"use client";
import {useMemo,useState,useRef,useEffect} from 'react';
import {ResponsiveContainer,ComposedChart,Area,Line,XAxis,YAxis,ReferenceArea,ReferenceLine,Tooltip,CartesianGrid} from 'recharts';
import {effortProfile} from './effort-profile-data';
import {cyclingReference,effortBadges} from './cycling-advanced-data';
import {activityClimbs,paceFromSpeed} from './activity-terrain-data';
import {sportFamily,cadenceUnit} from './sports';
import {Zap,Timer,Mountain,Table2,Check} from 'lucide-react';
import type {RouteSelection} from './route-geometry';
import {segmentStatistics} from './segment-statistics';
import {segmentShare} from './segment-share';
import {lapValues} from './activity-laps';
import {ExpandButton} from './expansion';
const baseSensors=[{key:'altitude',label:'Elevation',unit:'m',color:'#63977c'},{key:'power',label:'Power',unit:'W',color:'#8b5bd1'},{key:'heartrate',label:'HR',unit:'bpm',color:'#d75570'},{key:'cadence',label:'Cadence',unit:'rpm',color:'#bd8b35'}];
const valid=(v:any):v is number=>typeof v==='number'&&Number.isFinite(v);
const clock=(m:number)=>{const s=Math.round(m*60);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
export default function ActivityProfile({detail,expanded=false,onSelection,onShowMap}:{detail:any;expanded?:boolean;onSelection?:(selection:RouteSelection|null)=>void;onShowMap?:()=>void}){
 const streams=detail.seriesSampled?.data??{},step=detail.seriesSampled?.sampleSize,family=sportFamily(detail),cycling=family==='cycling',foot=['running','walking','hiking'].includes(family),swimming=family==='swimming',pace=foot||swimming,paceUnit=swimming?'/100m':'/km',cadenceLabel=cadenceUnit(family);
 const sensors=[...baseSensors,...(family==='running'?[{key:'stepLength',label:'Step length',unit:'cm',color:'#208f93'}]:[]),{key:'speed',label:pace?'Pace':'Speed',unit:pace?paceUnit:'km/h',color:'#3268d6'}];
 const motionLabel=(v:any)=>pace?paceFromSpeed(v,swimming?100:1000):valid(v)?(v*3.6).toFixed(1):'—';
 const available=sensors.filter(s=>streams[s.key]?.some(valid)),sensor=foot||swimming?(available.some(s=>s.key==='speed')?'speed':'heartrate'):available.some(s=>s.key==='power')?'power':available.some(s=>s.key==='speed')?'speed':'heartrate';
 const [visible,setVisible]=useState<string[]>(['altitude',sensor]),[mode,setMode]=useState('efforts'),[selection,setSelection]=useState<number|null>(null),[copy,setCopy]=useState(''),[fallback,setFallback]=useState('');
 useEffect(()=>{setVisible(['altitude',sensor]);setSelection(null)},[sensor]);
 const [shareOpen,setShareOpen]=useState(false),[shareShort,setShareShort]=useState(true),[shareTiming,setShareTiming]=useState(false);
 const chartRef=useRef<HTMLDivElement>(null),[showTable,setShowTable]=useState(false);
 const choose=(i:number)=>{setSelection(i);chartRef.current?.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};
 const profile=useMemo(()=>effortProfile(detail,sensor),[detail,sensor]);
 const climbs=useMemo(()=>cycling||foot?activityClimbs(detail,family):[],[detail,cycling,foot]);
 const rows=useMemo(()=>{if(!valid(step)||step<=0)return [];const n=Math.max(0,...sensors.map(s=>streams[s.key]?.length??0)),cap=detail.summary?.durationTotal;return Array.from({length:n},(_,i)=>({time:i*step/60,...Object.fromEntries(sensors.map(s=>[s.key,valid(streams[s.key]?.[i])?streams[s.key][i]:null]))})).filter(r=>!valid(cap)||r.time*60<=cap)},[detail,step]);
 const segments=mode==='efforts'?profile.efforts.map((e,i)=>({...e,label:`Effort ${i+1}`})):mode==='climbs'?climbs.map((c,i)=>({...c,start:c.start/60,end:c.end/60,label:`Climb ${i+1}`})):mode==='laps'?profile.laps.map(l=>({...l,label:`Lap ${l.index}`})):[];
 const badges=(i:number)=>mode==='efforts'?effortBadges(profile.efforts,i):mode==='climbs'?[...(i===climbs.reduce((best,c,j)=>c.end-c.start>climbs[best].end-climbs[best].start?j:best,0)?['Longest climb']:[]),...(i===climbs.reduce((best,c,j)=>c.gain>climbs[best].gain?j:best,0)?['Most elevation']:[])]:[];
 const badgeIcons=(i:number)=><span className="profile-row-badges">{badges(i).map(b=><span key={b} title={b} aria-label={b}>{/Longest/.test(b)?<Timer size={12}/>:b==='Most elevation'?<Mountain size={12}/>:b==='Repeat matched'?<Check size={12}/>:<Zap size={12}/>}</span>)}</span>;
 const selected=selection===null?null:segments[selection],part=selected?rows.filter(r=>r.time>=selected.start&&r.time<selected.end):rows;
 useEffect(()=>{onSelection?.(selected?{start:selected.start,end:selected.end,label:selected.label}:null)},[selected?.start,selected?.end,selected?.label,onSelection]);
 const mean=(key:string)=>{const recorded=mode==='laps'&&selection!==null?lapValues(detail.laps?.[selection]??{}):null;if(recorded&&valid(recorded[key]))return recorded[key];const v=part.map((r:any)=>r[key]).filter(v=>valid(v)&&(key==='heartrate'||key==='cadence'?v>0:true));return v.length?v.reduce((a,b)=>a+b,0)/v.length:null};
 const strideLength=family==='running'?mean('stepLength'):null,speed=mean('speed'),power=mean('power'),hr=mean('heartrate'),cadence=mean('cadence'),ref=cyclingReference(detail),stride=Math.max(1,Math.ceil(rows.length/650)),chartRows=rows.filter((_,i)=>i%stride===0||i===rows.length-1);
 const changeMode=(m:string)=>{setMode(m);setSelection(null);setCopy('');setFallback('')};
 const shareText=segmentShare({title:detail.title??'',sport:family,date:detail.date&&!Number.isNaN(Date.parse(detail.date))?new Date(detail.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):undefined,mode,short:shareShort,timing:shareTiming,segments:segments.map((s,i)=>{const sample=rows.filter(r=>r.time>=s.start&&r.time<s.end),recorded=mode==='laps'?lapValues(detail.laps?.[i]??{}):null,avg=(key:string)=>{if(recorded&&valid(recorded[key]))return recorded[key];const values=sample.map((r:any)=>r[key]).filter(v=>valid(v)&&(key==='heartrate'?v>0:true));return values.length?values.reduce((a,b)=>a+b,0)/values.length:null};return {...s,power:avg('power'),speed:avg('speed'),hr:avg('heartrate'),badges:badges(i)}})});
 async function copySegments(){try{await navigator.clipboard.writeText(shareText);setCopy('Copied — ready to paste');setFallback('')}catch{setFallback(shareText);setCopy('Select and copy the preview below')}}

 if(!rows.length)return <p className="activity-data-note">The interactive profile needs timed sensor data. Recorded laps remain available in the Laps tab.</p>;
 return <section className="unified-profile"><header><div><h3>Activity profile</h3><small>One timeline · toggle your layers</small></div>{!expanded&&<ExpandButton title="Activity profile"><ActivityProfile detail={detail} expanded onSelection={onSelection}/></ExpandButton>}</header>
 <div className="unified-toggles" aria-label="Chart layers">{available.map(s=><button key={s.key} type="button" aria-pressed={visible.includes(s.key)} onClick={()=>setVisible(v=>v.includes(s.key)?v.filter(k=>k!==s.key):[...v,s.key])}><i style={{background:s.color}}/>{s.label}</button>)}</div>
 <div ref={chartRef} style={{height:expanded?360:200,scrollMarginTop:80,position:'relative'}}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartRows} margin={{top:10,right:8,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={v=>`${Math.round(v)}m`} tick={{fontSize:10}} height={23}/><YAxis yAxisId="overlay" hide domain={[0,1]}/>{available.map(s=><YAxis key={s.key} yAxisId={s.key} hide domain={s.key==='altitude'?['auto','auto']:[0,'auto']}/>)}{segments.map((s,i)=>mode==='laps'?<ReferenceLine key={i} yAxisId="overlay" x={s.start} stroke="#9aa8ba" strokeDasharray="2 4"/>:<ReferenceArea key={i} yAxisId="overlay" y1={0} y2={1} x1={s.start} x2={s.end} fill={mode==='climbs'?'#63977c':'#d6a147'} fillOpacity={.1}/>)}{available.filter(s=>visible.includes(s.key)).map(s=>s.key==='altitude'?<Area key={s.key} yAxisId={s.key} dataKey={s.key} name={`${s.label} · ${s.unit}`} stroke={s.color} fill={s.color} fillOpacity={.12} isAnimationActive={false}/>:<Line key={s.key} yAxisId={s.key} dataKey={s.key} name={`${s.label} · ${s.key==='cadence'?cadenceLabel:s.unit}`} stroke={s.color} dot={false} strokeWidth={1.4} isAnimationActive={false}/>)}{selected&&<><ReferenceArea yAxisId="overlay" y1={0} y2={1} x1={selected.start} x2={selected.end} fill="#6366f1" fillOpacity={.23} stroke="#4f46e5" strokeWidth={2} zIndex={500}/><ReferenceLine yAxisId="overlay" x={selected.start} stroke="#4f46e5" strokeWidth={2} zIndex={500} label={{value:selected.label,position:'insideTopRight',fill:'#4338ca',fontSize:11}}/><ReferenceLine yAxisId="overlay" x={selected.end} stroke="#4f46e5" strokeWidth={2} strokeDasharray="3 2" zIndex={500}/></>}<Tooltip wrapperStyle={{pointerEvents:'none'}} contentStyle={{fontSize:11,padding:6,borderRadius:8}} labelFormatter={v=>clock(Number(v))+' elapsed'} formatter={(v:any,n:any)=>[String(n).startsWith('Pace')||String(n).startsWith('Speed')?motionLabel(Number(v)):Math.round(Number(v)),n]}/></ComposedChart></ResponsiveContainer>{selected&&rows.at(-1)!.time>0&&<div className="profile-highlight-plane" aria-label={`${selected.label}: ${clock(selected.start)} to ${clock(selected.end)} elapsed`}><div className="profile-highlight-band" style={{left:`${Math.max(0,selected.start/rows.at(-1)!.time*100)}%`,width:`${Math.max(.3,(Math.min(selected.end,rows.at(-1)!.time)-selected.start)/rows.at(-1)!.time*100)}%`}}><span>{selected.label}</span></div></div>}</div>
 <div className="unified-modes" aria-label="Profile overlays">{[['none','Overview'],['efforts',`Efforts ${profile.efforts.length}`],...(cycling||foot?[['climbs',`Climbs ${climbs.length}`]]:[]),['laps',`Laps ${profile.laps.length}`]].map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>changeMode(id)}>{label}</button>)}</div>
 {mode!=='none'&&<div className="unified-segments" aria-label={`Select ${mode}`}>{segments.length?segments.map((s,i)=><button key={i} aria-pressed={selection===i} onClick={()=>choose(i)}><b>{i+1}</b><span>{clock(s.end-s.start)}<small>min:sec</small></span>{badgeIcons(i)}</button>):<small>{mode==='laps'&&profile.reason?profile.reason:`No ${mode} detected in the available samples.`}</small>}</div>}
 <div className="unified-selection" aria-live="polite"><strong>{selected?`${selected.label} · ${clock(selected.start)} → ${clock(selected.end)}`:'Whole activity'}</strong>{selected&&onShowMap&&!expanded&&<button className="profile-show-map" onClick={onShowMap}>View on map ↑</button>}<div>{speed!==null&&<span><b>{motionLabel(speed)}</b> {pace?paceUnit:'km/h'}</span>}{power!==null&&cycling&&<span><b>{Math.round(power)}</b> W{cycling&&ref.weight?` · ${(power/ref.weight).toFixed(2)} W/kg`:''}{cycling&&ref.ftp?` · ${Math.round(power/ref.ftp*100)}% FTP`:''}</span>}{hr!==null&&<span><b>{Math.round(hr)}</b> bpm</span>}{cadence!==null&&<span><b>{Math.round(cadence)}</b> {cadenceLabel} <small>moving cadence</small></span>}{strideLength!==null&&<span><b>{Math.round(strideLength)}</b> cm step length</span>}{selected&&'gain' in selected&&valid(selected.gain)&&<span>{selected.gain<0?'↓':'↑'} {Math.abs(Math.round(selected.gain))} m <small>{mode==='efforts'?'net':'gain'}</small></span>}{selected&&'grade' in selected&&valid(selected.grade)&&<span>{selected.grade.toFixed(1)}% grade</span>}</div></div>

 {mode!=='none'&&<div className="profile-table-toolbar"><button type="button" aria-expanded={showTable} onClick={()=>setShowTable(v=>!v)}><Table2 size={13}/>{showTable?'Hide table':'Table'} · {mode}</button><button type="button" aria-expanded={shareOpen} onClick={()=>setShareOpen(v=>!v)}>Copy / share text</button></div>}
 {mode!=='none'&&showTable&&<div className="unified-data-table stacked-segment-table"><table><caption>{mode==='climbs'?'Detected climbs':mode==='efforts'?'Detected efforts':'Recorded laps'} · avg / max</caption><thead><tr><th>Segment</th><th>{cycling?'Power':pace?'Pace':'Output'}</th><th>Heart rate</th><th>Cadence</th></tr></thead><tbody>{segments.map((s,i)=>{
 const lap=mode==='laps'?lapValues(detail.laps?.[i]??{}):null,samples=rows.filter(r=>r.time>=s.start&&r.time<s.end),avg=(key:string)=>{if(lap&&valid(lap[key]))return lap[key];const v=samples.map((r:any)=>r[key]).filter(v=>valid(v)&&(key==='heartrate'||key==='cadence'?v>0:true));return v.length?v.reduce((a,b)=>a+b,0)/v.length:null},v=avg('speed'),p=avg('power'),h=avg('heartrate'),c=avg('cadence'),sl=family==='running'?avg('stepLength'):null,gain=lap&&valid(lap.ascent)?lap.ascent:'gain' in s&&valid(s.gain)?s.gain:null,stats=segmentStatistics(samples,step,(s.end-s.start)*60,lap),fmt=(n:any,u:string)=>valid(n)?`${Math.round(n)} ${u}`:'—';
 return <tr key={i} className={selection===i?'is-selected':''} onClick={()=>choose(i)}><td><button aria-label={`Highlight ${s.label}`} aria-pressed={selection===i} onClick={e=>{e.stopPropagation();choose(i)}}>{s.label}{badgeIcons(i)}</button><strong>{clock(s.end-s.start)} <small>min:sec</small></strong><small>At {clock(s.start)}</small>{gain!==null&&<small>{gain<0?'↓':'↑'} {Math.abs(Math.round(gain))} m{lap&&valid(lap.descent)?` · ↓ ${Math.round(lap.descent)} m`:''}</small>}{'grade' in s&&valid(s.grade)&&<small>{s.grade.toFixed(1)}% gradient</small>}{lap&&valid(lap.distance)&&<small>{(lap.distance/1000).toFixed(2)} km</small>}</td>
 <td>{cycling?<><strong>{fmt(p,'W')}</strong><small>Average power</small><span>Max {fmt(stats.maxPower,'W')}</span><span title="Estimated normalized power; requires at least 5 minutes of complete samples at 10-second resolution or better">NP {fmt(stats.normalized,'W')}</span>{stats.normalized===null&&<small>{s.end-s.start<5?'Under 5 min':'Incomplete samples'}</small>}{p!==null&&ref.weight&&<span>{(p/ref.weight).toFixed(2)} W/kg</span>}{p!==null&&ref.ftp&&<small>{Math.round(p/ref.ftp*100)}% FTP avg</small>}</>:<><strong>{motionLabel(v)} <small>{pace?paceUnit:'km/h'}</small></strong><small>Average {pace?'pace':'speed'}</small><span>Best {motionLabel(stats.maxSpeed)}</span><small>{pace?paceUnit:'km/h'} · peak sample</small>{p!==null&&<><span>{Math.round(p)} W avg</span><small>Max {fmt(stats.maxPower,'W')}</small></>}</>}</td>
 <td><strong>{fmt(h,'bpm')}</strong><small>Average HR</small><span>Max {fmt(stats.maxHR,'bpm')}</span></td><td><strong>{c===null?'—':Math.round(c)}</strong><small>{cadenceLabel} avg</small><span>Max {stats.maxCadence===null?'—':Math.round(stats.maxCadence)}</span><small>{cadenceLabel}</small>{sl!==null&&<><span>{Math.round(sl)} cm</span><small>Avg step length</small></>}</td></tr>})}</tbody></table>{!segments.length&&<p>No aligned {mode} available.</p>}<p className="profile-badge-legend">{mode==='climbs'?'◷ Longest climb · △ Most elevation':mode==='efforts'?'⚡ Highest output / fastest pace · ◷ Longest · ✓ Consistent repeat':'Recorded averages where supplied; sample-derived values otherwise'}</p><p className="profile-badge-legend">NP = estimated normalized power, not another average. Requires ≥5 min of complete power samples, ≤10s apart. Rolling windows approximate 30s at the recorded resolution. Max values use recorded lap maxima when supplied, otherwise sampled peaks; short spikes may be sensor noise. Running pace is not normalized power.</p></div>}

 {shareOpen&&mode!=='none'&&<div className="segment-share-preview"><div><label>Format <select aria-label="Shared stats format" value={shareShort?'highlights':'all'} onChange={e=>{setShareShort(e.target.value==='highlights');setCopy('')}}><option value="highlights">Highlights · up to 3</option><option value="all">All {mode}</option></select></label><label><input type="checkbox" checked={shareTiming} onChange={e=>{setShareTiming(e.target.checked);setCopy('')}}/> Include start times</label></div><pre>{shareText}</pre><button onClick={copySegments}>Copy message</button><span role="status">{copy}</span>{fallback&&<textarea aria-label="Message to copy manually" readOnly value={shareText} onFocus={e=>e.currentTarget.select()}/>}</div>}
 <details className="unified-notes"><summary>Scales & detection</summary><p>Pace is shown as min/km (swimming: min/100m); faster pace rises on the chart. Stops show no pace. Each layer has its own scale; line heights are not directly comparable. Hover or touch for values. Recorded laps use recorded averages where available; detected intervals use original samples. Sampled cadence excludes zeros. Gaps remain empty.</p><p>Efforts use {sensor==='speed'?(pace?'pace':'speed'):sensor==='power'?'power':'heart rate'}: {sensor==='speed'?'10s':'30s'} smoothing, at least 30s above this session’s relative cutoff. Climbs: {foot?'45s minimum, 12m net gain and 1% average gradient':'2 min minimum, 20m net gain and 2% average gradient'}. Smoothed elevation; small dips and flats are allowed. Estimates, not recorded laps.</p>{cycling&&power!==null&&<p>{ref.weight?`${ref.weight} kg · ${ref.weightLabel}. `:''}{ref.ftp?`${ref.ftp} W · ${ref.label}.`:''}</p>}</details></section>;
}
