"use client";
import {useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {ResponsiveContainer,ComposedChart,Area,Line,XAxis,YAxis,ReferenceArea,ReferenceLine,Tooltip,CartesianGrid} from 'recharts';
import {effortProfile} from './effort-profile-data';
import {cyclingReference,effortBadges} from './cycling-advanced-data';
import {activityClimbAnalysis,paceFromSpeed} from './activity-terrain-data';
import {sportFamily,cadenceUnit} from './sports';
import {Zap,Timer,Mountain,Table2,Check,ChevronLeft,ChevronRight,Focus} from 'lucide-react';
import type {RouteSelection} from './route-geometry';
import {profileSegmentStats} from './profile-segment-data';
import {segmentShare} from './segment-share';
import ActivityLaps,{lapValues} from './activity-laps';
import {ExpandButton} from './expansion';
import {climbGradeOptions,normalizeCyclingClimbSettings,readCyclingClimbSettings,saveCyclingClimbSettings,type CyclingClimbSettings} from './climb-settings';
const baseSensors=[{key:'altitude',label:'Elevation',unit:'m',color:'#63977c'},{key:'power',label:'Power',unit:'W',color:'#8b5bd1'},{key:'heartrate',label:'HR',unit:'bpm',color:'#d75570'},{key:'cadence',label:'Cadence',unit:'rpm',color:'#bd8b35'}];
const valid=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const measured=(v:unknown,key:string):v is number=>valid(v)&&(['heartrate','cadence','stepLength'].includes(key)?v>0:['power','speed','distance'].includes(key)?v>=0:true);
const clock=(m:number)=>{const s=Math.max(0,Math.round(m*60));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
const distanceLabel=(d:number|null)=>d===null?'—':d<1000?`${Math.round(d)} m`:`${(d/1000).toFixed(2)} km`;
type ProfileState={mode:string;sensor:string|null;selection:number|null;focus:boolean;sort:string;layers:string[]|null;detail:any;climbSettings:CyclingClimbSettings};
function profileStore(detail:any){
 let value:ProfileState={mode:'efforts',sensor:null,selection:null,focus:false,sort:'timeline',layers:null,detail,climbSettings:readCyclingClimbSettings()};
 const listeners=new Set<()=>void>();
 return {getSnapshot:()=>value,subscribe:(listener:()=>void)=>{listeners.add(listener);return()=>{listeners.delete(listener)}},set:(patch:Partial<ProfileState>)=>{value={...value,...patch};listeners.forEach(listener=>listener())}};
}
type SelectionStore=ReturnType<typeof profileStore>;
type ProfileSegment={start:number;end:number;label:string;gain?:number|null;grade?:number;distance?:number};
type ProfileRow={time:number;[key:string]:number|null};
function sameProfileData(a:any,b:any){
 return a.seriesSampled===b.seriesSampled&&a.laps===b.laps&&a.id===b.id&&a.sportType===b.sportType&&a.subSportType===b.subSportType&&a.title===b.title&&a.date===b.date&&a.summary?.duration===b.summary?.duration&&a.summary?.durationTotal===b.summary?.durationTotal&&a.summary?.ftp===b.summary?.ftp&&['manualReference','fitness','fitnessHistory','profile'].every(key=>a.cyclingContext?.[key]===b.cyclingContext?.[key]);
}
export default function ActivityProfile({detail:incomingDetail,expanded=false,onSelection,selectionStore}:{detail:any;expanded?:boolean;onSelection?:(selection:RouteSelection|null)=>void;selectionStore?:SelectionStore}){
 const [ownedStore]=useState(()=>profileStore(incomingDetail)),store=selectionStore??ownedStore,state=useSyncExternalStore(store.subscribe,store.getSnapshot,store.getSnapshot),detail=state.detail;
 // The expanded widget is a retained element. Share new same-session streams
 // with it so source choices and interval indices always refer to one revision.
 useEffect(()=>{if(!expanded&&!sameProfileData(state.detail,incomingDetail)){
  const a=state.detail,b=incomingDetail,boundsChanged=a.seriesSampled!==b.seriesSampled||a.laps!==b.laps||a.sportType!==b.sportType||a.subSportType!==b.subSportType||a.summary?.duration!==b.summary?.duration||a.summary?.durationTotal!==b.summary?.durationTotal;
  store.set({detail:incomingDetail,...(boundsChanged?{selection:null,focus:false}:{})});
 }},[incomingDetail,expanded,store,state.detail]);
 const streams=detail.seriesSampled?.data??{},step=detail.seriesSampled?.sampleSize,family=sportFamily(detail),cycling=family==='cycling',foot=['running','walking','hiking'].includes(family),swimming=family==='swimming',pace=foot||swimming,paceUnit=swimming?'/100m':'/km',cadenceLabel=cadenceUnit(family);
 const sensors=useMemo(()=>[...baseSensors,...(family==='running'?[{key:'stepLength',label:'Step length',unit:'cm',color:'#208f93'}]:[]),{key:'speed',label:pace?'Pace':'Speed',unit:pace?paceUnit:'km/h',color:'#3268d6'}],[family,pace,paceUnit]);
 const available=sensors.filter(s=>Array.isArray(streams[s.key])&&streams[s.key].some((v:unknown)=>measured(v,s.key)));
 const defaultSensor=cycling?(available.some(s=>s.key==='power')?'power':available.some(s=>s.key==='heartrate')?'heartrate':'speed'):pace?(available.some(s=>s.key==='speed')?'speed':available.some(s=>s.key==='power')?'power':'heartrate'):available.some(s=>s.key==='power')?'power':available.some(s=>s.key==='speed')?'speed':'heartrate';
 const sensor=state.sensor&&available.some(s=>s.key===state.sensor)?state.sensor:defaultSensor,mode=state.mode,speedSections=cycling&&sensor==='speed',effortLabel=speedSections?'Fast sections':'Efforts';
 const motionLabel=(v:unknown)=>pace?paceFromSpeed(v,swimming?100:1000):valid(v)?(v*3.6).toFixed(1):'—';
 const visible=state.layers??['altitude',sensor];
 const [copy,setCopy]=useState(''),[fallback,setFallback]=useState(''),[copyText,setCopyText]=useState(''),[shareOpen,setShareOpen]=useState(false),[shareShort,setShareShort]=useState(true),[shareTiming,setShareTiming]=useState(false),[showTable,setShowTable]=useState(false);
 const chartRef=useRef<HTMLDivElement>(null);
 const profile=useMemo(()=>effortProfile(detail,sensor,family),[detail,sensor,family]);
 const terrain=useMemo(()=>activityClimbAnalysis(detail,family,cycling?state.climbSettings:undefined),[detail,family,cycling,state.climbSettings]),climbs=terrain.climbs;
 const rows=useMemo<ProfileRow[]>(()=>{
  if(!valid(step)||step<=0)return [];
  const keys=[...sensors.map(s=>s.key),'distance'],n=keys.reduce((max,key)=>Math.max(max,streams[key]?.length??0),0),cap=detail.summary?.durationTotal;
  return Array.from({length:n},(_,i)=>({time:i*step/60,...Object.fromEntries(keys.map(key=>[key,measured(streams[key]?.[i],key)?streams[key][i]:null]))})).filter(r=>!valid(cap)||r.time*60<=cap);
 },[detail,step,sensors,streams]);
 const segments=useMemo<ProfileSegment[]>(()=>mode==='efforts'?profile.efforts.map((e,i)=>({...e,label:`${speedSections?'Section':'Effort'} ${i+1}`})):mode==='climbs'?climbs.map((c,i)=>({...c,start:c.start/60,end:c.end/60,label:`Climb ${i+1}`})):mode==='laps'?profile.laps.map(l=>({...l,label:`Lap ${l.index}`})):[],[mode,profile,climbs,speedSections]);
 const metrics=useMemo(()=>segments.map((s,i)=>profileSegmentStats(rows,step,s,mode==='laps'?lapValues(detail.laps?.[i]??{}):null)),[segments,rows,step,mode,detail.laps]);
 const selectedIndex=state.selection!==null&&segments[state.selection]?state.selection:null,selected=selectedIndex===null?null:segments[selectedIndex];
 const extent=rows.length&&valid(step)?Math.min(rows.at(-1)!.time+step/60,valid(detail.summary?.durationTotal)?detail.summary.durationTotal/60:Infinity):0;
 const whole=useMemo(()=>profileSegmentStats(rows,step,{start:0,end:extent}),[rows,step,extent]);
 const current=selectedIndex===null?whole:metrics[selectedIndex],{speed,power,heartrate:hr,cadence,stepLength:strideLength}=current.mean,ref=cyclingReference(detail);
 const output=(i:number)=>metrics[i]?.mean[sensor as 'power'|'speed'|'heartrate']??null;
 const outputLabel=(i:number)=>{const v=output(i);return v===null?'—':sensor==='power'?`${Math.round(v)} W`:sensor==='heartrate'?`${Math.round(v)} bpm`:`${motionLabel(v)} ${pace?paceUnit:'km/h'}`};
 const ordered=segments.map((s,i)=>({segment:s,index:i})).sort((a,b)=>state.sort==='longest'?(b.segment.end-b.segment.start)-(a.segment.end-a.segment.start):state.sort==='gain'?(b.segment.gain??-Infinity)-(a.segment.gain??-Infinity):state.sort==='output'?(output(b.index)??-Infinity)-(output(a.index)??-Infinity):a.index-b.index);
 const selectedPosition=ordered.findIndex(s=>s.index===selectedIndex);
 const clearSelection=()=>store.set({selection:null,focus:false});
 const choose=(i:number,scroll=true)=>{store.set({selection:i});if(scroll&&expanded)chartRef.current?.scrollIntoView({block:'nearest',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};
 const changeMode=(m:string)=>{store.set({mode:m,selection:null,focus:false,sort:'timeline'});setCopy('');setFallback('')};
 const changeClimbSettings=(patch:Partial<CyclingClimbSettings>)=>{const climbSettings=normalizeCyclingClimbSettings({...state.climbSettings,...patch});store.set({climbSettings,selection:null,focus:false});saveCyclingClimbSettings(climbSettings);setCopy('');setFallback('')};
 useEffect(()=>{onSelection?.(selected?{start:selected.start,end:selected.end,label:selected.label}:null)},[selected?.start,selected?.end,selected?.label,onSelection]);
 const focused=!!selected&&state.focus,padding=selected?Math.max(.25,(selected.end-selected.start)*.15):0,domain:[number,number]=focused?[Math.max(0,selected!.start-padding),Math.min(extent,selected!.end+padding)]:[0,Math.max(extent,.01)];
 const chartRows=useMemo(()=>{
  const section=rows.filter(r=>r.time>=domain[0]&&r.time<=domain[1]),stride=Math.max(1,Math.ceil(section.length/650));
  const boundaries=new Set(segments.flatMap(s=>[Math.floor(s.start*60/step),Math.ceil(s.start*60/step),Math.floor(s.end*60/step)-1,Math.ceil(s.end*60/step)]));
  return section.filter((row,i)=>i%stride===0||i===section.length-1||boundaries.has(Math.round(row.time*60/step))||sensors.some(s=>i>0&&valid(row[s.key])!==valid(section[i-1][s.key])||i<section.length-1&&valid(row[s.key])!==valid(section[i+1][s.key])));
 },[rows,domain[0],domain[1],sensors,segments,step]);
 const badges=(i:number)=>mode==='efforts'?effortBadges(profile.efforts,i):mode==='climbs'?[...(i===climbs.reduce((best,c,j)=>c.end-c.start>climbs[best].end-climbs[best].start?j:best,0)?['Longest climb']:[]),...(i===climbs.reduce((best,c,j)=>c.gain>climbs[best].gain?j:best,0)?['Most elevation']:[])]:[];
 const badgeIcons=(i:number)=><span className="profile-row-badges">{badges(i).map(b=><span key={b} title={b} aria-label={b}>{/Longest/.test(b)?<Timer size={12}/>:b==='Most elevation'?<Mountain size={12}/>:b==='Repeat matched'?<Check size={12}/>:<Zap size={12}/>}</span>)}</span>;
 const totalSeconds=metrics.reduce((sum,m)=>sum+m.durationSeconds,0),totalGain=climbs.reduce((sum,c)=>sum+c.gain,0);
 const shareText=segmentShare({title:detail.title??'',sport:family,date:detail.date&&!Number.isNaN(Date.parse(detail.date))?new Date(detail.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):undefined,mode:speedSections&&mode==='efforts'?'sections':mode,source:sensor,short:shareShort,timing:shareTiming,segments:segments.map((s,i)=>({...s,durationSeconds:metrics[i].durationSeconds,power:metrics[i].mean.power,speed:metrics[i].mean.speed,hr:metrics[i].mean.heartrate,badges:badges(i)}))});
 async function copySegments(){try{await navigator.clipboard.writeText(shareText);setCopyText(shareText);setCopy('Copied — ready to paste');setFallback('')}catch{setCopyText(shareText);setFallback(shareText);setCopy('Select and copy the preview below')}}
 const emptyReason=mode==='climbs'?terrain.reason:mode==='efforts'?profile.effortReason:profile.reason,cutoff=profile.effortMethod.cutoff;
 const cutoffLabel=cutoff===null?'—':sensor==='power'?`${Math.round(cutoff)} W`:sensor==='heartrate'?`${Math.round(cutoff)} bpm`:`${motionLabel(cutoff)} ${pace?paceUnit:'km/h'}`;
 if(!rows.length)return <p className="activity-data-note">The interactive profile needs timed sensor data. Recorded laps remain available in the Laps tab.</p>;
 return <section className={`unified-profile effort-analysis${expanded?' is-expanded':''}`} data-mode={mode}><header><div><h3>Efforts & terrain</h3><small>Choose a section to compare output and terrain</small></div>{!expanded&&<ExpandButton title="Efforts & terrain"><ActivityProfile detail={detail} expanded selectionStore={store}/></ExpandButton>}</header>
 <div className="unified-modes" aria-label="Profile overlays">{[['none','Overview'],['efforts',`${effortLabel} ${profile.efforts.length}`],...(cycling||foot?[['climbs',`Climbs ${climbs.length}`]]:[]),['laps',`Laps ${detail.laps?.length??profile.laps.length}`]].map(([id,label])=><button key={id} type="button" aria-pressed={mode===id} onClick={()=>changeMode(id)}>{label}</button>)}</div>
 {mode!=='none'&&<div className="effort-analysis-toolbar">{mode==='efforts'&&available.some(s=>['power','speed','heartrate'].includes(s.key))&&<label>Detect by <select aria-label="Effort detection source" value={sensor} onChange={e=>{store.set({sensor:e.target.value,selection:null,focus:false,layers:null});setCopy('');setFallback('')}}>{available.filter(s=>['power','speed','heartrate'].includes(s.key)).map(s=><option key={s.key} value={s.key}>{s.key==='heartrate'?'Heart rate':s.key==='speed'&&cycling?'Speed · fast sections':s.label}</option>)}</select></label>}{mode==='climbs'&&cycling&&<><label>Climb bounds <select aria-label="Cycling climb bounds" value={state.climbSettings.mode} onChange={e=>changeClimbSettings({mode:e.target.value==='whole'?'whole':'steep'})}><option value="steep">Steep sections</option><option value="whole">Whole climb</option></select></label>{state.climbSettings.mode==='steep'&&<label>Min gradient <select aria-label="Minimum cycling climb gradient" value={state.climbSettings.minGradePercent} onChange={e=>changeClimbSettings({minGradePercent:Number(e.target.value)})}>{climbGradeOptions.map(grade=><option key={grade} value={grade}>{grade}%</option>)}</select></label>}</>}{segments.length>1&&<label>Order <select aria-label="Segment order" value={state.sort} onChange={e=>store.set({sort:e.target.value})}><option value="timeline">Time</option><option value="longest">Longest</option>{mode==='climbs'?<option value="gain">Most climbing</option>:<option value="output">{sensor==='speed'&&pace?'Fastest':sensor==='power'?'Highest power':sensor==='heartrate'?'Highest HR':'Fastest'}</option>}</select></label>}<span>{segments.length?`${segments.length} ${mode==='climbs'?(segments.length===1?'climb':'climbs'):mode==='laps'?(segments.length===1?'lap':'laps'):speedSections?(segments.length===1?'section':'sections'):(segments.length===1?'effort':'efforts')} · ${clock(totalSeconds/60)}${mode==='climbs'?` · +${Math.round(totalGain)} m`:''}`:''}</span></div>}
 {mode!=='none'&&<div className="unified-segments effort-segments" aria-label={`Select ${mode}`}>{ordered.length?ordered.map(({segment:s,index:i})=><button key={i} type="button" aria-pressed={selectedIndex===i} onClick={()=>choose(i)}><span className="effort-segment-title">{s.label}{badgeIcons(i)}</span><strong>{mode==='climbs'&&valid(s.gain)?`+${Math.round(s.gain)} m`:outputLabel(i)}</strong><small>{clock(metrics[i].durationSeconds/60)}{mode==='climbs'&&valid(s.grade)?` · ${s.grade.toFixed(1)}%`:metrics[i].distance!==null?` · ${distanceLabel(metrics[i].distance)}`:''}</small></button>):<p className="effort-empty">{emptyReason??`No ${mode} detected in the available samples.`}</p>}</div>}
 {speedSections&&mode==='efforts'&&<p className="effort-source-note">Fast sections show speed changes. Use power or heart rate to assess exertion.</p>}
 <div className="unified-toggles" aria-label="Chart layers">{available.map(s=><button key={s.key} type="button" aria-pressed={visible.includes(s.key)} onClick={()=>store.set({layers:visible.includes(s.key)?visible.filter(k=>k!==s.key):[...visible,s.key]})}><i style={{background:s.color}}/>{s.label}</button>)}</div>
 <div ref={chartRef} className="effort-timeline" style={{height:expanded?340:'var(--effort-chart-height, 180px)',scrollMarginTop:80}}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartRows} margin={{top:10,right:8,left:0,bottom:0}} onClick={event=>{const at=event.activeLabel;if(!valid(at))return;const index=segments.findIndex(s=>at>=s.start&&at<s.end);if(index>=0)choose(index,false)}}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="time" type="number" domain={domain} allowDataOverflow tickFormatter={v=>`${Math.round(v)}m`} tick={{fontSize:10}} height={23}/><YAxis yAxisId="overlay" hide domain={[0,1]} allowDataOverflow/>{available.map(s=><YAxis key={s.key} yAxisId={s.key} hide domain={s.key==='altitude'?['auto','auto']:[0,'auto']}/>)}{segments.filter(s=>s.end>=domain[0]&&s.start<=domain[1]).map(s=>mode==='laps'?<ReferenceLine key={s.label} yAxisId="overlay" x={s.start} stroke="#9aa8ba" strokeDasharray="2 4"/>:<ReferenceArea key={s.label} yAxisId="overlay" y1={0} y2={1} x1={Math.max(domain[0],s.start)} x2={Math.min(domain[1],s.end)} fill={mode==='climbs'?'#63977c':'#d6a147'} fillOpacity={.13}/>)}{available.filter(s=>visible.includes(s.key)).map(s=>s.key==='altitude'?<Area key={s.key} yAxisId={s.key} dataKey={s.key} name={`${s.label} · ${s.unit}`} stroke={s.color} fill={s.color} fillOpacity={.1} connectNulls={false} isAnimationActive={false}/>:<Line key={s.key} yAxisId={s.key} dataKey={s.key} name={`${s.label} · ${s.key==='cadence'?cadenceLabel:s.unit}`} stroke={s.color} dot={false} strokeWidth={1.4} connectNulls={false} isAnimationActive={false}/>)}{selected&&<><ReferenceArea yAxisId="overlay" y1={0} y2={1} x1={Math.max(domain[0],selected.start)} x2={Math.min(domain[1],selected.end)} fill="#6366f1" fillOpacity={.18} stroke="#4f46e5" strokeWidth={1}/><ReferenceLine yAxisId="overlay" x={selected.start} stroke="#4f46e5" strokeWidth={1.5}/><ReferenceLine yAxisId="overlay" x={selected.end} stroke="#4f46e5" strokeWidth={1.5} strokeDasharray="3 2"/></>}<Tooltip wrapperStyle={{pointerEvents:'none'}} contentStyle={{fontSize:11,padding:6,borderRadius:8}} labelFormatter={v=>clock(Number(v))+' recorded time'} formatter={(v:any,n:any)=>[String(n).startsWith('Pace')||String(n).startsWith('Speed')?motionLabel(Number(v)):Math.round(Number(v)),n]}/></ComposedChart></ResponsiveContainer></div>
 <div className="effort-navigation">{selected&&<><div><button type="button" aria-label="Previous segment" disabled={selectedPosition<=0} onClick={()=>choose(ordered[selectedPosition-1].index,false)}><ChevronLeft size={15}/></button><span>{selectedPosition+1} / {segments.length}</span><button type="button" aria-label="Next segment" disabled={selectedPosition>=ordered.length-1} onClick={()=>choose(ordered[selectedPosition+1].index,false)}><ChevronRight size={15}/></button></div><button type="button" aria-pressed={focused} onClick={()=>store.set({focus:!state.focus})}><Focus size={13}/>{focused?'Whole timeline':'Focus section'}</button><button type="button" onClick={clearSelection}>Whole activity</button></>}{!selected&&segments.length>0&&<small>Tap a section or its shaded area</small>}</div>
 <div className="unified-selection effort-readout" aria-live="polite"><header><strong>{selected?`${selected.label} · ${clock(selected.start)} → ${clock(selected.end)}`:'Whole activity'}</strong></header><div><span><b>{clock(current.durationSeconds/60)}</b><small>Duration</small></span>{current.distance!==null&&<span><b>{distanceLabel(current.distance)}</b><small>Distance</small></span>}{speed!==null&&<span><b>{motionLabel(speed)}</b> {pace?paceUnit:'km/h'}<small>Average {pace?'pace':'speed'}</small></span>}{power!==null&&<span><b>{Math.round(power)}</b> W<small>{cycling&&ref.ftp?`${Math.round(power/ref.ftp*100)}% FTP`:'Average power'}{cycling&&ref.weight?` · ${(power/ref.weight).toFixed(2)} W/kg`:''}</small></span>}{hr!==null&&<span><b>{Math.round(hr)}</b> bpm<small>Average HR</small></span>}{cadence!==null&&<span><b>{Math.round(cadence)}</b><small>{cadenceLabel} · moving</small></span>}{family==='running'&&strideLength!==null&&<span><b>{Math.round(strideLength)}</b> cm<small>Step length</small></span>}{selected&&valid(selected.gain)&&<span><b>{selected.gain<0?'−':'+'}{Math.abs(Math.round(selected.gain))}</b> m<small>{mode==='efforts'?'Net elevation':'Climbing'}</small></span>}{selected&&valid(selected.grade)&&<span><b>{selected.grade.toFixed(1)}%</b><small>Average gradient</small></span>}</div>{mode==='efforts'&&selectedIndex!==null&&selectedIndex>0&&<p className="effort-recovery">{clock(Math.max(0,segments[selectedIndex].start-segments[selectedIndex-1].end))} between this and the previous {speedSections?'section':'effort'}</p>}</div>
 {mode!=='none'&&<div className="profile-table-toolbar"><button type="button" aria-expanded={showTable} onClick={()=>setShowTable(v=>!v)}><Table2 size={13}/>{showTable?'Hide comparison':'Compare all'}</button><button type="button" aria-expanded={shareOpen} onClick={()=>setShareOpen(v=>!v)}>Copy / share text</button></div>}
 {mode==='laps'&&profile.reason&&<p className="activity-data-note">{profile.reason}</p>}
 {mode==='laps'&&showTable&&!profile.laps.length&&!!detail.laps?.length&&<ActivityLaps detail={detail}/>}
 {mode!=='none'&&showTable&&!(mode==='laps'&&!profile.laps.length&&detail.laps?.length)&&<div className="unified-data-table effort-comparison-table" tabIndex={0} aria-label="Segment comparison table; scroll horizontally for all measurements"><table><caption>{mode==='climbs'?'Climb comparison':mode==='efforts'?`${effortLabel} comparison`:'Recorded laps'}</caption><thead><tr><th>Section</th><th>{mode==='climbs'?'Terrain':'Duration / distance'}</th><th>{sensor==='power'?'Power':sensor==='heartrate'?'Heart rate':pace?'Pace':'Speed'}</th><th>HR / cadence</th></tr></thead><tbody>{ordered.map(({segment:s,index:i})=>{
  const m=metrics[i],recovery=i>0?Math.max(0,s.start-segments[i-1].end):null;
  return <tr key={i} className={selectedIndex===i?'is-selected':''} onClick={()=>choose(i)}><td><button type="button" aria-label={`Select ${s.label}`} aria-pressed={selectedIndex===i} onClick={e=>{e.stopPropagation();choose(i)}}>{s.label}{badgeIcons(i)}</button><small>At {clock(s.start)}</small>{mode==='efforts'&&recovery!==null&&<small>{clock(recovery)} between</small>}</td><td><strong>{clock(m.durationSeconds/60)}</strong><small>{distanceLabel(m.distance)}</small>{valid(s.gain)&&<span>{s.gain<0?'−':'+'}{Math.abs(Math.round(s.gain))} m</span>}{valid(s.grade)&&<small>{s.grade.toFixed(1)}% gradient</small>}</td><td><strong>{outputLabel(i)}</strong>{cycling&&m.mean.power!==null&&sensor!=='power'&&<small>{Math.round(m.mean.power)} W avg</small>}{cycling&&sensor==='power'&&ref.ftp&&m.mean.power!==null&&<small>{Math.round(m.mean.power/ref.ftp*100)}% FTP</small>}{cycling&&m.stats.normalized!==null&&<small title="Estimated normalized power">NP {Math.round(m.stats.normalized)} W</small>}{!cycling&&m.mean.power!==null&&<small>{Math.round(m.mean.power)} W avg</small>}</td><td><strong>{m.mean.heartrate!==null?`${Math.round(m.mean.heartrate)} bpm`:'—'}</strong><small>{m.mean.cadence!==null?`${Math.round(m.mean.cadence)} ${cadenceLabel}`:'—'}</small><small>{m.stats.maxHR!==null?`Max ${Math.round(m.stats.maxHR)} bpm`:''}</small></td></tr>;
 })}</tbody></table>{!segments.length&&<p>{emptyReason??`No aligned ${mode} available.`}</p>}</div>}
 {shareOpen&&mode!=='none'&&<div className="segment-share-preview"><div><label>Format <select aria-label="Shared stats format" value={shareShort?'highlights':'all'} onChange={e=>{setShareShort(e.target.value==='highlights');setCopy('')}}><option value="highlights">Highlights · up to 3</option><option value="all">All {mode}</option></select></label><label><input type="checkbox" checked={shareTiming} onChange={e=>{setShareTiming(e.target.checked);setCopy('')}}/> Include start times</label></div><pre>{shareText}</pre><button type="button" onClick={copySegments}>Copy message</button><span role="status">{copyText===shareText?copy:''}</span>{copyText===shareText&&fallback&&<textarea aria-label="Message to copy manually" readOnly value={shareText} onFocus={e=>e.currentTarget.select()}/>}</div>}
 <details className="unified-notes"><summary>Detection & chart scales</summary><p>{effortLabel} use {sensor==='speed'?(pace?'pace':'speed'):sensor==='power'?'power':'heart rate'} with {profile.effortMethod.smoothingSeconds}s smoothing and at least {profile.effortMethod.minSeconds}s sustained. This session’s cutoff: {cutoffLabel}. Relative changes within this session, rather than prescribed training zones. Missing samples and recorded stops break detection.</p>{(cycling||foot)&&<p>{terrain.method} Minimum {terrain.thresholds.minSeconds}s, {terrain.thresholds.minGainMetres} m gain and {terrain.thresholds.minGradePercent}% {terrain.mode==='steep'?'local gradient':'average gradient'}. {terrain.mode==='steep'?'Steep sections split at areas below the selected local cutoff.':'Small dips are tolerated.'} Stops and data gaps split climbs.</p>}<p>Each chart layer has its own scale. Faster pace rises; stops have no pace. Tap or hover for values. Detected boundaries follow the recorded sample timeline, which may omit watch pauses. Recorded laps keep their own averages and durations. Missing measurements stay blank.</p>{cycling&&<p>NP is an estimated normalized power, requiring at least 5 minutes of complete power samples at 10s resolution or better. {ref.ftp?`${ref.ftp} W · ${ref.label}.`:''}</p>}</details>
 </section>;
}
