"use client";
import {cachedWorkout,loadWorkout} from './workout-detail-cache';
import {LoadingState} from './loading-state';
import {effortExcluded} from './workout-exclusions';
import {useEffect,useMemo,useRef,useState,lazy,Suspense} from 'react';
import {Activity,ArrowUpRight,Download,FlaskConical,RefreshCw,Search,X} from 'lucide-react';
import {Area,Bar,CartesianGrid,ComposedChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';

import {sportFamily,sportName,sportDescription,cadenceUnit,runningPace,workoutSpeed} from "./sports";
import {RunReview,ZoneTrends} from "./run-review";
import {useExpand,ExpandButton} from './expansion';
import ActivitySummary from './activity-summary';
import ActivityLaps from './activity-laps';
import ActivityZones from './activity-zones';
import {SportIcon} from './dashboard-calendar';
const ActivityShare=lazy(()=>import('./activity-share'));
import TrainingLog from './training-log';
import CorosHub,{CorosBody} from './coros-hub';
import ManualBody from './manual-body';
import SleepRegularity from "./sleep-regularity";
import RouteMap from "./route-map";
import InjuryCheck from "./injury-check";
import DisciplinePanel from "./discipline-panel";
import Studio,{SignalLab} from './studio';
type Row=Record<string,any>;
export type Workout={nativeVersion?:number;provider?:string;analysisSource?:string;coros?:{labelId:string;sportType:number};fallbackId?:string;id:string;date:string;sportType:string;subSportType?:string;title?:string;sessionLabel?:string|null;summary?:Row;evidence?:{version:number;best:Record<string,any[]>;sampleSeconds:number|null;insightVersion?:number;sensors?:ReturnType<typeof import("./tredict-opportunities-data").sensorEvidence>;insights?:ReturnType<typeof import("./session-intelligence-data").runningSignals>;classification?:ReturnType<typeof import("./session-intelligence-data").classifySession>};analyzed?:boolean;hrHistogram?:{secondsByBpm:Record<string,number>;validSeconds:number;missingSeconds:number;sampleSeconds:number}|null};
export type AthleteData={provider?:string;sourceNote?:string;activities:Workout[];sleep:Record<string,number[]>;hrv:Record<string,number[]>;extra?:Row;sources?:Row;historyStart?:string;historyVersion?:number;historyComplete?:boolean;warnings?:string[];excludedWorkouts?:{id:string;date:string}[];syncedAt?:string};
export const labTabs=['Training log','Injury check','Performance studio','Training load','Performance lab','Recovery lab','Session explorer','Athlete & zones','Planning & gear','Data coverage'];
const colors=['#222222','#888888','#aaaaaa','#bbbbbb','#555555'];
export const label=(key:string)=>({strength_training:'Strength training',misc:'Other',vo2max:'VO₂ max',hrRestDynamic:'Daily resting HR',hrMaxDynamic:'Daily maximum HR',restingHeartrate:'Configured resting HR',hrMax:'Maximum HR',hrLth:'Lactate threshold HR',ftp:'Threshold power',ftpa:'Threshold pace',heartrate:'Heart rate',powerAerobicFactor:'Power aerobic factor',speedAerobicFactor:'Speed aerobic factor'}[key]||key.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()));
export const sport=sportFamily;
const num=(v:any):number|null=>typeof v==='number'&&Number.isFinite(v)?v:null;
const avg=(v:(number|null|undefined)[])=>{const a=v.filter((x):x is number=>typeof x==='number'&&Number.isFinite(x));return a.length?a.reduce((s,n)=>s+n,0)/a.length:null};
const fmt=(v:any,d=1)=>num(v)==null?'—':Number(v).toLocaleString('en-GB',{maximumFractionDigits:d});
const duration=(s:any)=>num(s)==null?'—':`${Math.floor(Math.round(s/60)/60)}h ${String(Math.round(s/60)%60).padStart(2,'0')}m`;
const day=(date:string)=>date.slice(0,10).replaceAll('-','');
const dateLabel=(date:string)=>new Date(date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'2-digit',timeZone:'UTC'});
const unit=(key:string,family='all')=>key==='cadence'?cadenceUnit(family):({vo2max:'ml/kg/min',heartrate:'bpm',heartrateMax:'bpm',hrMax:'bpm',hrLth:'bpm',hrRestDynamic:'bpm',hrMaxDynamic:'bpm',restingHeartrate:'bpm',power:'W',powerMax:'W',ftp:'W',ftpa:'s/km',pace:'s/km',paceMax:'s/km',cadence:'rpm / steps/min',calories:'kcal',distance:'m',duration:'s',durationTotal:'s',temperature:'°C',groundContactTime:'ms',flightTime:'ms',stepLength:'cm',weightInKilograms:'kg',bodyFatInPercent:'%',bodyWaterInPercent:'%',muscleMassInPercent:'%',bodyHeightInCentimeter:'cm',speed:'m/s',speedMax:'m/s'}[key]||'');
function flatten(obj:any,prefix=''):Row{return Object.fromEntries(Object.entries(obj??{}).flatMap(([k,v])=>{const key=prefix?`${prefix}.${k}`:k;return v&&typeof v==='object'&&!Array.isArray(v)?Object.entries(flatten(v,key)):[[key,v]]}))}
function snapshot(records:Row[],until:string){return [...(records??[])].filter(r=>r.timestamp<=until).sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).reduce((s,r)=>({...s,...r}),{} as Row)}
function download(name:string,content:string,type='text/csv'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const csv=(rows:any[][])=>rows.map(row=>row.map(value=>{let s=String(value??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}).join(',')).join('\r\n');

function Panel({title,subtitle,children,wide=false}:{title:string;subtitle?:string;children:React.ReactNode;wide?:boolean}){return <section className={'panel lab-panel '+(wide?'span-all':'')}><div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><ExpandButton title={title}>{children}</ExpandButton></div>{children}</section>}
function Metric({title,value,note}:{title:string;value:string;note:string}){const expand=useExpand();return <button className="metric compact metric-interactive" onClick={()=>expand.metric(title,<><strong>{value}</strong><p>{note}</p></>)}><div className="metric-title">{title}</div><div className="big-number">{value}</div><div className="metric-foot">{note}</div></button>}
function Plot({rows,fields,height=260}:{rows:Row[];fields:{key:string;name:string;color?:string;bar?:boolean;dash?:boolean;axis?:boolean}[];height?:number}){return <div className="lab-chart" style={{height}}>{!rows.length?<p className="empty">No recorded values for this selection.</p>:<ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{top:15,right:25,left:0,bottom:0}}><CartesianGrid stroke="#e5e5e5" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="date" tick={{fill:'#777777',fontSize:11}} minTickGap={35}/><YAxis tick={{fill:'#777777',fontSize:11}} width={48}/>{fields.some(f=>f.axis)&&<YAxis yAxisId="right" orientation="right" tick={{fill:'#777777',fontSize:11}} width={40}/>}<Tooltip contentStyle={{background:'#ffffff',border:'1px solid #535353',borderRadius:8}} formatter={(v:any)=>typeof v==='number'?fmt(v,2):v}/>{fields.map((f,i)=>f.bar?<Bar key={f.key} dataKey={f.key} name={f.name} yAxisId={f.axis?'right':0} fill={f.color??colors[i%colors.length]} maxBarSize={24}/>:<Line key={f.key} dataKey={f.key} name={f.name} yAxisId={f.axis?'right':0} stroke={f.color??colors[i%colors.length]} dot={rows.length<14?{r:2}:false} strokeWidth={2} strokeDasharray={f.dash?'4 4':undefined} connectNulls={false}/>)}</ComposedChart></ResponsiveContainer>}</div>}
function Legend({items}:{items:string[]}){return <div className="legend">{items.map((s,i)=><span key={s}><i style={{background:colors[i%colors.length]}}/>{s}</span>)}</div>}
function Values({value,family="all"}:{value:Row;family?:string}){const rows=Object.entries(flatten(value));return <div className="table-wrap"><table className="value-table"><thead><tr><th>Metric</th><th>Value</th><th>Unit</th></tr></thead><tbody>{rows.map(([key,v])=><tr key={key}><td>{key.split('.').map(label).join(' / ')}</td><td>{Array.isArray(v)?v.map(x=>typeof x==='number'?fmt(x,3):JSON.stringify(x)).join(' · '):typeof v==='number'?fmt(v,3):v==null?'—':String(v)}</td><td>{key.startsWith('effort.')?'effort':/^(intensityDistribution|zonesDistribution)/.test(key)?'s':key.startsWith('altitude.')&&['ascent','descent','elevation','maxElevation','minElevation'].includes(key.split('.').pop()!)?'m':unit(key.split('.').pop()!,family)}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No recorded values available.</p>}</div>}

export function Analytics({data,setData,token,isDemo,tab,days,onSelect,syncing=false,embedded=false}:{embedded?:boolean;syncing?:boolean;data:AthleteData;setData:React.Dispatch<React.SetStateAction<AthleteData>>;token:string;isDemo:boolean;tab:string;days:number;onSelect:(a:Workout)=>void}){
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[sort,setSort]=useState('date'),[performance,setPerformance]=useState('pace'),[bodyMetric,setBodyMetric]=useState('weightInKilograms'),[zoneSport,setZoneSport]=useState('running'),[zoneMetric,setZoneMetric]=useState('heartrate'),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[page,setPage]=useState(1);
 const generation=useRef(0),stop=useRef(false);useEffect(()=>{generation.current++;stop.current=true;setBusy(false);setStatus('');setPage(1);return()=>{generation.current++;stop.current=true}},[token,isDemo]);
 useEffect(()=>{setPage(1)},[filter,search,days,sort]);
 const end=isDemo?new Date('2026-09-17T23:59:59Z'):new Date(),start=new Date(end);start.setUTCHours(0,0,0,0);start.setUTCDate(start.getUTCDate()-days+1);
 const extras=data.extra??{},sourceEnd=end.toISOString();
 const all=data.activities.filter(a=>new Date(a.date)>=start&&new Date(a.date)<=end),acts=all.filter(a=>filter==='all'||sport(a)===filter),sports=Array.from(new Set(data.activities.map(sport))).sort();
 useEffect(()=>{if(tab==='Performance lab'&&filter==='all')setFilter('running')},[tab]);
 useEffect(()=>{setPerformance(filter==='cycling'?'power':filter==='strength_training'?'duration':'pace')},[filter]);
 const analyzed=data.activities.filter(a=>a.analyzed&&a.evidence?.version===1).length;
 async function enrich(limit:number){if(busy||syncing||isDemo)return;const current=generation.current;stop.current=false;setBusy(true);const pending=data.activities.filter(a=>!a.analyzed||a.hrHistogram===undefined||a.evidence?.insightVersion!==2).slice(0,limit);let completed=0;try{for(let i=0;i<pending.length;i+=4){if(stop.current||current!==generation.current)break;const r=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action:'enrich',ids:pending.slice(i,i+4).map(a=>a.id)}),signal:AbortSignal.timeout(90000)});const result=await r.json() as Row;if(!r.ok)throw new Error(result.error||'Deep analysis could not be loaded.');if(current!==generation.current)break;setData(previous=>({...previous,activities:previous.activities.map(a=>{const d=result.details.find((v:Row)=>v.id===a.id);return d?{...a,nativeVersion:d.nativeVersion,analysisSource:d.analysisSource,summary:a.provider==='coros'?d.summary:{...a.summary,...d.summary},hrHistogram:d.hrHistogram,evidence:d.evidence,analyzed:true}:a})}));completed+=result.details.length;setStatus(`${completed} / ${pending.length} workouts analyzed in this pass`);await new Promise(resolve=>setTimeout(resolve,250))}}catch(e){if(current===generation.current)setStatus(e instanceof Error?e.message:'Analysis interrupted. Retry to continue.')}finally{if(current===generation.current)setBusy(false)}}

 const rows=useMemo(()=>{const last=isDemo?new Date('2026-09-17T23:59:59Z'):new Date(),first=new Date(last);first.setUTCHours(0,0,0,0);first.setUTCDate(first.getUTCDate()-364);const efforts=extras.efforts?.trainingEfforts;const series=Array.from({length:365},(_,i)=>{const d=new Date(first);d.setUTCDate(d.getUTCDate()+i);const iso=d.toISOString().slice(0,10),key=iso.replaceAll('-',''),daily=data.activities.filter(a=>a.date.slice(0,10)===iso&&(filter==='all'||sport(a)===filter));const raw=efforts?.[key];const effort=effortExcluded(data,iso)?null:efforts&&filter==='all'?(Array.isArray(raw)?raw.reduce((s:number,e:any)=>s+(num(Array.isArray(e)?e[0]:e)??0),0):daily.length||!data.historyComplete?null:0):null;return {iso,date:dateLabel(iso),effort,volume:daily.reduce((s,a)=>s+(num(a.summary?.duration)??0),0)/3600,sleep:num(data.sleep[key]?.[0])==null?null:data.sleep[key][0]/3600,sleepBaseline:num(data.sleep[key]?.[1])==null?null:data.sleep[key][1]/3600,hrv:num(data.hrv[key]?.[0]),hrvBaseline:num(data.hrv[key]?.[1])}});return series.map((r,i)=>({...r,short:i>=6?avg(series.slice(i-6,i+1).map(x=>x.effort)):null,long:i>=41?avg(series.slice(i-41,i+1).map(x=>x.effort)):null,volume7:i>=6?series.slice(i-6,i+1).reduce((s,x)=>s+x.volume,0):null})).slice(-days)},[data,days,filter,isDemo]);
 const effortRows=rows.filter(r=>r.effort!=null),latest=rows.at(-1),latestBody=snapshot(extras.bodyvalues?.bodyvalues??[],sourceEnd),capacities=extras.capacity?.capacity??{},zones=extras.zones?.zones??{},equipment=extras.equipmentList?.equipment??[],plans=extras.plannedTrainingList?._embedded?.plannedWorkoutList??[];
 const performanceRows=[...acts].reverse().filter(a=>num(a.summary?.[performance])!=null).map(a=>({date:dateLabel(a.date),value:a.summary![performance],sport:sportDescription(a)}));
 const bodyKeys=Array.from(new Set<string>((extras.bodyvalues?.bodyvalues??[]).flatMap((r:Row)=>Object.keys(r).filter(k=>!['timestamp','timezoneOffsetInSeconds'].includes(k)))));
 const bodyRows=(extras.bodyvalues?.bodyvalues??[]).filter((r:Row)=>num(r[bodyMetric])!=null&&new Date(r.timestamp)>=start).sort((a:Row,b:Row)=>a.timestamp.localeCompare(b.timestamp)).map((r:Row)=>({date:dateLabel(r.timestamp),value:r[bodyMetric]}));
 const filtered=acts.filter(a=>`${a.title??''} ${sportDescription(a)}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='date'?b.date.localeCompare(a.date):(num(b.summary?.[sort])??-1)-(num(a.summary?.[sort])??-1));
 const rankMetric=filter==='cycling'?'power':filter==='strength_training'?'duration':'vo2max';
 const ranked=acts.filter(a=>num(a.summary?.[rankMetric])!=null);
 const vo2=acts.filter(a=>num(a.summary?.vo2max)!=null);const sleepValues=rows.map(r=>r.sleep).filter((v):v is number=>v!=null),sleepAvg=avg(sleepValues),sleepSD=sleepAvg==null?null:Math.sqrt(sleepValues.reduce((s,v)=>s+(v-sleepAvg)**2,0)/sleepValues.length);
 const groups=sports.map(s=>{const group=acts.filter(a=>sport(a)===s);return {sport:s,count:group.length,hours:group.reduce((n,a)=>n+(num(a.summary?.duration)??0),0)/3600,distance:group.reduce((n,a)=>n+(num(a.summary?.distance)??0),0)/1000,calories:group.reduce((n,a)=>n+(num(a.summary?.calories)??0),0)}}).filter(g=>g.count);
 const zoneVersions=zones[zoneSport]?.[zoneMetric]??{};const zoneDate=Object.keys(zoneVersions).filter(d=>d<=sourceEnd).sort().at(-1);const zoneList=zoneDate?zoneVersions[zoneDate]:[];
 const distributions=['heartrate','power','pace','cadence'].map(key=>{let coverage=0;const totals=[0,0,0];acts.forEach(a=>{const d=a.summary?.intensityDistribution?.[key];if(d){coverage++;for(let i=0;i<3;i++)totals[i]+=num(d[i])??0}});return {key,coverage,totals,total:totals.reduce((a,b)=>a+b,0)}});
 return <>
 {tab==='Training log'&&<TrainingLog data={data} isDemo={isDemo} token={token} onSelect={onSelect}/>}
 {(!embedded||tab==='Data coverage')&&<details className="sync-details"><summary>More workout data <span>{isDemo?'Demo':`${analyzed} / ${data.activities.length} fully loaded`}{busy?' · loading…':''}</span></summary><section className="analysis-banner"><FlaskConical size={24}/><div><strong>Detailed workout data</strong><p>{isDemo?'Illustrative advanced metrics. Connect COROS to analyze your own sessions.':`${analyzed} / ${data.activities.length} workouts enriched · ${data.activities.length} summaries synced · extended training history`}</p>{status&&<small role="status">{status}</small>}</div>{!isDemo&&<div className="analysis-actions"><button className="lab-button" disabled={busy||syncing||analyzed===data.activities.length} onClick={()=>enrich(40)}>{busy?<RefreshCw size={15} className="spinning"/>:<FlaskConical size={15}/>}Load next 40</button>{busy?<button className="lab-button" onClick={()=>{stop.current=true;setStatus('Stopping after the current batch…')}}>Stop</button>:<button className="lab-button subtle" disabled={syncing||analyzed===data.activities.length} onClick={()=>enrich(data.activities.length)}>Load all workouts</button>}</div>}</section></details>}
 {tab==='Performance studio'&&<Studio data={data} isDemo={isDemo} onSelect={onSelect}/>}
 {tab==='Recovery lab'&&<SleepRegularity isDemo={isDemo} sleep={data.sleep} windows={data.extra?.coros?.sleepWindows}/>}
 {tab==='Training load'&&<ZoneTrends activities={all} onLoad={()=>enrich(data.activities.length)} loading={busy}/>}
 {tab==='Injury check'&&<InjuryCheck data={data} isDemo={isDemo}/>}
 {labTabs.includes(tab)&&!['Performance studio','Injury check','Training log'].includes(tab)&&<div className="laboratory"><div className="lab-toolbar"><span className="eyebrow">{tab}</span><label>Sport <select aria-label="Filter sport" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All sports</option>{sports.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><span className="muted">{acts.length} sessions in selected period · UTC dates</span></div>
 {tab==='Training load'&&<><div className="metrics"><Metric title="Training effort" value={effortRows.length?fmt(effortRows.reduce((s,r)=>s+(r.effort??0),0),0):'—'} note="Recorded load · all sports only"/><Metric title="7-day mean effort" value={fmt(latest?.short)} note="Daily effort, including rest days"/><Metric title="42-day mean effort" value={fmt(latest?.long)} note="Rolling mean, not CTL"/><Metric title="Load balance" value={latest?.short!=null&&latest.long!=null?fmt(latest.long-latest.short):'—'} note="42-day mean minus 7-day mean"/></div><div className="lab-grid"><Panel title="Workload over time" subtitle="Recorded activity load with transparent rolling averages" wide><Legend items={['Daily effort','7-day average','42-day average']}/><Plot rows={rows} fields={[{key:'effort',name:'Daily effort',bar:true},{key:'short',name:'7-day average'},{key:'long',name:'42-day average'}]}/><p className="lab-note">Load is summed from COROS activity loads. Missing workout loads remain unknown. These are rolling means, not a fitness prediction. Sport-specific effort is unavailable; select All sports.</p></Panel><Panel title="Intensity distribution" subtitle="Measured seconds across analyzed sessions; each sensor is independent">{distributions.map(d=><div className="intensity" key={d.key}><div><strong>{label(d.key)}</strong><small>{d.coverage} / {acts.length} sessions</small></div><div className="stack">{d.total?d.totals.map((v,i)=><span key={i} style={{width:`${v/d.total*100}%`,background:colors[i]}} title={`${['Low','Medium','High'][i]}: ${duration(v)}`}/>):<span className="no-intensity">No measured distribution</span>}</div><p>{d.total?d.totals.map((v,i)=>`${['Low','Medium','High'][i]} ${Math.round(v/d.total*100)}%`).join(' · '):'Run deep analysis to retrieve available distributions.'}</p></div>)}</Panel><Panel title="Weekly volume trend" subtitle="Trailing 7-day total · hours"><Plot rows={rows} fields={[{key:'volume7',name:'7-day hours'}]}/></Panel><Panel title="Sport allocation" subtitle="Strength retains its own category" wide><div className="table-wrap"><table><thead><tr><th>Discipline</th><th>Sessions</th><th>Time</th><th>Distance</th><th>Calories reported</th></tr></thead><tbody>{groups.map(g=><tr key={g.sport}><td>{label(g.sport)}</td><td>{g.count}</td><td>{duration(g.hours*3600)}</td><td>{fmt(g.distance)} km</td><td>{fmt(g.calories,0)} kcal</td></tr>)}</tbody></table></div></Panel></div></>}
 {tab==='Performance lab'&&<><DisciplinePanel activities={all} filter={filter} onFilter={setFilter} onSelect={onSelect}/><div className="lab-grid"><Panel title="Performance signals" subtitle="One observation per recorded session" wide><div className="lab-controls"><label>Metric <select value={performance} onChange={e=>setPerformance(e.target.value)}>{(filter==='cycling'?['power','powerMax','speed','heartrate','heartrateMax','cadence','trainingLoad']:filter==='strength_training'?['duration','heartrate','heartrateMax','calories']:['pace','power','heartrate','heartrateMax','cadence','groundContactTime','stepLength','verticalOscillation','verticalRatio','trainingLoad']).map(k=><option key={k} value={k}>{label(k)} {unit(k,filter)&&`(${unit(k,filter)})`}</option>)}</select></label><span>{performanceRows.length} observations · {filter==='all'?'filter by sport for comparable results':label(filter)}</span></div><Plot rows={performanceRows} fields={[{key:'value',name:`${label(performance)} ${unit(performance,filter)}`}]} /><p className="lab-note">Recorded COROS session metrics only. The current fitness VO₂ assessment and race predictions are on Home. Session averages and maxima are not power-duration or race records.</p></Panel><Panel title={filter==='cycling'?'Highest session power':filter==='strength_training'?'Longest strength sessions':'Longest recorded sessions'} subtitle={`${label(rankMetric)} · ${unit(rankMetric,filter)}`}><div className="rank-list">{[...ranked].sort((a,b)=>b.summary![rankMetric]-a.summary![rankMetric]).slice(0,8).map((a,i)=><button key={a.id} onClick={()=>onSelect(a)}><span className="rank">{String(i+1).padStart(2,'0')}</span><span>{a.title||sportDescription(a)}<small>{dateLabel(a.date)} · {sportDescription(a)}</small></span><strong>{fmt(a.summary![rankMetric])}</strong><ArrowUpRight size={15}/></button>)}{!ranked.length&&<p className="empty">No values for this discipline and metric. Analyze your workouts to load available data.</p>}</div></Panel><Panel title="Session benchmarks" subtitle="Best whole-session results within each discipline"><div className="rank-list">{groups.map(g=>{const entries=acts.filter(a=>sport(a)===g.sport),longest=[...entries].sort((a,b)=>(b.summary?.duration??0)-(a.summary?.duration??0))[0];return <button key={g.sport} onClick={()=>onSelect(longest)}><span><strong>{label(g.sport)}</strong><small>Longest session · {dateLabel(longest.date)}</small></span><strong>{duration(longest.summary?.duration)}</strong><ArrowUpRight size={15}/></button>})}</div></Panel></div></>}
 {tab==='Recovery lab'&&<><div className="metrics"><Metric title="Average sleep" value={sleepAvg==null?'—':duration(sleepAvg*3600)} note={`${sleepValues.length} / ${days} nights recorded`}/><Metric title="Sleep variability" value={sleepSD==null?'—':`${fmt(sleepSD*60,0)} min`} note="Standard deviation of recorded durations"/><Metric title="Average HRV" value={fmt(avg(rows.map(r=>r.hrv)))} note="Nightly RMSSD · ms"/><Metric title="Latest daily resting HR" value={fmt(latestBody.hrRestDynamic,0)} note="bpm · last known body-value measurement"/></div><div className="lab-grid"><Panel title="HRV and personal baseline" subtitle="Nightly RMSSD · milliseconds"><Legend items={['HRV','COROS baseline']}/><Plot rows={rows} fields={[{key:'hrv',name:'HRV (ms)'},{key:'hrvBaseline',name:'Baseline (ms)',dash:true}]}/></Panel><Panel title="Sleep duration" subtitle="Hours · missing nights remain gaps"><Plot rows={rows} fields={[{key:'sleep',name:'Sleep (h)',bar:true}]}/></Panel><Panel title="Recovery diary" subtitle="Deviations compare each night to the baseline supplied for that date" wide><div className="table-wrap"><table><thead><tr><th>Date</th><th>Sleep</th><th>Vs baseline</th><th>HRV</th><th>Vs baseline</th><th>Training</th></tr></thead><tbody>{[...rows].reverse().map(r=><tr key={r.iso}><td>{r.date}</td><td>{r.sleep==null?'—':duration(r.sleep*3600)}</td><td>{r.sleep!=null&&r.sleepBaseline!=null?`${fmt((r.sleep-r.sleepBaseline)*60,0)} min`:'—'}</td><td>{fmt(r.hrv)} ms</td><td>{r.hrv!=null&&r.hrvBaseline?`${fmt((r.hrv/r.hrvBaseline-1)*100)}%`:'—'}</td><td>{duration(r.volume*3600)}</td></tr>)}</tbody></table></div><p className="lab-note">Sleep stage proportions, sleep windows and scores are shown above when COROS supplies them. HRV and sleep describe trends; sieste does not infer an unsupported readiness score.</p></Panel></div></>}
 {tab==='Session explorer'&&<><div className="explorer-tools"><label className="search"><Search size={17}/><input aria-label="Search sessions" placeholder="Search sessions or discipline…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Sort sessions" value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Newest first</option>{['duration','distance','power','trainingLoad','heartrate'].map(k=><option key={k} value={k}>Highest {label(k)}</option>)}</select><button className="lab-button" onClick={()=>download('sieste-sessions.csv',csv([['Date','Sport','Title','Duration (s)','Distance (m)','Average HR (bpm)','Power (W)','COROS training load'],...filtered.map(a=>[a.date,sportDescription(a),a.title,a.summary?.duration,a.summary?.distance,a.summary?.heartrate,a.summary?.power,a.summary?.trainingLoad])]))}><Download size={15}/> Export selection</button></div><Panel title="Session explorer" subtitle={`${filtered.length} matching sessions · open a workout for its route map, stats and laps`} wide><div className="table-wrap"><table><thead><tr><th>Workout</th><th>Date</th><th>Duration</th><th>Distance</th><th>Avg HR</th><th>Avg power</th><th>kcal</th><th>Load</th><th>Analysis</th></tr></thead><tbody>{filtered.slice((page-1)*30,page*30).map(a=><tr key={a.id}><td><button className="session-name" onClick={()=>onSelect(a)}><span><strong>{a.title||sportDescription(a)}</strong><small>{sportDescription(a)}</small></span><ArrowUpRight size={14}/></button></td><td>{dateLabel(a.date)}</td><td>{duration(a.summary?.duration)}</td><td>{a.summary?.distance==null?'—':fmt(a.summary.distance/1000)+' km'}</td><td>{fmt(a.summary?.heartrate,0)}</td><td>{fmt(a.summary?.power,0)}</td><td>{fmt(a.summary?.calories,0)}</td><td>{fmt(a.summary?.trainingLoad)}</td><td><span className={'status-pill '+(a.analyzed?'success':'')}>{a.analyzed?'Enriched':'Summary'}</span></td></tr>)}</tbody></table>{!filtered.length&&<p className="empty">No sessions match your filters.</p>}</div><div className="pagination"><button className="lab-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page} / {Math.max(1,Math.ceil(filtered.length/30))}</span><button className="lab-button" disabled={page*30>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</button></div></Panel></>}
 {tab==='Athlete & zones'&&<div className="lab-grid">{data.provider==='coros'?<CorosBody data={data}/>:<ManualBody/>}<Panel title="Body measurements" subtitle="Actual observations; sparse updates are not interpolated" wide><div className="lab-controls"><select aria-label="Body measurement" value={bodyMetric} onChange={e=>setBodyMetric(e.target.value)}>{Array.from(new Set(['weightInKilograms','hrRestDynamic',...bodyKeys])).map(k=><option value={k} key={k}>{label(k)} ({unit(k)})</option>)}</select><span>{bodyRows.length} recorded observations</span></div><Plot rows={bodyRows} fields={[{key:'value',name:`${label(bodyMetric)} (${unit(bodyMetric)})`}]}/></Panel><Panel title="Latest known body values" subtitle="Sparse records merged field by field; each field retains its own date"><div className="table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>Last recorded</th></tr></thead><tbody>{bodyKeys.map(k=>{const records=(extras.bodyvalues?.bodyvalues??[]).filter((r:Row)=>r[k]!=null&&r.timestamp<=sourceEnd).sort((a:Row,b:Row)=>b.timestamp.localeCompare(a.timestamp));return <tr key={k}><td>{label(k)}</td><td>{fmt(latestBody[k])} {unit(k)}</td><td>{records[0]?dateLabel(records[0].timestamp):'—'}</td></tr>})}</tbody></table>{!bodyKeys.length&&<p className="empty">No body measurements returned.</p>}</div></Panel><Panel title="Thresholds & zones"><p className="lab-note">COROS threshold pace is in Fitness & race predictions on Home. Personal zone boundaries are not exposed by this connection. Activity zone tables use recorded zone time when supplied, otherwise explicitly labelled bpm bands.</p></Panel></div>}
 {tab==='Planning & gear'&&data.provider!=='coros'&&<div className="lab-grid"><Panel title="Training calendar" subtitle="Synced past year and next 90 days; upcoming workouts stay visible regardless of history range" wide><div className="table-wrap"><table><thead><tr><th>Date</th><th>Workout</th><th>Sport</th><th>Planned duration</th><th>Status</th></tr></thead><tbody>{[...plans].filter((p:Row)=>new Date(p.date)>=start&&(filter==='all'||sport(p)===filter)).sort((a:Row,b:Row)=>b.date.localeCompare(a.date)).map((p:Row)=><tr key={p.id}><td>{dateLabel(p.date)}</td><td>{p.title||'Planned workout'}{p.notes&&<details><summary>Coach notes</summary><p className="plan-notes">{p.notes}</p></details>}</td><td>{label(p.sportType||'misc')}</td><td>{duration(p.duration)}</td><td><span className="status-pill">{p.executedTrainingId?'Linked to completed workout':new Date(p.date)>end?'Upcoming':'No completed link'}</span></td></tr>)}</tbody></table>{!plans.length&&<p className="empty">No planned workouts were returned by COROS.</p>}</div></Panel><Panel title="Equipment inventory" subtitle="All equipment records and cumulative metrics from COROS" wide><div className="gear-grid">{equipment.map((item:Row,i:number)=><details className="gear-card" key={item.id??i}><summary><strong>{item.name||label(item.type||'Equipment')}</strong><span>{label(item.type||'misc')} · {item.count??'—'} sessions</span></summary><Values value={Object.fromEntries(Object.entries(item).filter(([k])=>!['trainingIds','id'].includes(k)))}/></details>)}{!equipment.length&&<p className="empty">No equipment records returned.</p>}</div><p className="lab-note">Equipment values are shown as returned by COROS. Distance fields use the API’s metric units; usage totals can include history outside the selected period.</p></Panel></div>}
 {tab==='Data coverage'&&data.provider==='coros'&&<CorosHub data={data}/>}
 {tab==='Data coverage'&&<div className="lab-grid">{data.warnings?.map(w=><p className="lab-note" key={w}>{w}</p>)}<Panel title="Connection observability" subtitle="See exactly what was returned and what still needs analysis" wide><div className="coverage-grid">{[['Activities',data.activities.length+' summaries'],['Deep metrics',analyzed+' enriched'],['Sleep',Object.keys(data.sleep).length+' nights'],['HRV',Object.keys(data.hrv).length+' nights'],...Object.entries(data.sources??{}).map(([k,v])=>[label(k),v.status==='synced'?'Synced':v.message||'Unavailable'])].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="lab-note">A successful source may legitimately contain no records. Summary sync progressively checks the available COROS history; detailed analysis is progressive and can be stopped or resumed. Your signed-in account keeps its encrypted connection and dashboard across refreshes. Disconnect COROS from account settings.</p></Panel><Panel title="Metric dictionary" subtitle="Definitions that matter"><div className="methods"><p><b>VO₂ max:</b> COROS’s current fitness assessment, shown with race predictions at the bottom of Home. It is not a per-activity metric. Never inferred from heart rate alone.</p><p><b>Training effort:</b> COROS activity training loads summed across sessions. Rolling averages use 7 and 42 calendar days, including today.</p><p><b>Intensity:</b> low, medium and high measured seconds, separated by heart rate, power, pace and cadence. Do not add sensors together.</p><p><b>Body values and thresholds:</b> sparse revisions. The latest value of each field carries forward until the next revision.</p><p><b>Coverage:</b> charts use only supplied values. Unsupported sensor metrics and missing physiological settings remain unavailable.</p><a className="docs-link" href="https://support.coros.com/" target="_blank" rel="noreferrer">COROS documentation ↗</a></div></Panel><Panel title="Your data, inspectable" subtitle="Export the current in-memory dataset"><div className="methods"><p>The export includes synced summaries, enriched metrics and all additional sources currently loaded. It never includes your token.</p><button className="lab-button" onClick={()=>download('sieste-athlete-data.json',JSON.stringify(data,null,2),'application/json')}><Download size={16}/> Download athlete data</button><details className="raw-inspector"><summary>Inspect source payloads</summary><pre>{JSON.stringify(extras,null,2)}</pre></details></div></Panel></div>}
 </div>}
 </>
}

export function WorkoutDetails({activity,cyclingContext,history=[],token,isDemo,onClose,onRemove,onClassify}:{onClassify?:(id:string,label:string|null)=>void;activity:Workout;cyclingContext?:any;history?:Workout[];token:string;isDemo:boolean;onClose:()=>void;onRemove:(activity:Workout)=>Promise<void>}){
 const [manualReference,setManualReference]=useState<any>(null);useEffect(()=>{if(isDemo)return;let active=true;const load=()=>fetch('/api/cycling-reference').then(r=>r.json()).then((d:any)=>{if(active)setManualReference(d.reference??null)}).catch(()=>{});void load();window.addEventListener('cycling-reference-changed',load);return()=>{active=false;window.removeEventListener('cycling-reference-changed',load)}},[isDemo]);
 const [removing,setRemoving]=useState(false),[removeError,setRemoveError]=useState('');
 async function removeWorkout(){setRemoving(true);setRemoveError('');try{await onRemove(activity)}catch(e){setRemoveError(e instanceof Error?e.message:'Could not remove workout.');setRemoving(false)}}
 const [detail,setDetail]=useState<Row|null>(()=>isDemo?null:cachedWorkout(token,activity.id)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('Summary'),[sensor,setSensor]=useState('heartrate'),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;const controller=new AbortController();setDetail(isDemo?null:cachedWorkout(token,activity.id));setError('');if(isDemo){const step=5,count=Math.floor((activity.summary?.duration??3600)/step),signal={...(['running','cycling'].includes(sport(activity))?{positionLat:Array.from({length:count},(_,i)=>48.86+.008*Math.cos(i/(count-1)*Math.PI*2)),positionLong:Array.from({length:count},(_,i)=>2.29+.012*Math.sin(i/(count-1)*Math.PI*2))}:{}),heartrate:Array.from({length:count},(_,i)=>Math.round(130+12*Math.sin(i/35)+(i%180>140?20:0))),...(activity.sportType==='cycling'?{power:Array.from({length:count},(_,i)=>Math.round(220+35*Math.sin(i/27)+(i%180>140?100:0)))}:{})};setDetail({...activity,demo:true,laps:Array.from({length:4},(_,i)=>({lap:i+1,duration:Math.floor(count*step/4),notes:'Illustrative demo lap'})),seriesSampled:{sampleSize:step,data:signal}});return}setBusy(!cachedWorkout(token,activity.id));loadWorkout(token,activity.id,'detail',attempt>0).then(d=>{if(active)setDetail(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false;controller.abort()}},[activity.id,token,isDemo,attempt]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=document.querySelector<HTMLElement>('.workout-modal');dialog?.querySelector<HTMLElement>('button')?.focus();const handle=(e:KeyboardEvent)=>{if(document.querySelector('.metric-expansion'))return;if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),select,input,textarea,summary,a[href]')??[]);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus()}}};document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);document.body.style.overflow=overflow;previous?.focus()}},[]);
 const summary=detail?.summary??activity.summary??{},series=detail?.seriesSampled?.data??{},keys=Object.keys(series).filter(k=>Array.isArray(series[k])&&series[k].some((n:any)=>num(n)!=null)),selected=keys.includes(sensor)?sensor:keys[0];
 const points=useMemo(()=>view==='Telemetry'?(series[selected]??[]).map((v:any,i:number)=>({date:`${fmt(i*(detail?.seriesSampled?.sampleSize??1)/60,1)}m`,value:num(v)})):[],[view,series[selected],detail?.seriesSampled?.sampleSize]);
 return <div className="overlay" onClick={onClose}><section className="modal workout-modal" role="dialog" aria-modal="true" aria-labelledby="workout-title" onClick={e=>e.stopPropagation()}><header className="activity-sheet-heading"><span className={`activity-sheet-icon sport-${sport(activity)}`}><SportIcon activity={activity}/></span><div><h2 id="workout-title">{activity.title||sportDescription(activity)}</h2><p>{sportDescription(activity)} · {new Date(activity.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'2-digit'})} · {new Date(activity.date).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p></div><button className="activity-sheet-close" aria-label="Close workout" onClick={onClose}><X size={19}/></button></header><div className="detail-tabs">{['Summary','Share',...(['running','cycling'].includes(sport(activity))?['Map']:[]),'Telemetry','Signal lab','Laps','Zones','Raw data'].map(t=><button className={view===t?'active':''} key={t} onClick={()=>setView(t)}>{t}</button>)}</div>{busy&&<LoadingState compact label="Loading metrics, laps & sensor streams…"/>}{error&&<div className="notice" role="alert">{error}<button className="lab-button" onClick={()=>setAttempt(a=>a+1)}>Retry</button></div>}
 {view==='Summary'&&<><ActivitySummary detail={{...activity,...detail,summary,cyclingContext:{...cyclingContext,manualReference}}} history={history} loading={busy} onClassify={label=>{setDetail(current=>current?{...current,sessionLabel:label}:current);onClassify?.(activity.id,label)}}/></>}
 {view==='Share'&&<Suspense fallback={<LoadingState compact label="Loading share designs…"/>}><ActivityShare key={activity.id} activity={{...activity,...detail,summary}} history={history} loading={busy}/></Suspense>}
 {view==='Map'&&<RouteMap detail={detail??activity} loading={busy}/>}
 {view==='Signal lab'&&<SignalLab detail={detail??activity}/>}
 {view==='Telemetry'&&<><div className="lab-controls"><select aria-label="Telemetry sensor" value={selected??''} onChange={e=>setSensor(e.target.value)}>{keys.map(k=><option key={k} value={k}>{label(k)} {unit(k,sport(activity))}</option>)}</select><span>{points.length} samples · {detail?.seriesSampled?.sampleSize??'—'}s resolution</span></div><section className="activity-telemetry"><header><h3>{label(selected??'Sensor')}</h3><ExpandButton title={label(selected??'Sensor')}><Plot rows={points} fields={[{key:'value',name:`${label(selected??'Sensor')} ${unit(selected??'',sport(activity))}`}]} height={440}/></ExpandButton></header><Plot rows={points} fields={[{key:'value',name:`${label(selected??'Sensor')} ${unit(selected??'',sport(activity))}`}]} height={170}/></section><p className="lab-note">Recorded sensor data. Time starts at the first sample; gaps remain gaps. {isDemo?'Illustrative demo samples.':'No synthetic streams are added.'}</p></>}
 {view==='Laps'&&<><ActivityLaps detail={detail??activity}/>{sport(activity)==='running'&&<details className="activity-advanced-laps"><summary>Compare work intervals · HR, cadence & step length</summary><RunReview detail={detail??activity} initialMode="Track intervals"/></details>}</>}
 {view==='Zones'&&<><ActivityZones summary={summary} loading={busy}/><p className="lab-note">Recorded COROS zone times when supplied; otherwise measured bpm bands. Zone numbers follow this workout’s distribution; current zone thresholds may differ. Percentages use classified time, which may be shorter than the activity.</p></>}
 {view==='Raw data'&&<><button className="lab-button" disabled={!detail} onClick={()=>download('sieste-workout.json',JSON.stringify(detail,null,2),'application/json')}><Download size={16}/> Export workout</button><pre className="raw-inspector">{JSON.stringify(detail??activity,null,2)}</pre></>}
 <div className="workout-remove"><button disabled={removing} onClick={removeWorkout}>{removing?'Removing…':'Remove workout from sieste'}</button><p>{isDemo?'Demo only · resets on refresh.':'Stays hidden after syncing. The original workout remains in COROS.'} You can undo after removal.</p><small>Daily load for this date becomes unavailable when the excluded session was part of its total.</small>{removeError&&<p role="alert">{removeError}</p>}</div>
 </section></div>
}
