"use client";
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,X,ArrowUp,Plus,Trash2} from 'lucide-react';
type Message={id:string;thread:string;message:string;answer?:string;status:string;created:number;model?:string};
export default function AthenaChat({selectedId,disabled=false}:{selectedId?:string;disabled?:boolean}){
 const [open,setOpen]=useState(false),[text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false),[state,setState]=useState<{online:boolean;model?:string;messages:Message[]}>({online:false,messages:[]}),[thread,setThread]=useState(''),[loaded,setLoaded]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLTextAreaElement>(null),launcher=useRef<HTMLButtonElement>(null),bottom=useRef<HTMLDivElement>(null),request=useRef<{text:string;id:string}|null>(null);
 async function refresh(signal?:AbortSignal){const r=await fetch('/api/athena',{cache:'no-store',signal});const b:any=await r.json();if(!r.ok)throw Error(b.error||'Chat unavailable');setState(b);setLoaded(true);setThread(t=>t||b.messages.at(-1)?.thread||crypto.randomUUID())}
 useEffect(()=>{if(!open||disabled)return;dialog.current?.showModal();input.current?.focus();const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{if(document.visibilityState==='visible')await refresh(controller.signal)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Connection unavailable')}finally{if(!controller.signal.aborted)timer=setTimeout(poll,4000)}};void poll();return()=>{controller.abort();clearTimeout(timer);dialog.current?.close();launcher.current?.focus()}},[open,disabled]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest'})},[state.messages.length,state.messages.at(-1)?.status,thread]);
 const pending=state.messages.some(m=>['queued','working'].includes(m.status));
 async function send(){if(!text.trim()||sending||pending)return;setSending(true);setError('');try{const key=request.current?.text===text?request.current.id:crypto.randomUUID();request.current={text,id:key};const r=await fetch('/api/athena',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text.trim(),thread,requestId:key,selectedId,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone})});const b:any=await r.json();if(!r.ok)throw Error(b.error||'Could not send');setText('');request.current=null;await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not send')}finally{setSending(false)}}
 async function clear(){setError('');try{const r=await fetch('/api/athena',{method:'DELETE'});if(!r.ok)throw Error('Could not clear chats');setThread(crypto.randomUUID());await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not clear chats')}}
 const threads=[...new Map(state.messages.map(m=>[m.thread,{label:m.message,date:m.created}])).entries()].reverse();
 const messages=state.messages.filter(m=>m.thread===thread);
 if(disabled)return null;
 return <><button ref={launcher} className="athena-launcher" aria-label="Chat with Athena" aria-haspopup="dialog" onClick={()=>setOpen(true)}><MessageCircle size={19}/><span>Athena</span></button>{open&&<dialog ref={dialog} className="athena-chat" aria-labelledby="athena-title" onCancel={()=>setOpen(false)}><header><div><strong id="athena-title">Athena</strong><small>{!loaded?'Connecting…':pending?'Thinking about your question…':state.online?'Available · '+(state.model||'Hermes'):'Offline · saved chats available'}</small></div><button aria-label="New conversation" title="New conversation" onClick={()=>{setThread(crypto.randomUUID());setText('');input.current?.focus()}}><Plus size={18}/></button><button aria-label="Close Athena" onClick={()=>setOpen(false)}><X size={20}/></button></header>
 {threads.length>0&&<div className="athena-history"><select aria-label="Conversation" value={thread} onChange={e=>setThread(e.target.value)}>{!threads.some(([id])=>id===thread)&&<option value={thread}>New conversation</option>}{threads.map(([id,g])=><option key={id} value={id}>{g.label.slice(0,55)}</option>)}</select><button title="Clear all chat history" aria-label="Clear all chat history" onClick={clear}><Trash2 size={15}/></button></div>}
 <div className="athena-messages" role="log" aria-live="polite">{messages.length===0&&<div className="athena-empty"><strong>What should we look at?</strong><p>Sleep, recovery and your last 28 days of training.{selectedId?' The open activity is included.':''}</p>{['How is my sleep affecting recovery?','Am I doing too much too soon?','Suggest my next workout'+(selectedId?' based on this session':'')].map(p=><button key={p} onClick={()=>{setText(p);input.current?.focus()}}>{p} ↗</button>)}</div>}{messages.map(m=><article key={m.id}><div className="athena-question">{m.message}</div><div className="athena-answer"><strong>Athena</strong><p>{m.answer||(m.status==='working'?'Analysing your saved data…':m.status==='failed'?'This request expired. Please try again.':'Waiting for Athena…')}</p></div></article>)}<div ref={bottom}/></div>
 <form onSubmit={e=>{e.preventDefault();void send()}}>{error&&<p className="athena-error" role="alert">{error}</p>}<div className="athena-compose"><textarea ref={input} aria-label="Message Athena" placeholder="Ask Athena…" rows={2} maxLength={2000} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><button type="submit" aria-label="Send message" disabled={!loaded||!state.online||pending||sending||!text.trim()}><ArrowUp size={20}/></button></div><small>Uses saved health & training summaries via your local Athena / Grok. No GPS. Saved in sieste for 7 days. Suggestions, not medical advice.</small></form></dialog>}</>;
}

