"use client";
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import AthenaAnswer from './athena-answer';
import {MessageCircle,Minus,ArrowUp,Plus,Trash2,History,Info} from 'lucide-react';
type Message={id:string;thread:string;message:string;answer?:string;status:string;created:number;model?:string};
export default function AthenaChat({selectedId,screen='Home',canChat=true}:{selectedId?:string;screen?:string;canChat?:boolean}){
 const [mounted,setMounted]=useState(false),[viewContext,setViewContext]=useState(screen);
 useEffect(()=>{setMounted(true);let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const labels=Array.from(document.querySelectorAll<HTMLElement>('[data-athena-screen]')).filter(e=>e.getClientRects().length>0).map(e=>e.dataset.athenaScreen).filter(Boolean);setViewContext([screen,...labels].join(' · ').slice(0,180))})};const observer=new MutationObserver(update);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['data-athena-screen']});update();return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[screen]);
 const [open,setOpen]=useState(false),[text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false),[state,setState]=useState<{online:boolean;model?:string;messages:Message[]}>({online:false,messages:[]}),[thread,setThread]=useState(''),[loaded,setLoaded]=useState(false),[compare,setCompare]=useState(false),[showHistory,setShowHistory]=useState(false),[showInfo,setShowInfo]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLTextAreaElement>(null),launcher=useRef<HTMLButtonElement>(null),bottom=useRef<HTMLDivElement>(null),request=useRef<{text:string;id:string}|null>(null);
 async function refresh(signal?:AbortSignal){const r=await fetch('/api/athena',{cache:'no-store',signal});const b:any=await r.json();if(!r.ok)throw Error(b.error||'Chat unavailable');setState(b);setLoaded(true);setThread(t=>t||b.messages.at(-1)?.thread||crypto.randomUUID())}
 useEffect(()=>{if(!open)return;dialog.current?.showModal();const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{if(canChat&&document.visibilityState==='visible')await refresh(controller.signal)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Connection unavailable')}finally{if(!controller.signal.aborted)timer=setTimeout(poll,4000)}};void poll();return()=>{controller.abort();clearTimeout(timer);dialog.current?.close();launcher.current?.focus()}},[open,canChat]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const articles=dialog.current?.querySelectorAll<HTMLElement>('.athena-messages article');articles?.[articles.length-1]?.scrollIntoView({block:'start'})});return()=>cancelAnimationFrame(frame)},[state.messages.length,state.messages.at(-1)?.status,thread]);
 useEffect(()=>{if(!open)return;const viewport=window.visualViewport;const resize=()=>{if(!viewport)return;dialog.current?.style.setProperty('--athena-height',Math.max(160,viewport.height-16)+'px');dialog.current?.style.setProperty('--athena-bottom',Math.max(8,window.innerHeight-viewport.height-viewport.offsetTop+8)+'px')};resize();viewport?.addEventListener('resize',resize);viewport?.addEventListener('scroll',resize);return()=>{viewport?.removeEventListener('resize',resize);viewport?.removeEventListener('scroll',resize)}},[open]);
 const pending=state.messages.some(m=>['queued','working'].includes(m.status));
 async function send(){if(!canChat||!text.trim()||sending||pending)return;setSending(true);setError('');try{const key=request.current?.text===text?request.current.id:crypto.randomUUID();request.current={text,id:key};const r=await fetch('/api/athena',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text.trim(),thread,requestId:key,selectedId,screen:viewContext,compare,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone})});const b:any=await r.json();if(!r.ok)throw Error(b.error||'Could not send');setText('');setCompare(false);request.current=null;await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not send')}finally{setSending(false)}}
 async function clear(){setError('');try{const r=await fetch('/api/athena',{method:'DELETE'});if(!r.ok)throw Error('Could not clear chats');setThread(crypto.randomUUID());await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not clear chats')}}
 const threads=[...new Map(state.messages.map(m=>[m.thread,{label:m.message,date:m.created}])).entries()].reverse();
 const messages=state.messages.filter(m=>m.thread===thread);
 if(!mounted)return null;
 return createPortal(<><button ref={launcher} className="athena-launcher" aria-label="Chat with Athena" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><MessageCircle size={19}/><span>Athena</span></button>{open&&<dialog ref={dialog} className="athena-chat" aria-labelledby="athena-title" onCancel={()=>setOpen(false)}><header><div><strong id="athena-title">Athena</strong><small>{!canChat?'Connect to chat':!loaded?'Connecting…':pending?'Thinking…':state.online?'Ready':'Offline'} · {viewContext}</small></div><button aria-label="Conversation history" aria-expanded={showHistory} onClick={()=>setShowHistory(v=>!v)}><History size={18}/></button><button aria-label="New conversation" title="New conversation" onClick={()=>{setThread(crypto.randomUUID());setText('');input.current?.focus()}}><Plus size={18}/></button><button aria-label="Minimize Athena" title="Minimize chat" onClick={()=>setOpen(false)}><Minus size={20}/></button></header>
 {!canChat&&<p className="athena-connect-note">Athena is available here. Sign in and connect your training data to send a question.</p>}
 {showHistory&&canChat&&threads.length>0&&<div className="athena-history"><select aria-label="Conversation" value={thread} onChange={e=>{setThread(e.target.value);setShowHistory(false)}}>{!threads.some(([id])=>id===thread)&&<option value={thread}>New conversation</option>}{threads.map(([id,g])=><option key={id} value={id}>{g.label.slice(0,55)}</option>)}</select><button title="Clear all chat history" aria-label="Clear all chat history" onClick={clear}><Trash2 size={15}/></button></div>}
 <div className="athena-messages" role="log" aria-live="polite">{messages.length===0&&<div className="athena-empty"><strong>What should we look at?</strong><p>Compact sleep, recovery and training context.{selectedId?' The open activity is included.':''}</p>{['How is my sleep affecting recovery?','Am I doing too much too soon?',selectedId?'Compare efficiency and cadence with similar sessions':'Suggest my next workout'].map(p=><button key={p} onClick={()=>{setText(p);input.current?.focus()}}>{p} ↗</button>)}</div>}{messages.map(m=><article key={m.id}><div className="athena-question">{m.message}</div><div className="athena-answer">{m.answer?<AthenaAnswer text={m.answer}/>:<p className="athena-waiting">{m.status==='working'?'Reviewing your training and recovery…':m.status==='failed'?'This request expired. Please try again.':'Waiting for Athena…'}</p>}</div></article>)}<div ref={bottom}/></div>
 <form onSubmit={e=>{e.preventDefault();void send()}}>{error&&<p className="athena-error" role="alert">{error}</p>}{selectedId&&<label className="athena-compare"><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/> Compare similar sessions for this question</label>}<div className="athena-compose"><textarea ref={input} aria-label="Message Athena" placeholder="Ask Athena…" rows={1} maxLength={2000} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><button type="submit" aria-label="Send message" disabled={!canChat||!loaded||!state.online||pending||sending||!text.trim()}><ArrowUp size={20}/></button></div><div className="athena-footer"><span>Only runs when you send</span><button type="button" aria-label="About Athena and your data" aria-expanded={showInfo} onClick={()=>setShowInfo(v=>!v)}><Info size={14}/></button></div>{showInfo&&<small className="athena-info">{state.model||'Hermes'} · Your saved summaries are sent to Athena / Grok. No GPS. Chat history stays in sieste for 7 days. Suggestions are not medical advice.</small>}</form></dialog>}</>,document.body);
}

