"use client";
import {useEffect,useRef,useState,type RefObject} from 'react';

import AthenaAnswer from './athena-answer';
import {MessageCircle,Minus,ArrowUp,ArrowUpRight,Plus,Trash2,History,Info} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {InputGroup,InputGroupTextarea,InputGroupAddon,InputGroupButton} from '@/components/ui/input-group';
import {Field,FieldGroup,FieldLabel,FieldError} from '@/components/ui/field';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription,EmptyContent} from '@/components/ui/empty';
import {MessageScrollerProvider,MessageScroller,MessageScrollerViewport,MessageScrollerContent,MessageScrollerItem,MessageScrollerButton} from '@/components/ui/message-scroller';
import {Message,MessageContent,MessageHeader} from '@/components/ui/message';
import {Bubble,BubbleContent} from '@/components/ui/bubble';
import {Marker,MarkerContent} from '@/components/ui/marker';
import type {AthenaChatProps} from './athena-chat';
type ChatTurn={id:string;thread:string;message:string;answer?:string;status:string;created:number;model?:string;scope?:string};
export default function AthenaChatPanel({selectedId,screen='Home',canChat=true,open,onMinimize,launcher}:AthenaChatProps&{open:boolean;onMinimize:()=>void;launcher:RefObject<HTMLButtonElement|null>}){
 const [viewContext,setViewContext]=useState(screen);
 useEffect(()=>{let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const labels=Array.from(document.querySelectorAll<HTMLElement>('[data-athena-screen]')).filter(e=>e.getClientRects().length>0).map(e=>e.dataset.athenaScreen).filter(Boolean);setViewContext((screen==='Activity'&&labels.some(s=>s?.startsWith('Activity /'))?labels:[screen,...labels]).join(' · ').slice(0,180))})};const observer=new MutationObserver(update);observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['data-athena-screen']});update();return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[screen]);
 const [text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false),[state,setState]=useState<{online:boolean;model?:string;messages:ChatTurn[]}>({online:false,messages:[]}),[thread,setThread]=useState(''),[loaded,setLoaded]=useState(false),[compare,setCompare]=useState(false),[showHistory,setShowHistory]=useState(false),[showInfo,setShowInfo]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLTextAreaElement>(null),request=useRef<{text:string;id:string}|null>(null);
 async function refresh(signal?:AbortSignal){const r=await fetch('/api/athena',{cache:'no-store',signal});const b:any=await r.json();if(!r.ok)throw Error(b.error||'Chat unavailable');setState(b);setLoaded(true);setThread(t=>t||b.messages.at(-1)?.thread||crypto.randomUUID())}
 useEffect(()=>{if(!open)return;dialog.current?.showModal();const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{if(canChat&&document.visibilityState==='visible')await refresh(controller.signal)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Connection unavailable')}finally{if(!controller.signal.aborted)timer=setTimeout(poll,4000)}};void poll();return()=>{controller.abort();clearTimeout(timer);dialog.current?.close();launcher.current?.focus()}},[open,canChat]);
 useEffect(()=>{if(!open)return;const viewport=window.visualViewport;const resize=()=>{if(!viewport)return;dialog.current?.style.setProperty('--athena-height',Math.max(160,viewport.height-16)+'px');dialog.current?.style.setProperty('--athena-bottom',Math.max(8,window.innerHeight-viewport.height-viewport.offsetTop+8)+'px')};resize();viewport?.addEventListener('resize',resize);viewport?.addEventListener('scroll',resize);return()=>{viewport?.removeEventListener('resize',resize);viewport?.removeEventListener('scroll',resize)}},[open]);
 const pending=state.messages.some(m=>['queued','working'].includes(m.status));
 async function send(){if(!canChat||!text.trim()||sending||pending)return;setSending(true);setError('');try{const key=request.current?.text===text?request.current.id:crypto.randomUUID();request.current={text,id:key};const r=await fetch('/api/athena',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text.trim(),thread,requestId:key,selectedId,screen:viewContext,compare,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone})});const b:any=await r.json();if(!r.ok)throw Error(b.error||'Could not send');setText('');setCompare(false);request.current=null;await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not send')}finally{setSending(false)}}
 async function clear(){setError('');try{const r=await fetch('/api/athena',{method:'DELETE'});if(!r.ok)throw Error('Could not clear chats');setThread(crypto.randomUUID());await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not clear chats')}}
 const threads=[...new Map(state.messages.map(m=>[m.thread,{label:m.message,date:m.created}])).entries()].reverse();
 const messages=state.messages.filter(m=>m.thread===thread);
 if(!open)return null;
 return <dialog ref={dialog} className="athena-chat" aria-labelledby="athena-title" onCancel={onMinimize}><header><div><strong id="athena-title">Athena</strong><small>{!canChat?'Connect to chat':!loaded?'Connecting…':pending?'Thinking…':state.online?'Ready':'Offline'} · {viewContext}</small></div><Button variant="ghost" size="icon-sm" aria-label="Conversation history" aria-expanded={showHistory} onClick={()=>setShowHistory(v=>!v)}><History data-icon="inline-start"/></Button><Button variant="ghost" size="icon-sm" aria-label="New conversation" title="New conversation" onClick={()=>{setThread(crypto.randomUUID());setText('');input.current?.focus()}}><Plus data-icon="inline-start"/></Button><Button variant="ghost" size="icon-sm" aria-label="Minimize Athena" title="Minimize chat" onClick={onMinimize}><Minus data-icon="inline-start"/></Button></header>
 {!canChat&&<p className="athena-connect-note">Athena is available here. Sign in and connect your training data to send a question.</p>}
 {showHistory&&canChat&&threads.length>0&&<div className="athena-history"><Field orientation="horizontal"><FieldLabel htmlFor="athena-conversation" className="sr-only">Conversation</FieldLabel><NativeSelect id="athena-conversation" size="sm" className="min-w-0 flex-1" value={thread} onChange={e=>{setThread(e.target.value);setShowHistory(false)}}>{!threads.some(([id])=>id===thread)&&<NativeSelectOption value={thread}>New conversation</NativeSelectOption>}{threads.map(([id,g])=><NativeSelectOption key={id} value={id}>{g.label.slice(0,55)}</NativeSelectOption>)}</NativeSelect></Field><Button variant="ghost" size="icon-sm" title="Clear all chat history" aria-label="Clear all chat history" onClick={clear}><Trash2 data-icon="inline-start"/></Button></div>}
 <MessageScrollerProvider key={thread} autoScroll defaultScrollPosition="last-anchor"><MessageScroller className="athena-messages"><MessageScrollerViewport className="athena-message-viewport" aria-label="Conversation with Athena"><MessageScrollerContent className="athena-message-content" aria-live="polite">{messages.length===0&&<MessageScrollerItem messageId="athena-welcome"><Empty className="athena-empty"><EmptyHeader><EmptyMedia variant="icon"><MessageCircle/></EmptyMedia><EmptyTitle>What should we look at?</EmptyTitle><EmptyDescription>Compact sleep, recovery and training context.{selectedId?' The open activity is included.':''}</EmptyDescription></EmptyHeader><EmptyContent className="athena-suggestions">{['How is my sleep affecting recovery?','Am I doing too much too soon?',selectedId?'Compare efficiency and cadence with similar sessions':'Suggest my next workout'].map(p=><Button variant="outline" key={p} className="w-full justify-between" onClick={()=>{setText(p);input.current?.focus()}}>{p}<ArrowUpRight data-icon="inline-end"/></Button>)}</EmptyContent></Empty></MessageScrollerItem>}{messages.map(m=><MessageScrollerItem key={m.id} messageId={m.id} scrollAnchor className="athena-turn"><Message align="end"><MessageContent><Bubble variant="tinted" align="end"><BubbleContent className="athena-question">{m.message}</BubbleContent></Bubble></MessageContent></Message><Marker className="athena-turn-scope"><MarkerContent>{m.scope?'About: '+m.scope:'Earlier question · screen context not saved'}</MarkerContent></Marker><Message align="start"><MessageContent><MessageHeader>Athena</MessageHeader><Bubble variant="ghost"><BubbleContent className="athena-answer">{m.answer?<AthenaAnswer text={m.answer}/>:<p className="athena-waiting" role="status">{m.status==='working'?'Reviewing your training and recovery…':m.status==='failed'?'This request expired. Please try again.':'Waiting for Athena…'}</p>}</BubbleContent></Bubble></MessageContent></Message></MessageScrollerItem>)}</MessageScrollerContent></MessageScrollerViewport><MessageScrollerButton aria-label="Jump to latest message"/></MessageScroller></MessageScrollerProvider>
 <form onSubmit={e=>{e.preventDefault();void send()}}><FieldGroup className="athena-fields gap-2">{error&&<FieldError className="athena-error">{error}</FieldError>}{selectedId&&<Field orientation="horizontal" className="athena-compare"><Checkbox id="athena-compare-sessions" checked={compare} onCheckedChange={value=>setCompare(value===true)}/><FieldLabel htmlFor="athena-compare-sessions">Compare similar sessions for this question</FieldLabel></Field>}<Field><FieldLabel htmlFor="athena-message" className="sr-only">Message Athena</FieldLabel><InputGroup className="athena-compose"><InputGroupTextarea id="athena-message" ref={input} placeholder="Ask Athena…" rows={1} maxLength={2000} className="min-h-8" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><InputGroupAddon align="block-end" className="justify-end"><InputGroupButton variant="default" size="icon-sm" type="submit" aria-label="Send message" disabled={!canChat||!loaded||!state.online||pending||sending||!text.trim()}><ArrowUp data-icon="inline-start"/></InputGroupButton></InputGroupAddon></InputGroup></Field></FieldGroup><div className="athena-footer"><span>Only runs when you send</span><Button variant="ghost" size="icon-xs" type="button" aria-label="About Athena and your data" aria-expanded={showInfo} onClick={()=>setShowInfo(v=>!v)}><Info data-icon="inline-start"/></Button></div>{showInfo&&<small className="athena-info">{state.model||'Hermes'} · Your saved summaries are sent to Athena / Grok. No GPS. Chat history stays in sieste for 7 days. Suggestions are not medical advice.</small>}</form></dialog>;
}

