"use client";
import {weeklyVerdict} from './weekly-verdict-data';
import {sportFamily} from './sports';
import type {AthleteData,Workout} from './analytics';
import {latestRunningSignals,newRecordedBests,mechanicsHistory} from './session-intelligence-data';
import {sleepTrainingPattern} from './training-coach-data';
import {efficiencyInsight} from './training-insights-data';
import {RunningEvidence} from './session-intelligence';
import {useExpand} from './expansion';
import {paceLabel} from './activity-metrics';
const day=(v:string)=>new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short'});
export default function CoachAdditions({data,now,family,onSelect}:{data:AthleteData;now:Date;family:'running'|'cycling';onSelect:(a:Workout)=>void}){
 const verdict=weeklyVerdict(data,now,family),latestRide=[...data.activities].filter(a=>sportFamily(a)==='cycling'&&new Date(a.date)<=now).sort((a,b)=>b.date.localeCompare(a.date))[0],expand=useExpand(),latest=latestRunningSignals(data.activities,now),signals=latest?.evidence?.insights,bests=newRecordedBests(data.activities,now,family),efficiency=efficiencyInsight(data,now,family),sleep=sleepTrainingPattern(data,now),drift=signals?.drift,mechanics=latest?mechanicsHistory(latest,data.activities):[];
 const open=(a:Workout)=>{expand.close();onSelect(a)},value=(v:number)=>family==='running'?`${paceLabel(1000/v)} /km`:`${Math.round(v)} W`;
 const showBests=()=>expand.widget('New recorded bests · last 7 days',<div className="coach-evidence"><p>Compared with all earlier processed {family} sessions in your synced history. {bests.analyzed}/{bests.total} sessions processed. {data.historyStart?`History starts ${day(data.historyStart)}.`:''} These are best recorded sampled efforts, not certified race records or a complete lifetime history.</p>{bests.records.length?<div className="coach-table-scroll"><table><thead><tr><th>Effort</th><th>New best</th><th>Previous best</th><th>Change</th></tr></thead><tbody>{bests.records.map(r=><tr key={r.seconds+r.activity.id}><th>{r.seconds/60} min</th><td><button className="coach-session" onClick={()=>open(r.activity)}>{value(r.value)} · {day(r.activity.date)} ↗</button></td><td><button className="coach-session" onClick={()=>open(r.previous.activity)}>{value(r.previous.value)} · {day(r.previous.activity.date)} ↗</button></td><td className="trend-good">↑ {r.change.toFixed(1)}% {family==='running'?'speed':'power'}</td></tr>)}</tbody></table></div>:<p>No new best with a previous benchmark in the last 7 days. A first reading establishes a baseline.</p>}</div>);
 const showRunning=(title:string)=>{if(signals&&latest)expand.widget(title,<><RunningEvidence signals={signals}/><h3>Compared with earlier runs</h3><p>Up to 5 runs from the prior 56 days, same sport subtype and matched pace/gradient. Device, shoes, weather and fatigue may differ; direction alone is not a technique score.</p>{mechanics.length?<div className="coach-table-scroll"><table><thead><tr><th>Earlier run</th><th>Matched</th><th>Change now vs then</th></tr></thead><tbody>{mechanics.map(r=><tr key={r.activity.id}><td><button className="coach-session" onClick={()=>open(r.activity)}>{day(r.activity.date)} ↗</button></td><td>{r.minutes} min</td><td>{r.metrics.map(m=><small key={m.key}>{m.key.replace(/([A-Z])/g," $1")} {m.change>0?"↑":m.change<0?"↓":"→"} {Math.abs(m.change).toFixed(1)}%</small>)}</td></tr>)}</tbody></table></div>:<p>No earlier run with enough matched sensor readings yet.</p>}<button className="coach-session" onClick={()=>open(latest)}>Open {day(latest.date)} run ↗</button></>);else expand.widget(title,<p>Open a run or analyse older sessions to process the required pace, gradient and sensor data.</p>)};
 const cutoff=new Date(now);cutoff.setDate(cutoff.getDate()-7);
 const week=data.activities.filter(a=>new Date(a.date)>=cutoff&&new Date(a.date)<=now),unprocessed=week.filter(a=>a.evidence?.insightVersion!==2).length;
 const improved=bests.records.length?`${bests.records.length} new recorded best${bests.records.length===1?'':'s'}`:efficiency.change!==null&&efficiency.change>0?`Matched ${family==='running'?'speed':'power'} +${efficiency.change.toFixed(1)}% (28 days)`:'No improvement confirmed';
 const attention=sleep.short?`${sleep.short} short night${sleep.short===1?'':'s'} in last 3 days`:efficiency.change!==null&&efficiency.change<0?`Matched ${family==='running'?'speed':'power'} ${efficiency.change.toFixed(1)}% (28 days)`:'No review signal in these checks';
 const verdictText=[verdict.volumeChange===null?'Volume comparison incomplete':`${family==='running'?'Run':'Ride'} volume ${verdict.volumeChange>=0?'↑':'↓'}${Math.abs(verdict.volumeChange).toFixed(0)}%`,efficiency.change===null?'efficiency building':`matched output ${efficiency.change>=0?'↑':'↓'}${Math.abs(efficiency.change).toFixed(1)}% (28d)`,verdict.sleepChange===null?'sleep comparison incomplete':`sleep ${verdict.sleepChange>=0?'↑':'↓'}${Math.round(Math.abs(verdict.sleepChange))}m/night`].join(' · ');
 const review=()=>expand.widget('Weekly review · evidence',<div className="coach-evidence"><h3>{verdictText}</h3><p>Last 7 completed days ({verdict.current.from} → {verdict.current.to}) versus the previous 7. Volume needs complete history. Sleep uses {verdict.current.nights}/7 versus {verdict.prior.nights}/7 nights, at least 4 per period. Efficiency uses 28 versus the preceding 56 days, not a weekly comparison.</p><h3>{improved}</h3><p>{bests.records.length?'New bests compare the latest seven days with all earlier processed efforts.':efficiency.title}</p><button className="coach-session" onClick={showBests}>See recorded bests ↗</button><h3>{attention}</h3><p>{sleep.title}. Short-night checks use the latest 3 days. Efficiency uses 28 versus the preceding 56 days, with {efficiency.pairs.length} matched pairs; it is not a week-over-week fitness verdict.</p><h3>Coverage</h3><p>{week.length-unprocessed}/{week.length} sessions in the rolling last seven days have the new analysis. {sleep.coverage}/3 recent nights recorded. Missing or unprocessed readings cannot establish improvement or recovery.</p>{week.map(a=><button className="coach-session" key={a.id} onClick={()=>open(a)}>{day(a.date)} · {a.title??a.sportType} ↗</button>)}</div>);
 return <><div className="coach-grid coach-additions">{family==='cycling'&&<button className="coach-tile" disabled={!latestRide} onClick={()=>latestRide&&open(latestRide)}><span>Ride durability ↗</span><strong>{latestRide?'HR at matched watts':'No ride recorded'}</strong><small>{latestRide?day(latestRide.date)+' · open Deep analysis':'Needs timed power and HR'}</small></button>}{family==='running'&&<><button className="coach-tile" onClick={()=>showRunning('Latest run · mechanics')}><span>Running mechanics ↗</span><strong>{signals?.mechanics.length?`${signals.mechanics.length} comparable measures`:'Building reference'}</strong><small>{latest?`${day(latest.date)} · early versus late`:'Needs a processed run'}</small></button><button className="coach-tile" onClick={()=>showRunning('Latest run · durability')}><span>Steady-run durability ↗</span><strong className={drift==null?'trend-missing':drift>10?'trend-bad':drift>5?'trend-watch':'trend-neutral'}>{drift==null?'Insufficient steady data':`${drift>0?'↑':'↓'} ${Math.abs(drift).toFixed(1)}% HR cost`}</strong><small>{latest?`${day(latest.date)} · matched pace & gradient`:'After warm-up · stops excluded'}</small></button></>}<button className="coach-tile" onClick={showBests}><span>New recorded bests ↗</span><strong className={bests.records.length?'trend-good':'trend-neutral'}>{bests.records.length?`${bests.records.length} in the last 7 days`:'No new benchmark'}</strong><small>1 / 5 / 20 / 60 min · {bests.analyzed}/{bests.total} processed</small></button></div><button className="coach-weekly" onClick={review}><b>Weekly verdict ↗</b><span>{verdictText}</span><span><i className={improved==='No improvement confirmed'?'neutral':'good'}/>{improved}</span><span><i className={sleep.short||efficiency.change!==null&&efficiency.change<0?'watch':'neutral'}/>{attention}</span><span><i className="neutral"/>{unprocessed?`${unprocessed} sessions need analysis`:`${week.length} sessions processed`} · tap for evidence</span></button></>;
}
