// COROS MCP currently returns labelled text for summaries/health and JSON for laps.
// These parsers accept the observed, unit-bearing fields only; unknown formats fail closed.
import {sportFamily} from './sports';
export function corosText(value:any):string{if(typeof value==='string')return value;if(typeof value?.text==='string')return value.text;throw new Error('COROS returned a data format sieste cannot yet read. Your saved dashboard is unchanged.')}
const number=(s:string|undefined)=>s===undefined?undefined:Number(s.replaceAll(',',''));
const val=(s:string,re:RegExp)=>number(s.match(re)?.[1]);
export function seconds(s:string|undefined){if(!s)return undefined;if(/^\d+(?::\d{1,2}){1,2}(?:\.\d+)?$/.test(s.trim()))return s.trim().split(':').reduce((a,v)=>a*60+Number(v),0);const h=val(s,/(\d+(?:\.\d+)?)h/),m=val(s,/(\d+(?:\.\d+)?)\s*min/);return h===undefined&&m===undefined?undefined:(h??0)*3600+(m??0)*60}
export function corosSport(code:number){if(code>=100&&code<=103)return {sportType:'running',subSportType:code===101?'indoor_running':code===102?'trail_running':code===103?'track_running':undefined};if(code===104||code===105)return {sportType:'hiking'};if(code>=200&&code<=299)return {sportType:'cycling',subSportType:code===201?'indoor_cycling':code===202||code===205?'e_biking':undefined};if(code===402||code===9901)return {sportType:'misc',subSportType:'strength_training'};if(code===900)return {sportType:'walking'};if(code===300||code===301)return {sportType:'swimming'};return {sportType:'misc'}}
export function corosRecords(value:any){const text=corosText(value);const count=val(text,/\((\d+) records?\)/);if(count===undefined){if(/no (?:sport |workout |activity )?records/i.test(text))return [];throw new Error('COROS workout list format was not recognized. Your history was preserved.')}
 const blocks=text.split(/\n(?=\d+\. )/).slice(1);if(blocks.length!==count)throw new Error('COROS returned an incomplete workout list.');return blocks.map(block=>{const id=block.match(/LabelId: ([\w-]+)/)?.[1],code=val(block,/SportType: (\d+)/),start=val(block,/startTimestamp=(\d+)/),end=val(block,/endTimestamp=(\d+)/);if(!id||code===undefined||!start)throw new Error('A COROS workout is missing its ID or start time.');const summary:any={};const fields={duration:seconds(block.match(/Duration: ([\d:.]+)/)?.[1]),distance:val(block,/Distance: ([\d,.]+) km/),heartrate:val(block,/Avg HR: ([\d.]+) bpm/),calories:val(block,/Calories: ([\d,.]+) kcal/),sets:val(block,/Sets: (\d+)/),pace:seconds(block.match(/Average Pace: ([\d:]+) \/km/)?.[1])};for(const [k,v] of Object.entries(fields))if(v!==undefined&&Number.isFinite(v))summary[k]=k==='distance'?v*1000:v;const speed=val(block,/Average Speed: ([\d.]+) km\/h/);if(speed!==undefined)summary.speed=speed/3.6;if(end&&end>=start)summary.durationTotal=end-start;return {id:`coros_${code}_${id}`,provider:'coros',localDay:block.match(/— (\d{4}-\d\d-\d\d)/)?.[1],coros:{labelId:id,sportType:code},date:new Date(start*1000).toISOString(),...corosSport(code),title:block.match(/Location: ([^\n]+)/)?.[1]?.trim()||block.match(/^\d+\. (.+?) —/)?.[1],summary}})
}
export function corosSummary(value:any){const text=corosText(value),s:any={};const fields:any={duration:seconds(text.match(/Workout Time: ([\d:.]+)/)?.[1]),durationTotal:seconds(text.match(/Total Time: ([\d:.]+)/)?.[1]),distance:val(text,/Distance: ([\d,.]+) km/),pace:seconds(text.match(/Average Pace: ([\d:]+) \/km/)?.[1]),heartrate:val(text,/Average Heart Rate: ([\d.]+) bpm/),cadence:val(text,/Average Cadence: ([\d.]+) (?:spm|rpm)/),stepLength:val(text,/Average Stride Length: ([\d.]+) m/),power:val(text,/Average Power: ([\d.]+) W/),calories:val(text,/Calories: ([\d,.]+) kcal/),trainingLoad:val(text,/Training Load: ([\d.]+)/),aerobicTrainingEffect:val(text,/Aerobic TE: ([\d.]+)/),anaerobicTrainingEffect:val(text,/Anaerobic TE: ([\d.]+)/)};for(const [k,v] of Object.entries(fields))if(typeof v==='number'&&Number.isFinite(v))s[k]=k==='distance'?v*1000:k==='stepLength'?v*100:v;const altitude=text.match(/Elevation Gain \/ Loss: ([\d,.]+) m \/ ([\d,.]+) m/);if(altitude)s.altitude={ascent:number(altitude[1]),descent:number(altitude[2])};return s}
export function corosSleep(value:any){const text=corosText(value);if(/^No .*sleep.*data/i.test(text))return {sleep:{},windows:{}};if(!text.startsWith('Sleep Data'))throw new Error('COROS sleep format was not recognized.');const sleep:Record<string,number[]>={},windows:Record<string,any>={};for(const block of text.split(/\n(?=\d{4}-\d\d-\d\d\n)/).slice(1)){const date=block.slice(0,10).replaceAll('-',''),duration=seconds(block.match(/Main Sleep: ([^\n]+)/)?.[1]);if(duration!==undefined&&duration>0)sleep[date]=[duration];const window=block.match(/Main Sleep Window: (\d{4}-\d\d-\d\d \d\d:\d\d) - (\d{4}-\d\d-\d\d \d\d:\d\d)/);windows[date]={bedtime:window?.[1],wakeTime:window?.[2],score:val(block,/Sleep Score: ([\d.]+)/),awakeMinutes:val(block,/Awake Time: ([\d.]+) min/),deepPercent:val(block,/Deep Sleep Ratio: ([\d.]+)%/),lightPercent:val(block,/Light Sleep Ratio: ([\d.]+)%/),remPercent:val(block,/REM Ratio: ([\d.]+)%/),napMinutes:val(block,/Naps Total: ([\d.]+) min/),source:'COROS',dateBasis:'wake-up day'};}return {sleep,windows}}
export function corosHrv(value:any){const text=corosText(value),assessment=text.split('Sleep HRV Time Series')[0],hrv:Record<string,number[]>={};for(const m of assessment.matchAll(/(\d{4}-\d\d-\d\d):\s*\n\s*HRV Avg: ([\d.]+) ms[^\n]*\n\s*Normal Range: ([\d.]+) - ([\d.]+) ms\s*\n\s*Baseline: ([\d.]+) ms/g))hrv[m[1].replaceAll('-','')]=[+m[2],+m[5],+m[3],+m[4]];if(!/HRV Assessment|no .*data/i.test(text))throw new Error('COROS HRV format was not recognized.');return hrv}
export function corosResting(value:any){return [...corosText(value).matchAll(/(\d{4}-\d\d-\d\d): ([\d.]+) bpm/g)].map(m=>({timestamp:m[1]+'T00:00:00Z',hrRestDynamic:+m[2],source:'COROS'}))}
export function corosDaily(value:any){const text=corosText(value);return Object.fromEntries(text.split(/\n(?=--- \d{8} ---)/).slice(1).map(block=>{const key=block.match(/--- (\d{8}) ---/)![1];return [key,{steps:val(block,/Steps: ([\d,]+)/),calories:val(block,/Calories: ([\d,]+) kcal/),source:'COROS'}]}))}
export function corosLoad(value:any){return corosText(value).split(/\n(?=\d{4}-\d\d-\d\d\n)/).slice(1).map(b=>({date:b.slice(0,10),short:val(b,/Short-Term Load: ([\d.]+)/),long:val(b,/Long-Term Load: ([\d.]+)/),ratio:val(b,/Load Ratio: ([\d.]+)/),comment:b.match(/Comment: ([^\n]+)/)?.[1]}))}
export function corosFitness(value:any){const t=corosText(value);return {ftp:val(t,/(?:^|\n)(?:Cycling )?(?:FTP|Functional Threshold Power):\s*([\d.]+)\s*(?:W|watts)\b/i),vo2max:val(t,/VO2max: ([\d.]+)/),thresholdPace:seconds(t.match(/Threshold Pace: ([\d:]+)/)?.[1]),runningLevel:val(t,/Running Level: ([\d.]+)/)}}
export function corosRecovery(value:any){const t=corosText(value);return {percent:val(t,/Recovery: ([\d.]+)%/),label:t.match(/Level: ([^\n]+)/)?.[1]}}
export function mergeCorosActivities(primary:any[],archive:any[]){const used=new Set<string>();const activities=primary.map(a=>{const candidates=archive.filter(b=>!used.has(b.id)&&sportFamily(a)===sportFamily(b)&&Math.abs(Date.parse(a.date)-Date.parse(b.date))<=120000&&Math.abs((a.summary?.duration??0)-(b.summary?.duration??0))<=Math.max(60,(a.summary?.duration??0)*.1));const match=candidates.length===1?candidates[0]:null;if(match)used.add(match.id);const fallbackKeys=match?Object.keys(match.summary??{}).filter(k=>a.summary[k]===undefined):[];return {...a,...(match?{fallbackId:match.id,fallbackSummaryFields:fallbackKeys,hrHistogram:match.hrHistogram,evidence:match.evidence,analyzed:match.analyzed,analysisSource:match.evidence?"Saved Tredict":undefined}:{}),summary:{...match?.summary,...a.summary},sessionLabel:match?.sessionLabel??a.sessionLabel}});return [...activities,...archive.filter(a=>!used.has(a.id)).map(a=>({...a,provider:'tredict'}))].sort((a,b)=>b.date.localeCompare(a.date))}
export function corosLaps(value:any){const groups=value?.lapGroups;if(!Array.isArray(groups))return [];const group=groups.find((g:any)=>g.type===1&&g.laps?.length)||groups.find((g:any)=>g.type===2&&g.laps?.length)||groups.find((g:any)=>g.type!==-1&&g.laps?.length);return (group?.laps??[]).map((l:any)=>({lap:l.lapIndex,duration:l.time,durationTotal:l.time,distance:typeof l.distance==='number'?l.distance/100:undefined,heartrate:l.avgHr>0?l.avgHr:undefined,heartrateMax:l.maxHr>0?l.maxHr:undefined,cadence:l.avgCadence>0?l.avgCadence:undefined,power:l.avgPower>0?l.avgPower:undefined,stepLength:l.avgStrideLength>0?l.avgStrideLength:undefined,altitude:{ascent:l.elevGain,descent:l.totalDescent},source:'COROS'}))}
