'use client';
import {localDate} from './week-overview';
import RecordedIndicator from './recorded-indicator';
import DailyRing from './daily-ring';
import WidgetSpark from './widget-spark';
import type {AthleteData} from './analytics';
import {useExpand} from './expansion';
import {CorosSleepWindows} from './coros-recovery';
const finite=(n:any):n is number=>typeof n==='number'&&Number.isFinite(n);
function MiniLine({values,label,score=false,dates=[],color='#507fbc'}:{values:(number|null)[];label:string;score?:boolean;dates?:string[];color?:string}){return <WidgetSpark mode="bars" color={color} className="coros-mini-line" values={values} label={label} domain={score?[0,100]:undefined} negativeBelow={score?60:undefined} amberBelow={score?80:undefined} positiveFrom={score?80:undefined} pointLabels={values.map((v,i)=>`${stamp(dates[i]??'')}: ${v??'No reading'}${score?' /100 · sieste colours: 80+ green, 60–79 amber, below 60 red':''}`)}/>}
const stamp=(d:string)=>`${d.slice(6,8)}/${d.slice(4,6)}`;
export default function CorosDaily({data,now=new Date()}:{data:AthleteData;now?:Date}){const expand=useExpand(),c=data.extra?.coros;if(!c)return null;const dates=Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(d.getDate()-6+i);return localDate(d).replaceAll('-','')});const nights=dates.map(d=>[d,c.sleepWindows?.[d]??{}]) as [string,any][],night=nights.filter(([,v])=>finite(v.score)).at(-1),days=dates.map(d=>[d,c.daily?.[d]??{}]) as [string,any][];
 function daily(key:'steps'|'calories',label:string){const recorded=days.filter(([,v])=>finite(v[key])),last=recorded.at(-1),prior=recorded.slice(0,-1),reference=prior.length>=3?prior.reduce((sum,[,v])=>sum+v[key],0)/prior.length:null;return <button onClick={()=>expand.widget(label,<><p>COROS recorded daily totals; these are not live readings. The ring compares the latest total with the average of the preceding available days (at least three); it is not a prescribed target. More calories is not automatically better.{key==='calories'?' The source does not separate active and resting calories here; this is not a calculated total daily energy expenditure.':''}</p><table className="coros-daily-table"><tbody>{days.map(([d,v])=><tr key={d}><th>{stamp(d)}</th><td>{finite(v[key])?v[key].toLocaleString('en-GB'):'—'} {key==='calories'?'kcal':'steps'}</td></tr>)}</tbody></table></>)}><small>{label}</small><div className="daily-ring-row"><strong>{last?.[1][key]?.toLocaleString('en-GB')??'—'}{key==='calories'&&<em>kcal</em>}</strong><DailyRing value={last?.[1][key]??null} reference={reference} label="vs avg"/></div><MiniLine color={key==='steps'?'#367db3':'#9460ba'} dates={dates} values={days.map(([,v])=>finite(v[key])?v[key]:null)} label={`${label}, last seven calendar days`}/><RecordedIndicator readings={Object.entries(c.daily??{}).map(([date,v]:any)=>({date,value:v[key]}))} completeDays/><span>{last?stamp(last[0])+' · recorded':'No reading'}</span></button>}
 return <section className="coros-daily-strip daily-mini-tiles" aria-label="Daily sleep score, steps and calories"><button onClick={()=>expand.widget('Sleep score & timing',<><MiniLine dates={dates} values={nights.map(([,v])=>finite(v.score)?v.score:null)} score label="Sleep scores, last seven calendar nights"/><CorosSleepWindows windows={c.sleepWindows??{}}/></>)}><small>Sleep score</small><div className="daily-ring-row"><strong>{night?.[1].score??'—'}<em>/100</em></strong><DailyRing value={night?.[1].score??null} reference={100} label="of 100"/></div><MiniLine dates={dates} values={nights.map(([,v])=>finite(v.score)?v.score:null)} score label="Sleep scores, last seven calendar nights, scale 0 to 100"/><RecordedIndicator readings={Object.entries(c.sleepWindows??{}).map(([date,v]:any)=>({date,value:v.score}))} direction="higher"/><span>{night?stamp(night[0])+' · 7-night trend':'No reading'}</span></button>{daily('steps','Daily steps')}{daily('calories','Daily calories')}</section>;
}
