'use client';
import RecordedIndicator from './recorded-indicator';
import DailyRing from './daily-ring';
import WidgetSpark from './widget-spark';
import type {AthleteData} from './analytics';
import {useExpand} from './expansion';
import {CorosSleepWindows} from './coros-recovery';
const finite=(n:any):n is number=>typeof n==='number'&&Number.isFinite(n);
function MiniLine({values,label,score=false}:{values:(number|null)[];label:string;score?:boolean}){return <WidgetSpark className="coros-mini-line" values={values} label={label} domain={score?[0,100]:undefined}/>}
const stamp=(d:string)=>`${d.slice(6,8)}/${d.slice(4,6)}`;
export default function CorosDaily({data}:{data:AthleteData}){const expand=useExpand(),c=data.extra?.coros;if(!c)return null;const nights=Object.entries(c.sleepWindows??{}).sort(([a],[b])=>a.localeCompare(b)).filter(([,v]:any)=>finite(v.score)).slice(-7) as [string,any][],night=nights.at(-1),days=Object.entries(c.daily??{}).sort(([a],[b])=>a.localeCompare(b)).slice(-7) as [string,any][];
 function daily(key:'steps'|'calories',label:string){const recorded=days.filter(([,v])=>finite(v[key])),last=recorded.at(-1),prior=recorded.slice(0,-1),reference=prior.length>=3?prior.reduce((sum,[,v])=>sum+v[key],0)/prior.length:null;return <button onClick={()=>expand.widget(label,<><p>COROS recorded daily totals; these are not live readings. The ring compares the latest total with the average of the preceding available days (at least three); it is not a prescribed target. More calories is not automatically better.{key==='calories'?' The source does not separate active and resting calories here; this is not a calculated total daily energy expenditure.':''}</p><table className="coros-daily-table"><tbody>{days.map(([d,v])=><tr key={d}><th>{stamp(d)}</th><td>{finite(v[key])?v[key].toLocaleString('en-GB'):'—'} {key==='calories'?'kcal':'steps'}</td></tr>)}</tbody></table></>)}><small>{label}</small><div className="daily-ring-row"><strong>{last?.[1][key]?.toLocaleString('en-GB')??'—'}{key==='calories'&&<em>kcal</em>}</strong><DailyRing value={last?.[1][key]??null} reference={reference} label="vs avg"/></div><MiniLine values={days.map(([,v])=>finite(v[key])?v[key]:null)} label={`${label}, last seven recorded days`}/><RecordedIndicator readings={Object.entries(c.daily??{}).map(([date,v]:any)=>({date,value:v[key]}))} completeDays/><span>{last?stamp(last[0])+' · recorded':'No reading'}</span></button>}
 return <section className="coros-daily-strip" aria-label="Daily sleep score, steps and calories"><button onClick={()=>expand.widget('Sleep score & timing',<><MiniLine values={nights.map(([,v])=>v.score)} score label="Sleep scores, last seven recorded nights"/><CorosSleepWindows windows={c.sleepWindows??{}}/></>)}><small>Sleep score</small><div className="daily-ring-row"><strong>{night?.[1].score??'—'}<em>/100</em></strong><DailyRing value={night?.[1].score??null} reference={100} label="of 100"/></div><MiniLine values={nights.map(([,v])=>v.score)} score label="Sleep scores, last seven recorded nights, scale 0 to 100"/><RecordedIndicator readings={Object.entries(c.sleepWindows??{}).map(([date,v]:any)=>({date,value:v.score}))} direction="higher"/><span>{night?stamp(night[0])+' · 7-night trend':'No reading'}</span></button>{daily('steps','Daily steps')}{daily('calories','Daily calories')}</section>;
}
