'use client';
import RecordedIndicator from './recorded-indicator';
import WidgetSpark from './widget-spark';
import type {AthleteData} from './analytics';
import {useExpand} from './expansion';
import {COROS_LIBRARY,publicCorosText} from './coros-extended-data';
import {durationLabel,paceLabel} from './activity-metrics';
function Spark({values}:{values:number[]}){return <WidgetSpark className="coros-hub-spark" values={values} label="Recorded trend"/>}
export function CorosBody({data}:{data:AthleteData}){const p=data.extra?.coros?.profile;return <section className="panel coros-hub"><h3>Body measurements · COROS</h3><div className="coros-readings"><div><small>Weight</small><strong>{p?.weight??'—'} <em>kg</em></strong></div><div><small>Height</small><strong>{p?.height??'—'} <em>cm</em></strong></div></div><p className="lab-note">Synced from your COROS profile. These are current profile values, not historical weigh-ins.</p></section>}
export default function CorosHub({data,compact=false}:{data:AthleteData;compact?:boolean}){const expand=useExpand(),c=data.extra?.coros;if(!c)return null;const days=Object.entries(c.daily??{}).sort(([a],[b])=>a.localeCompare(b)).slice(-7) as [string,any][],last=days.at(-1);const heart=Object.entries(c.heartDays??{}).sort(([a],[b])=>a.localeCompare(b)).slice(-7) as [string,any][];const latest=(rows:[string,any][],k:string)=>rows.at(-1)?.[1]?.[k]??'—';const dateLabel=(date?:string)=>date?`${date.slice(6,8)}/${date.slice(4,6)}`:'No reading';const native=data.activities.filter(a=>a.provider==='coros'),loaded=native.filter(a=>a.analysisSource==='COROS FIT').length;
 return <section className="panel coros-hub"><header><h3>COROS data</h3><span>Only live source</span></header><div className="coros-hub-grid">
 <button onClick={()=>expand.widget('Daily heart rate',<>{heart.map(([d,v])=><p key={d}>{dateLabel(d)} · average {v.average} bpm · {v.min??'—'}–{v.max??'—'} bpm</p>)}</>)}><small>Daily HR · {dateLabel(heart.at(-1)?.[0])}</small><strong>{latest(heart,'average')} <em>bpm</em></strong><Spark values={heart.map(([,v])=>v.average)}/><RecordedIndicator readings={heart.map(([date,v])=>({date,value:v.average}))} completeDays/></button>
 <button onClick={()=>expand.widget('COROS body measurements',<CorosBody data={data}/>)}><small>Weight / height</small><strong>{c.profile?.weight??'—'} <em>kg</em></strong><span>{c.profile?.height??'—'} cm · COROS profile</span></button>
 </div><details><summary>Import coverage · {loaded}/{native.length} workout files</summary><p>{native.length} COROS workout summaries · {loaded} detailed files cached. {c.history?.complete?'Workout list checked back to 2000.':'Older workout summaries importing.'} {c.recoveryHistory?.complete?'Recovery backfill reached your earliest imported workout.':`Older recovery importing${c.recoveryHistory?.from?' · reached '+c.recoveryHistory.from:''}.`}</p><p>Details import while sieste is open. COROS permits 50 file downloads a day; automatic imports use up to 45, reserving five for activities you open. Cached files do not need another download.</p><p>Zone boundaries, shoe mileage and historical VO₂ estimates are not exposed by the connected COROS tools. Activity heart-rate tables show measured bpm bands when zones are unavailable. Missing values stay unavailable.</p><div className="coros-source-list">{Object.entries(COROS_LIBRARY).map(([key,label])=>{const status=c.library?.[key]??data.sources?.[key];return <div key={key}><span>{label}</span><small>{status?.status==='synced'?'Imported':status?.status==='empty'?'No records':status?.status==='saved'?'Saved · refresh pending':status?.status??'Pending'}</small>{status?.retrievedAt&&<a href={'/api/coros/data?source='+key} target="_blank" rel="noreferrer">Data ↗</a>}</div>})}</div><h4>Latest wellness check</h4><pre className="coros-source-text">{c.wellness?.text?publicCorosText(c.wellness.text):'No imported wellness check.'}</pre></details></section>
}
