import {corosText,seconds} from './coros-data';
const n=(t:string,re:RegExp)=>{const s=t.match(re)?.[1];return s===undefined?undefined:Number(s.replaceAll(',',''))};
export function corosProfile(v:any){const t=corosText(v);if(!/User Profile Information/.test(t))throw new Error('Profile format unavailable');return {height:n(t,/Height: ([\d.]+) cm/),weight:n(t,/Weight: ([\d.]+) kg/),nickname:t.match(/Nickname: ([^\n]+)/)?.[1],source:'COROS'}}
export function corosHeartDays(v:any){return Object.fromEntries([...corosText(v).matchAll(/(\d{4}-\d\d-\d\d): ([\d.]+) bpm(?: \(Min: ([\d.]+), Max: ([\d.]+)\))?/g)].map(m=>[m[1].replaceAll('-',''),{average:+m[2],min:m[3]?+m[3]:undefined,max:m[4]?+m[4]:undefined}]))}
export function corosStressDays(v:any){return Object.fromEntries([...corosText(v).matchAll(/(\d{4}-\d\d-\d\d):\s*\nAverage Stress: ([\d.]+)(?: \(([^)]+)\))?/g)].map(m=>[m[1].replaceAll('-',''),{value:+m[2],label:m[3]}]))}
export function corosDevices(v:any){const t=corosText(v);if(!/Bound Devices|no .*devices/i.test(t))throw new Error('Devices format unavailable');return [...t.matchAll(/(?:^|\n)\d+\. ([^\n]+)\n\s*Bluetooth ID: [^\n]*\n\s*Model Name: ([^\n]+)/g)].map(m=>({name:m[1],model:m[2]}))}
export function corosPredictions(v:any){const t=corosText(v);return Object.fromEntries(['5 km','10 km','Half Marathon','Marathon'].map(k=>[k,seconds(t.match(new RegExp('^\\s*'+k+' Prediction:\\s*([\\d:]+)\\s*$', 'mi'))?.[1])]).filter(([,v])=>v!==undefined))}
export function corosStressPoints(v:any){return [...corosText(v).matchAll(/timestamp=(\d+), timezone=(-?[\d.]+), stress=([\d.]+), score=([\d.]+), stressHrv=([\d.]+), stressHr=([\d.]+)/g)].map(m=>({timestamp:+m[1],timezone:+m[2],stress:+m[3],score:+m[4],hrv:+m[5]>0?+m[5]:null,heartRate:+m[6]>0?+m[6]:null}))}
export function publicCorosText(v:any){return corosText(v).replace(/^.*(?:Plan ID|idInPlan|Bluetooth ID|Serial Number):.*$/gm,'').replace(/\n{3,}/g,'\n\n')}
export const COROS_LIBRARY:Record<string,string>={queryUserInfo:'Body measurements',queryAvgHeartRate:'Daily heart rate',queryHealthCheckTimeSeries:'Wellness check',querySleepData:'Sleep & timings',querySleepHrv:'Sleep HRV',queryRestingHeartRate:'Resting heart rate',queryDailyHealthData:'Daily health',queryFitnessAssessmentOverview:'Fitness & race predictions',queryTrainingLoadAssessment:'Training load',queryRecoveryStatus:'Recovery'};

// Old unanchored matching could read Half Marathon as Marathon. Repair only from stored source text.
export function repairRacePredictions(data:any,cached:any){const c=data.extra?.coros;if(!c)return data;const history={...c.fitnessHistory};for(const [day,v] of Object.entries(history) as [string,any][]){if(v?.predictionVersion!==2){const predictions={...v?.predictions};delete predictions.Marathon;history[day]={...v,predictions,predictionVersion:2}}}let fitness=c.fitness;if(fitness&&fitness.predictionVersion!==2){const predictions={...fitness.predictions};delete predictions.Marathon;fitness={...fitness,predictions,predictionVersion:2};if(cached?.data&&cached?.retrievedAt){const parsed=corosPredictions(cached.data);fitness={...fitness,predictions:parsed,observedAt:cached.retrievedAt};const key=cached.retrievedAt.slice(0,10).replaceAll('-','');if(history[key])history[key]={...history[key],predictions:parsed,predictionVersion:2}}}return {...data,extra:{...data.extra,coros:{...c,fitness,fitnessHistory:history}}};}
