const valid=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:null;
export function cyclingAnalysis(detail:any,start=0,end=Infinity){
 const s=detail.seriesSampled?.data??{},step=detail.seriesSampled?.sampleSize;
 const empty={rows:[] as any[],power:null as number|null,hr:null as number|null,cadence:null as number|null,work:null as number|null,coasting:null as number|null,coverage:0,bests:[] as {seconds:number;watts:number|null;at:number|null}[],matched:[] as any[],drift:null as number|null,reason:'Timed power, HR and cadence samples are needed.',seconds:0};
 if(!valid(step)||step<=0||step>30)return empty;
 const n=Math.max(...['power','heartrate','cadence'].map(k=>s[k]?.length??0)),limit=valid(detail.summary?.durationTotal)?detail.summary.durationTotal:n*step;
 const rows=Array.from({length:n},(_,i)=>({t:i*step,time:i*step/60,power:valid(s.power?.[i])&&s.power[i]>=0?s.power[i]:null,hr:valid(s.heartrate?.[i])&&s.heartrate[i]>0?s.heartrate[i]:null,cadence:valid(s.cadence?.[i])&&s.cadence[i]>=0?s.cadence[i]:null,speed:valid(s.speed?.[i])?s.speed[i]:null})).filter(r=>r.t>=start&&r.t<Math.min(end,limit));
 const powers=rows.map(r=>r.power).filter(valid),hrs=rows.map(r=>r.hr).filter(valid),cadences=rows.filter(r=>r.cadence!==null&&r.cadence>0).map(r=>r.cadence).filter(valid),moving=rows.filter(r=>r.speed!==null&&r.speed>1&&r.power!==null),coverage=rows.length?powers.length/rows.length:0;
 const bests=[30,60,300,1200].map(seconds=>{const count=Math.ceil(seconds/step);if(seconds%step!==0)return {seconds,watts:null,at:null};let total=0,gaps=0,best=-Infinity,at:number|null=null;for(let i=0;i<rows.length;i++){const v=rows[i].power;if(v===null)gaps++;else total+=v;if(i>=count){const old=rows[i-count].power;if(old===null)gaps--;else total-=old}if(i>=count-1&&gaps===0&&total/count>best){best=total/count;at=rows[i-count+1].t}}return {seconds,watts:valid(best)?best:null,at}});
 // Match full stable 60-second blocks in 25 W bands, after warm-up and before cooldown.
 const blocks:any[]=[];for(let t=Math.max(start,600);t+60<=Math.min(end,limit-180);t+=60){const part=rows.filter(r=>r.t>=t&&r.t<t+60);if(part.length*step<60||part.some(r=>r.power===null||r.power<=0||r.hr===null))continue;const p=avg(part.map(r=>r.power).filter(valid))!,h=avg(part.map(r=>r.hr).filter(valid))!,cv=Math.sqrt(part.reduce((sum,r)=>sum+(r.power!-p)**2,0)/part.length)/p;if(cv>.12)continue;blocks.push({t,p,h,c:avg(part.map(r=>r.cadence).filter((v):v is number=>valid(v)&&v>0)),band:Math.floor(p/25)*25})}
 const midpoint=(Math.max(start,600)+Math.min(end,limit-180))/2,matched:any[]=[];
 for(const band of [...new Set(blocks.map(b=>b.band))]){const early=blocks.filter(b=>b.band===band&&b.t+60<=midpoint),late=blocks.filter(b=>b.band===band&&b.t>=midpoint);if(early.length<3||late.length<3)continue;const ep=avg(early.map(b=>b.p))!,lp=avg(late.map(b=>b.p))!;if(Math.abs(lp/ep-1)>.05)continue;const eh=avg(early.map(b=>b.h))!,lh=avg(late.map(b=>b.h))!;matched.push({band,earlyPower:ep,latePower:lp,earlyHR:eh,lateHR:lh,earlyCadence:avg(early.map(b=>b.c).filter(valid)),lateCadence:avg(late.map(b=>b.c).filter(valid)),minutes:Math.min(early.length,late.length),change:(lh/eh-1)*100})}
 const minutes=matched.reduce((a,b)=>a+b.minutes,0),drift=minutes>=5?matched.reduce((a,b)=>a+b.change*b.minutes,0)/minutes:null;
 return {rows,power:avg(powers),hr:avg(hrs),cadence:avg(cadences),work:powers.length?powers.reduce((a,b)=>a+b,0)*step/1000:null,coasting:moving.length?moving.filter(r=>r.power===0).length/moving.length*100:null,coverage,bests,matched,drift,reason:drift===null?'Need ≥5 matched minutes per half, with stable power within 5%.':null,seconds:rows.length*step};
}
