"use client";
import {useState} from 'react';
import {Moon,Activity,Heart,Star,Footprints,Flame,ChevronLeft,ChevronRight} from 'lucide-react';
import type {AthleteData} from './analytics';
import {weekOverview,localDate} from './week-overview';
import {sportFamily} from './sports';
import {metricStatus} from './metric-status';
import {useExpand} from './expansion';
import CorosDaily from './coros-daily';
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const palette={green:'#21845b',lightgreen:'#5b987d',yellow:'#ab9231',orange:'#b87c24',red:'#ca485f',neutral:'#8793a5'};
const metrics=[{key:'sleep',label:'Sleep',unit:'duration',title:'Latest sleep',Icon:Moon,color:'#8673ed'},{key:'hrv',label:'HRV',unit:'ms',title:'Average HRV',Icon:Activity,color:'#25b985'},{key:'rhr',label:'Resting HR',unit:'bpm',title:'Resting HR',Icon:Heart,color:'#f16b88'},{key:'score',label:'Sleep score',unit:'/100',title:'Sleep score',Icon:Star,color:'#a294f5'},{key:'steps',label:'Steps',unit:'steps',title:'Daily steps',Icon:Footprints,color:'#65a6fa'},{key:'calories',label:'Calories',unit:'kcal',title:'Daily calories',Icon:Flame,color:'#f4ae6a'}];
const format=(key:string,v:number|null,compact=false)=>v===null?'—':key==='sleep'?`${Math.floor(Math.round(v*60)/60)}h${String(Math.round(v*60)%60).padStart(2,'0')}`:compact&&v>=10000?`${(v/1000).toFixed(1)}k`:v.toLocaleString('en-GB',{maximumFractionDigits:0});
export default function DailyThreeDays({data,now}:{data:AthleteData;now:Date}){
 const [offset,setOffset]=useState(0),expand=useExpand(),end=new Date(now);end.setDate(end.getDate()-offset*3);
 const days=weekOverview(data,end,sportFamily).rows.slice(-3),coros=data.extra?.coros,today=localDate(now);
 const value=(key:string,day:typeof days[number]):number|null=>{const stamp=day.iso.replaceAll('-',''),v=key==='score'?coros?.sleepWindows?.[stamp]?.score:key==='steps'||key==='calories'?coros?.daily?.[stamp]?.[key]:day[key as 'sleep'|'hrv'|'rhr'];return finite(v)?v:null};
 return <section className="health-week" aria-label="Daily health and activity"><header><div><h2>Daily Health & Activity</h2><p>{new Date(days[0].iso+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'})} – {end.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</p></div><nav aria-label="Health history"><button aria-label="Previous three days" onClick={()=>setOffset(v=>v+1)}><ChevronLeft size={14}/></button><button aria-label="Next three days" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-1))}><ChevronRight size={14}/></button><button className="health-current" onClick={()=>setOffset(0)}>{offset?'Latest':'Last 3 days'}</button></nav></header>
 <div className="health-date-row"><span/><div>{days.map(day=><span className={day.iso===today?'health-today':''} key={day.iso}><small>{new Date(day.iso+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short'})}</small>{day.iso.slice(-2)}</span>)}</div><span/></div>
 {metrics.map(metric=>{const values=days.map(d=>value(metric.key,d)),last=values[2],prior=values[1],physiology=['sleep','hrv','rhr'].includes(metric.key),status=last!==null&&physiology?metricStatus(metric.key,data,end,sportFamily):null,partial=offset===0&&['steps','calories'].includes(metric.key),diff=last!==null&&prior!==null?last-prior:null,delta=partial?'Today · partial':diff===null?'No comparison':diff===0?'→ unchanged':`${diff>0?'↑':'↓'} ${metric.key==='sleep'?Math.round(Math.abs(diff)*60)+'m':Math.abs(diff).toLocaleString('en-GB',{maximumFractionDigits:1})} vs prior day`,insight=last===null?'Not available':status?.label??(partial?'Day in progress':'Recorded total'),known=values.filter(finite),bars=!physiology,min=bars?0:Math.min(...known),max=bars&&metric.key==='score'?100:Math.max(...known),spread=Math.max(max-min,metric.key==='sleep'?2:metric.key==='rhr'?8:metric.key==='hrv'?20:1),middle=(min+max)/2,y=(v:number)=>bars?29-v/Math.max(1,max)*24:17-(v-middle)/spread*22,x=(i:number)=>i*100+50;
 let connected=false;const path=values.map((v,i)=>{if(v===null){connected=false;return ''}const cmd=connected?'L':'M';connected=true;return `${cmd}${x(i)},${y(v)}`}).join(' ');
 const open=()=>physiology?expand.metric(metric.title):expand.widget(metric.title,<CorosDaily data={data} now={end}/>);
 return <button key={metric.key} className="health-metric-row" onClick={open} style={{'--metric-color':metric.color} as React.CSSProperties} aria-label={`${metric.label}: ${format(metric.key,last)} ${metric.unit}. ${insight}. Open analysis`}><span className="health-summary"><span className="health-icon"><metric.Icon size={16}/></span><span className="health-name">{metric.label}<small>{metric.unit}</small></span><span className="health-latest"><strong>{format(metric.key,last)}</strong><small style={{color:status?palette[status.tone]:undefined}}>{delta}</small></span></span><span className="health-series"><svg viewBox="0 0 300 34" preserveAspectRatio="none" role="img" aria-label={`${metric.label}, three-day trend; missing readings are gaps`}>{!bars&&<path d={path} fill="none" stroke={metric.color} strokeWidth="1.2" strokeOpacity=".7"/>}{values.map((v,i)=>v===null?null:bars?<rect key={i} x={x(i)-15} y={y(v)} width="30" height={Math.max(1,29-y(v))} rx="2" fill={metric.color} opacity={i===2?'.95':'.65'}><title>{days[i].iso}: {v} {metric.unit}</title></rect>:<circle key={i} cx={x(i)} cy={y(v)} r={i===2?3.6:2.5} fill={metric.color}><title>{days[i].iso}: {format(metric.key,v)} {metric.unit}</title></circle>)}</svg><span className="health-series-values">{values.map((v,i)=><span key={days[i].iso} className={days[i].iso===today?'health-today':''} title={`${days[i].iso}: ${format(metric.key,v)} ${metric.unit}`}>{format(metric.key,v,true)}</span>)}</span></span><span className="health-insight" style={{color:status?palette[status.tone]:undefined}}><b>{insight}</b><small>{status?.rangeLabel?`Usual ${status.rangeLabel}`:partial?'Totals so far':metric.key==='score'?'COROS sleep score':'Tap for analysis'}</small></span></button>})}
 <p className="health-footnote">Tap a row for analysis · steps & calories are recorded totals, not live</p></section>;
}
