const valid=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
export function dailyRingMetrics(data:any,now:Date,dayKey:(d:Date)=>string){
 const days=Array.from({length:29},(_,i)=>{const d=new Date(now);d.setDate(d.getDate()-i);const date=dayKey(d),sessions=data.activities.filter((a:any)=>dayKey(new Date(a.date))===date&&new Date(a.date)<=now),source=data.extra?.efforts?.trainingEfforts,raw=source?.[date.replaceAll('-','')];
 const effort=Array.isArray(raw)?raw.map((e:any)=>Array.isArray(e)?e[0]:e):[];
 const total=(key:string,scale=1)=>{const values=sessions.map((a:any)=>a.summary?.[key]).filter(valid);return {value:values.length?values.reduce((a:number,b:number)=>a+b,0)/scale:sessions.length?null:0,partial:values.length<sessions.length}};
 return {date,active:sessions.length>0,steps:total('steps'),minutes:total('duration',60),effort:{value:source?(effort.length&&effort.every(valid)?effort.reduce((a:number,b:number)=>a+b,0):sessions.length?null:0):null,partial:effort.some((v:any)=>!valid(v))}};
 });
 return [{key:'effort',label:'Daily exertion',unit:'effort',description:'Sum of Tredict training-effort values for today. This is Tredict’s metric, not WHOOP’s Strain score; it does not measure all-day exertion.'},{key:'steps',label:'Workout steps',unit:'steps',description:'Steps recorded inside synced workouts only. Tredict does not supply your all-day step count through this connection.'},{key:'minutes',label:'Training time',unit:'min',description:'Total recorded workout duration today. Missing durations are excluded.'}].map(m=>{const key=m.key as 'steps'|'minutes'|'effort',history=days.slice(1).filter(d=>d.active&&!d[key].partial&&d[key].value!==null&&d[key].value!>0).map(d=>d[key].value!);return {...m,...days[0][key],referenceDays:history.length,series:days.slice(0,7).reverse().map(d=>({date:d.date,value:d[key].partial?null:d[key].value,partial:d[key].partial})),reference:history.length>=3?Math.max(...history):null}});
}
