"use client";
import {Activity,Footprints,Timer,ArrowUpRight} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import type {AthleteData} from './analytics';
import {useExpand} from './expansion';
import {localDate} from './week-overview';
import {dailyRingMetrics} from './daily-ring-data';
const number=(v:number|null)=>v===null?'—':Math.round(v).toLocaleString('en-GB');
export default function DailyRings({data,now}:{data:AthleteData;now:Date}){
 const expand=useExpand(),metrics=dailyRingMetrics(data,now,localDate);
 function open(m:typeof metrics[number]){expand.widget(m.label,<div className="ring-explanation"><div className="ring-detail-stats"><div><span>Today</span><strong>{number(m.value)} <small>{m.unit}</small></strong></div><div><span>28-day high</span><strong>{number(m.reference)} <small>{m.unit}</small></strong></div><div><span>Reference coverage</span><strong>{m.referenceDays} <small>workout days</small></strong></div></div><p>{m.description}</p><h3>Last seven days</h3><div className="ring-week-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={m.series} margin={{left:0,right:12,top:10,bottom:0}}><CartesianGrid vertical={false} stroke="#eee"/><XAxis dataKey="date" tickFormatter={d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short'})} tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip labelFormatter={d=>String(d)} formatter={v=>[number(typeof v==='number'?v:null)+' '+m.unit,m.label]}/><Bar dataKey="value" fill="#343b38" radius={[4,4,0,0]} maxBarSize={38}/></BarChart></ResponsiveContainer></div><p>{m.partial?'Some sessions are missing this measurement; today’s total is partial.':m.value===null?'This measurement was not returned.':'Today includes synced workouts so far.'} Chart gaps mean missing or partial measurements.</p><details><summary>How the ring is calculated</summary><p>{m.reference?`Ring fill compares today with your highest fully measured active day in the previous 28 days (${number(m.reference)} ${m.unit}). A full ring is a reference, not a target or a signal to stop training. The number and percentage keep increasing above that reference.`:'At least three fully measured active days are needed for a reference. Until then, the total is shown with an unfilled ring.'}</p></details></div>)}
 return <section className="daily-rings home-surface" aria-label="Daily activity rings"><header><div><span className="ring-eyebrow">TODAY</span><h2>Daily movement</h2></div><span className="ring-source">From workouts</span></header><div className="daily-ring-grid">{metrics.map(m=>{const percent=m.value!==null&&m.reference?m.value/m.reference*100:null,ratio=Math.min(1,(percent??0)/100),Icon=m.key==='effort'?Activity:m.key==='steps'?Footprints:Timer;return <button key={m.key} className="daily-ring-widget" onClick={()=>open(m)} aria-label={`${m.label}: ${number(m.value)} ${m.unit}. ${m.partial?'Partial data. ':''}Open seven-day chart.`}><span className="daily-ring-dial"><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="43" className="ring-track"/>{ratio>0&&<circle cx="50" cy="50" r="43" className="ring-progress" pathLength="100" strokeDasharray={`${ratio*100} 100`} transform="rotate(-90 50 50)"/>}</svg><span><Icon size={16} strokeWidth={1.6}/><strong>{number(m.value)}</strong><small>{m.unit}</small></span></span><b>{m.label}</b><small>{m.partial?'Partial total':m.value===null?'Not supplied':percent===null?'Learning your pattern':`${Math.round(percent)}% of recent high`}</small><span className="ring-open">7-day view <ArrowUpRight size={12}/></span></button>})}</div><div className="ring-footnote">Steps are workout-only. Rings show context, not daily goals.</div></section>
}
