"use client";
import {useExpand} from "./expansion";
import type {Workout} from './analytics';
import {sportFamily,sportName,sportDescription,runningPace,workoutSpeed,cadenceUnit} from './sports';
import {mean,numeric} from './performance-math';
const fmt=(n:unknown,d=1)=>numeric(n)?n.toLocaleString('en-GB',{maximumFractionDigits:d}):'—';
export default function DisciplinePanel({activities,filter,onFilter,onSelect}:{activities:Workout[];filter:string;onFilter:(s:string)=>void;onSelect:(a:Workout)=>void}){
 const expand=useExpand();
 const selected=['running','cycling','strength_training'].includes(filter)?filter:'running';
 const rows=activities.filter(a=>sportFamily(a)===selected),values=(k:string)=>rows.map(a=>a.summary?.[k]),total=(k:string)=>{const v=values(k).filter(numeric);return v.length?v.reduce((a,b)=>a+b,0):null};
 const latest=rows.find(a=>numeric(a.summary?.vo2max)),paceRows=rows.filter(a=>numeric(a.summary?.pace));
 const stats=selected==='cycling'?[['Distance',numeric(total('distance'))?`${fmt(total('distance')!/1000)} km`:'—','Reported cycling distance'],['Mean session power',`${fmt(mean(values('power')),0)} W`,'Session averages · cycling only'],['Mean session speed',`${fmt(mean(rows.map(workoutSpeed)))} km/h`,'Reported speed, or distance / moving duration'],['Mean cadence',`${fmt(mean(values('cadence')),0)} rpm`,'Cycling cadence']]:selected==='running'?[['Distance',numeric(total('distance'))?`${fmt(total('distance')!/1000)} km`:'—','Reported running distance'],['Mean session pace',runningPace(mean(values('pace'))),'Unweighted mean · eligible runs'],['Mean session HR',`${fmt(mean(values('heartrate')),0)} bpm`,'Recorded running heart rate'],['Mean cadence',`${fmt(mean(values('cadence')),0)} steps/min`,'Running cadence']]:[['Strength sessions',String(rows.length),'Strength remains separate from Other'],['Training time',numeric(total('duration'))?`${fmt(total('duration')!/3600,2)} h`:'—','Recorded strength-session durations'],['Mean session HR',`${fmt(mean(values('heartrate')),0)} bpm`,'Reported session heart rate'],['Recorded energy',`${fmt(total('calories'),0)} kcal`,'Reported calorie estimates']];
 return <section className="discipline-panel"><nav className="studio-tabs" aria-label="Sport-specific analysis">{['running','cycling','strength_training'].map(s=><button key={s} aria-pressed={selected===s} onClick={()=>onFilter(s)}>{sportName(s)}</button>)}</nav><div className="studio-stats">{stats.map(([title,value,note])=><button className="studio-stat metric-interactive" key={title} onClick={()=>title.includes("VO₂")?expand.metric(title):expand.widget(title,<div className="expanded-snapshot"><strong>{value}</strong><p>{note}</p></div>)}><span>{title}</span><strong>{value}</strong><small>{note}</small></button>)}</div><section className="panel"><div className="panel-head"><div><h2>{sportName(selected)} analysis</h2><p>{selected==='cycling'?'Power, speed, cadence and climbing. Road, indoor and other cycling subtypes stay together.':selected==='running'?'Pace, heart rate, cadence and running dynamics. Running subtypes stay together.':'Duration, frequency, heart rate and energy. Sets, repetitions and lifted weight are not supplied by these summaries.'}</p></div></div><div className="table-wrap"><table><thead><tr><th>Session</th><th>Date</th><th>Duration</th>{selected!=='strength_training'&&<th>Distance</th>}<th>{selected==='cycling'?'Speed':selected==='running'?'Pace':'Energy'}</th><th>{selected==='cycling'?'Avg power':'Avg HR'}</th>{selected!=='strength_training'&&<th>Cadence</th>}<th>{selected==='cycling'?'Ascent':selected==='running'?'Ground contact':'Max HR'}</th></tr></thead><tbody>{rows.slice(0,10).map(a=><tr key={a.id}><td><button className="session-name" onClick={()=>onSelect(a)}><span><strong>{a.title||sportName(selected)}</strong><small>{sportDescription(a)}</small></span></button></td><td>{a.date.slice(0,10)}</td><td>{numeric(a.summary?.duration)?`${fmt(a.summary!.duration/60,0)} min`:'—'}</td>{selected!=='strength_training'&&<td>{numeric(a.summary?.distance)?`${fmt(a.summary!.distance/1000)} km`:'—'}</td>}<td>{selected==='cycling'?`${fmt(workoutSpeed(a))} km/h`:selected==='running'?runningPace(a.summary?.pace):`${fmt(a.summary?.calories,0)} kcal`}</td><td>{selected==='cycling'?`${fmt(a.summary?.power,0)} W`:`${fmt(a.summary?.heartrate,0)} bpm`}</td>{selected!=='strength_training'&&<td>{fmt(a.summary?.cadence,0)} {cadenceUnit(selected)}</td>}<td>{selected==='cycling'?`${fmt(a.summary?.altitude?.ascent,0)} m`:selected==='running'?`${fmt(a.summary?.groundContactTime,0)} ms`:`${fmt(a.summary?.heartrateMax,0)} bpm`}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No {sportName(selected).toLowerCase()} sessions in this date range.</p>}</div><p className="lab-note">{rows.length} sessions in this period. {selected==='running'?`${paceRows.length} have recorded pace. `:''}Missing measurements remain empty. Open a session for detailed telemetry and sustained-effort analysis.</p></section></section>
}
