"use client";
import {useMemo,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {progressRecords} from './training-coach-data';
import type {AthleteData,Workout} from './analytics';
import {runningPace} from './sports';
import {valueTrend} from './trend';
import TrendBadge from './trend-badge';
export default function EffortProgress({data,now,family,onSelect}:{data:AthleteData;now:Date;family:'running'|'cycling';onSelect:(a:Workout)=>void}){
 const [days,setDays]=useState(28),r=useMemo(()=>progressRecords(data,now,family,days),[data,now,family,days]),format=(v:number)=>family==='running'?runningPace(1000/v):`${Math.round(v)} W`;
 const rows=r.rows.map(p=>({...p,label:`${p.seconds/60} min`,current:p.recent?.value??null,previous:p.prior?.value??null}));
 return <div className="coach-evidence"><label className="coach-period">Compare equal periods <select value={days} onChange={e=>setDays(+e.target.value)}>{[28,90,365].map(d=><option key={d} value={d}>Last {d} vs prior {d} days</option>)}</select></label><p>Best sampled efforts over fixed durations, through yesterday. Blue: recent period. Grey: previous period. {r.analyzed}/{r.eligible} sessions processed{!r.historyCovered?' · period history incomplete':''}.</p><div style={{height:200,width:'100%'}}><ResponsiveContainer><LineChart data={rows} margin={{left:10,right:12,top:10,bottom:0}}><CartesianGrid vertical={false} stroke="#edf0f4"/><XAxis dataKey="label" tick={{fontSize:12}}/><YAxis tick={{fontSize:11}} width={family==='running'?72:44} domain={['auto','auto']} tickFormatter={format}/><Tooltip labelFormatter={v=>`${v} best`} formatter={(v:any,name:any)=>[format(Number(v)),name==='current'?'Recent':'Previous']}/><Line dataKey="previous" stroke="#929faf" strokeDasharray="3 3" connectNulls={false} isAnimationActive={false}/><Line dataKey="current" stroke="#2c65ba" strokeWidth={2} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><div className="coach-table-scroll"><table><thead><tr><th>Effort</th><th>Recent</th><th>Previous</th><th>Change</th></tr></thead><tbody>{r.rows.map(p=><tr key={p.seconds}><th>{p.seconds/60} min</th>{[p.recent,p.prior].map((v,i)=><td key={i}>{v?<><strong>{format(v.value)}</strong><button className="coach-session" onClick={()=>onSelect(v.activity)}>{new Date(v.activity.date).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'2-digit'})} ↗</button></>:'—'}</td>)}<td><TrendBadge trend={valueTrend(p.recent?.value,p.prior?.value,'higher',`previous ${days} days`)}/></td></tr>)}</tbody></table></div><p>Compared range: {r.from} to {r.to}. Loaded history starts {data.historyStart?.slice(0,10)??'unknown'}.</p><p>These are recorded efforts, not maximum-capacity tests. Missing samples invalidate a window; power zeroes are retained. Running uses recorded speed averaged over time, then converts to pace. Sample-aligned windows can miss a peak between samples.</p><p>A lower best effort can reflect different sessions or terrain. Analyse older sessions for broader coverage; a missing comparison is never treated as a decline.</p></div>;
}
