"use client";
import {createContext,useContext,useEffect,useRef,useState,useMemo,lazy,Suspense,type ReactNode} from 'react';
import {X,Maximize2} from 'lucide-react';
import type {AthleteData} from './analytics';
const MetricTrend=lazy(()=>import('./metric-trend'));
const WidgetComparisons=lazy(()=>import('./widget-comparisons'));
const Context=createContext<{close:()=>void;metric:(title:string,snapshot?:ReactNode)=>void;widget:(title:string,content:ReactNode)=>void}>({close:()=>{},metric:()=>{},widget:()=>{}});
export const useExpand=()=>useContext(Context);
export function ExpandButton({title,children}:{title:string;children:ReactNode}){const expand=useExpand();return <button className="expand-widget" aria-label={`Enlarge ${title}`} onClick={()=>expand.widget(title,children)}><Maximize2 size={16}/></button>}
export default function ExpansionProvider({data,isDemo,children}:{data:AthleteData;isDemo:boolean;children:ReactNode}){
 const [view,setView]=useState<{title:string;content?:ReactNode;snapshot?:ReactNode}|null>(null),dialog=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!view)return;const previous=document.activeElement as HTMLElement,old=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLElement>('button')?.focus({preventScroll:true});const handle=(e:KeyboardEvent)=>{if(document.querySelector('.athena-chat[open], .share-canvas[open]'))return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();setView(null)}if(e.key==='Tab'){const items=[...Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),select,input,summary,a[href]')??[]),...Array.from(document.querySelectorAll<HTMLElement>('.athena-launcher'))];if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus()}}};document.addEventListener('keydown',handle,true);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',handle,true);previous?.focus({preventScroll:true})}},[!!view]);
 const controls=useMemo(()=>({close:()=>setView(null),metric:(title:string,snapshot?:ReactNode)=>setView({title,snapshot}),widget:(title:string,content:ReactNode)=>setView({title,content})}),[]);
 return <Context.Provider value={controls}><div inert={!!view}>{children}</div>{view&&<div className="overlay metric-expansion sieste-v3" onClick={()=>setView(null)}><div data-athena-screen={`Widget / ${view.title}`} className="expanded-widget" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="expanded-title" onClick={e=>e.stopPropagation()}><header><div><h2 id="expanded-title">{view.title}</h2></div><button aria-label="Close expanded widget" onClick={()=>setView(null)}><X size={22}/></button></header><div className="expanded-widget-body"><Suspense fallback={<p role="status">Loading metric details…</p>}>{!["Training load analysis","Efforts & terrain"].includes(view.title)&&<WidgetComparisons title={view.title} data={data} isDemo={isDemo} showChart={!!view.content}/>}{view.content??<MetricTrend key={view.title} title={view.title} data={data} isDemo={isDemo} snapshot={view.snapshot}/>}</Suspense></div></div></div>}</Context.Provider>
}
