"use client";
import LoadGuidance from './load-guidance';
import {useMemo,useState,lazy,Suspense} from 'react';
import CompactLoadChart from './compact-load-chart';
const LoadChart=lazy(()=>import('./load-chart'));
import {useExpand} from './expansion';
import {loadAnalysis} from './load-analysis-data';
import {loadOverlays,formatLoadOverlay,defaultLoadLayers} from './load-chart-series';
import {metricStatus} from './metric-status';
import {sportFamily} from './sports';
import type {AthleteData} from './analytics';
const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:1});
function LoadTool({data,now,large=false}:{data:AthleteData;now:Date;large?:boolean}){
 const [days,setDays]=useState(large?28:14),[mode,setMode]=useState<'load'|'time'>('load'),[layers,setLayers]=useState(defaultLoadLayers),[hover,setHover]=useState<ReturnType<typeof loadAnalysis>['rows'][number]|null>(null);
 const model=useMemo(()=>loadAnalysis(data,now,days,mode),[data,now,days,mode]),row=hover??model.today,overlays=useMemo(()=>loadOverlays(model),[model]),activeLayers=layers.filter(key=>mode==='load'||key!=='minutes');
 const amount=(v:number|null)=>v===null?'—':mode==='load'?`${Math.round(v).toLocaleString('en-GB')}`:`${Math.floor(Math.round(v)/60)}h ${Math.round(v)%60}m`;
 const range=(rows:typeof model.recent)=>`${rows[0]?.label} – ${rows.at(-1)?.label}`;
 const direction=!model.complete?'Some training data is missing':model.change===null?model.previous===0?'Training resumed after a zero-load week':'Not enough history to compare':Math.abs(model.change)<1?'About the same as the previous week':`${Math.round(Math.abs(model.change))}% ${model.change>0?'more':'less'} ${mode==='time'?'training time':'training load'} than the previous week`;
 const usual=model.baseline===null?null:model.baseline*7,vsUsual=model.ratio===null?null:(model.ratio-1)*100;

 const toggle=(key:string)=>setLayers(v=>v.includes(key)?activeLayers.length>1?v.filter(k=>k!==key):v:[...v,key]);
 return <><LoadGuidance data={data} now={now}/><div className="load-tool-controls"><select aria-label="Load analysis measure" value={mode} onChange={e=>{const next=e.target.value as 'load'|'time';setMode(next);setHover(null);if(next==='time')setLayers(current=>current.includes('minutes')&&!current.includes('value')?[...current,'value']:current)}}><option value="load">Training load</option><option value="time">Training time</option></select><span>All sports</span>{large&&<select aria-label="Load analysis period" value={days} onChange={e=>{setDays(+e.target.value);setHover(null)}}>{[14,28,90].map(n=><option key={n} value={n}>{n} days</option>)}</select>}</div>
 <div className="load-clear-verdict"><b>{direction}</b><span>{vsUsual===null?'A full 28-day history is needed for your usual level.':Math.abs(vsUsual)<1?'Also close to your usual weekly level.':`${Math.round(Math.abs(vsUsual))}% ${vsUsual>0?'above':'below'} your usual weekly level.`}</span></div>
 <div className="load-tool-kpis"><div><small>Last 7 days</small><strong>{amount(model.total)}{!model.complete&&<em> *</em>}</strong><span>{mode==='load'?'load points · ':''}{range(model.recent)}</span></div><div><small>Previous 7 days</small><strong>{amount(model.previous)}</strong><span>{range(model.prior)}</span></div><div><small>Your usual week</small><strong>{amount(usual)}</strong><span>Based on last 28 days</span></div></div>
 <div className="load-clear-chart-label"><b>Daily {mode==='time'?'training time (min)':'load (points)'}</b><span>{model.baseline!==null?<><i/> Your usual daily level</>:'Usual level unavailable'}</span></div>
 <div className="load-tool-legend load-overlay-legend" aria-label="Training and recovery chart layers">{large&&[['value','Daily','#a5b4fc'],['short','7d average','#4f46e5'],['long','28d average','#64748b']].map(([k,label,color])=><button key={k} aria-pressed={activeLayers.includes(k)} onClick={()=>toggle(k)}><i style={{background:color}}/>{label}</button>)}{overlays.map(series=><button key={series.key} aria-pressed={activeLayers.includes(series.key)} aria-label={`${series.label} overlay, ${series.key==='fatigue'&&mode==='load'?'shared training-load':'separate'} scale 0 to ${series.ceiling} ${series.unit}`} onClick={()=>toggle(series.key)}><i className={series.dash?'is-dashed':''} style={{color:series.color,borderColor:series.color}}/><span>{series.label}<small>0–{series.ceiling} {series.unit}</small></span></button>)}</div>
 <p className="load-overlay-scale-note">Estimated fatigue: recent load · other lines use separate scales</p>
 <div className="load-tool-chart" style={{height:large?300:180}}>{large?<Suspense fallback={<p role="status">Loading load chart…</p>}><LoadChart model={model} large layers={activeLayers} onHover={setHover}/></Suspense>:<CompactLoadChart model={model} layers={activeLayers} activeIso={hover?.iso} onHover={setHover}/>}</div>
 <div className="load-tool-readout"><b>{row.label}</b><span>{amount(row.value)}{mode==='load'?' points':''} · {row.sessions} session{row.sessions===1?'':'s'}{row.iso===model.today.iso?' · training so far':''}</span>{large&&<><span>7d avg {fmt(row.short)}</span><span>28d avg {fmt(row.long)}</span></>}</div>
 <div className="load-overlay-readout" aria-live="polite">{overlays.filter(series=>activeLayers.includes(series.key)).map(series=><span key={series.key} style={{color:series.color}}>{series.label} <b>{formatLoadOverlay(series.key,row[series.key])}</b>{series.key==='minutes'&&row.iso===model.today.iso?<small> so far</small>:series.key==='fatigue'?<small>{row.fatigue===null?' insufficient history':row.fatigueProvisional?' provisional':''}</small>:null}</span>)}</div>
 {model.missing.length>0&&<p className="load-tool-gap">{model.missing.length}/{days} days missing {mode==='load'?'load':'duration'} · gaps mean unknown, not rest{mode==='load'?'. Switch to training time for a volume view.':'.'}</p>}
 {large&&<div className="load-tool-recovery">{(['sleep','hrv','rhr'] as const).map(key=>{const status=metricStatus(key,data,now,sportFamily);return <span key={key} className={`status-${status.tone}`} title={status.reason}><b>{key==='rhr'?'RHR':key==='hrv'?'HRV':'Sleep'}</b> {status.label}</span>})}</div>}
 <p className="load-tool-note">{mode==='load'?'Taller bars = more recorded training load. Points reflect duration and intensity.':'Taller bars = more time training; intensity is not included.'} Today is partial and excluded from weekly totals. {large?`${model.source}. More is not automatically better.`:''}</p>
 {large&&<details className="load-fatigue-method"><summary>How estimated fatigue works</summary><p>A seven-day exponentially weighted average of daily {data.provider==='coros'?'COROS load':'Tredict effort'}. Hard sessions raise the line; confirmed rest days let it decay. This estimates accumulated training stress, not measured tiredness. Sleep, HRV and how you feel provide recovery context.</p><p>The model starts with the first seven complete days’ mean, then carries about 87% of yesterday’s value and adds about 13% of today’s load. It appears after 28 consecutive completed days. Missing load, incomplete history and exclusions interrupt the estimate and restart that warm-up. Today’s value is provisional, based on training synced so far. Changing the chart period or switching to training time keeps the same load-based estimate.</p></details>}
 {large&&<><details><summary>Daily load & coverage</summary><div className="table-wrap"><table><thead><tr><th>Day</th><th>Sessions</th><th>{model.unit}</th><th>Time (min)</th><th>Est. fatigue (pts)</th><th>Sleep</th><th>HRV (ms)</th><th>7d avg</th><th>28d avg</th></tr></thead><tbody>{[...model.rows].reverse().map(r=><tr key={r.iso}><td>{r.iso}{r.iso===model.today.iso?' *':''}</td><td>{r.sessions}</td><td>{fmt(r.value)}</td><td>{fmt(r.minutes)}</td><td>{fmt(r.fatigue)}{r.fatigueProvisional?' *':''}</td><td>{formatLoadOverlay('sleep',r.sleep)}</td><td>{fmt(r.hrv)}</td><td>{fmt(r.short)}</td><td>{fmt(r.long)}</td></tr>)}</tbody></table></div></details><p>Seven-day totals compare the last seven finished calendar days with the preceding seven. The baseline is the mean of the last 28 finished days. The chart’s averages include the selected day. Missing values are never zero-filled; rest days count as zero only in complete synced history. Tredict effort and COROS load are kept separate. Sleep and HRV stay on their recorded date; sleep is the night ending that morning, before that day’s training. Sleep, HRV and training-time lines use their own labelled scales. Estimated fatigue stays in load points and shares the load axis; training-time mode gives it a separate points scale. Matching heights across different units do not mean equivalent values. These rolling averages describe training, not measured fatigue, fitness or an overtraining diagnosis.</p></>}
 </>;
}
export default function FatigueRecovery({data,now}:{data:AthleteData;now:Date}){const expand=useExpand();return <section className="fatigue-recovery load-analysis" aria-label="Training load analysis"><header><h2>Training load</h2><button onClick={()=>expand.widget('Training load analysis',<div className="load-analysis"><LoadTool data={data} now={now} large/></div>)}>Analyse ↗</button></header><LoadTool data={data} now={now}/></section>}
