"use client";
import {useMemo,useState} from 'react';
import {ResponsiveContainer,ComposedChart,Line,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine,Cell} from 'recharts';
import {useExpand} from './expansion';
import {loadAnalysis} from './load-analysis-data';
import {metricStatus} from './metric-status';
import {sportFamily} from './sports';
import type {AthleteData} from './analytics';
const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:1});
function LoadTool({data,now,large=false}:{data:AthleteData;now:Date;large?:boolean}){
 const [days,setDays]=useState(large?28:14),[mode,setMode]=useState<'load'|'time'>('load'),[layers,setLayers]=useState(['value']),[hover,setHover]=useState<any>(null);
 const model=useMemo(()=>loadAnalysis(data,now,days,mode),[data,now,days,mode]),row=hover??model.today;
 const amount=(v:number|null)=>v===null?'—':mode==='load'?`${Math.round(v).toLocaleString('en-GB')}`:`${Math.floor(Math.round(v)/60)}h ${Math.round(v)%60}m`;
 const range=(rows:typeof model.recent)=>`${rows[0]?.label} – ${rows.at(-1)?.label}`;
 const direction=!model.complete?'Some training data is missing':model.change===null?model.previous===0?'Training resumed after a zero-load week':'Not enough history to compare':Math.abs(model.change)<1?'About the same as the previous week':`${Math.round(Math.abs(model.change))}% ${model.change>0?'more':'less'} ${mode==='time'?'training time':'training load'} than the previous week`;
 const usual=model.baseline===null?null:model.baseline*7,vsUsual=model.ratio===null?null:(model.ratio-1)*100;

 const toggle=(key:string)=>setLayers(v=>v.includes(key)?v.length>1?v.filter(k=>k!==key):v:[...v,key]);
 return <><div className="load-tool-controls"><select aria-label="Load analysis measure" value={mode} onChange={e=>{setMode(e.target.value as 'load'|'time');setHover(null)}}><option value="load">Training load</option><option value="time">Training time</option></select><span>All sports</span>{large&&<select aria-label="Load analysis period" value={days} onChange={e=>{setDays(+e.target.value);setHover(null)}}>{[14,28,90].map(n=><option key={n} value={n}>{n} days</option>)}</select>}</div>
 <div className="load-clear-verdict"><b>{direction}</b><span>{vsUsual===null?'A full 28-day history is needed for your usual level.':Math.abs(vsUsual)<1?'Also close to your usual weekly level.':`${Math.round(Math.abs(vsUsual))}% ${vsUsual>0?'above':'below'} your usual weekly level.`}</span></div>
 <div className="load-tool-kpis"><div><small>Last 7 days</small><strong>{amount(model.total)}{!model.complete&&<em> *</em>}</strong><span>{mode==='load'?'load points · ':''}{range(model.recent)}</span></div><div><small>Previous 7 days</small><strong>{amount(model.previous)}</strong><span>{range(model.prior)}</span></div><div><small>Your usual week</small><strong>{amount(usual)}</strong><span>Based on last 28 days</span></div></div>
 <div className="load-clear-chart-label"><b>Daily {mode==='time'?'training time (min)':'load (points)'}</b><span>{model.baseline!==null?<><i/> Your usual daily level</>:'Usual level unavailable'}</span></div>
 {large&&<div className="load-tool-legend">{[['value','Daily','#a5b4fc'],['short','7d average','#4f46e5'],['long','28d average','#64748b']].map(([k,label,color])=><button key={k} aria-pressed={layers.includes(k)} onClick={()=>toggle(k)}><i style={{background:color}}/>{label}</button>)}</div>}
 <div className="load-tool-chart" style={{height:large?300:170}}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={model.rows} margin={{left:-15,right:8,top:8,bottom:0}} onMouseMove={(s:any)=>{if(s?.activePayload?.[0]?.payload)setHover(s.activePayload[0].payload)}} onMouseLeave={()=>setHover(null)}><CartesianGrid vertical={false} stroke="#ececf1" strokeDasharray="2 4"/><XAxis dataKey="label" tick={{fontSize:10}} minTickGap={38} axisLine={false} tickLine={false}/><YAxis width={44} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip content={()=>null} cursor={{stroke:'#a5b4fc'}}/>{model.baseline!==null&&<ReferenceLine y={model.baseline} ifOverflow="extendDomain" stroke="#64748b" strokeDasharray="4 4"/>}{layers.includes('value')&&<Bar dataKey="value" fill="#a5b4fc" maxBarSize={large?16:22} radius={[3,3,0,0]} isAnimationActive={false}>{model.rows.map(r=><Cell key={r.iso} fill={r.iso===model.today.iso?'#c7d2fe':r.iso>=model.recent[0].iso?'#6366f1':'#a5b4fc'} stroke={r.iso===model.today.iso?'#6366f1':undefined} strokeDasharray={r.iso===model.today.iso?'3 2':undefined}/>)}</Bar>} {layers.includes('short')&&<Line dataKey="short" stroke="#4f46e5" strokeWidth={2} dot={false} connectNulls={false} isAnimationActive={false}/>} {layers.includes('long')&&<Line dataKey="long" stroke="#64748b" strokeDasharray="3 4" dot={false} connectNulls={false} isAnimationActive={false}/>}</ComposedChart></ResponsiveContainer></div>
 <div className="load-tool-readout"><b>{row.label}{row.iso===model.today.iso?' · so far':''}</b><span>{amount(row.value)}{mode==='load'?' points':''} · {row.sessions} session{row.sessions===1?'':'s'}</span>{large&&<><span>7d avg {fmt(row.short)}</span><span>28d avg {fmt(row.long)}</span></>}</div>
 {model.missing.length>0&&<p className="load-tool-gap">{model.missing.length}/{days} days missing {mode==='load'?'load':'duration'} · gaps mean unknown, not rest{mode==='load'?'. Switch to training time for a volume view.':'.'}</p>}
 {large&&<div className="load-tool-recovery">{(['sleep','hrv','rhr'] as const).map(key=>{const status=metricStatus(key,data,now,sportFamily);return <span key={key} className={`status-${status.tone}`} title={status.reason}><b>{key==='rhr'?'RHR':key==='hrv'?'HRV':'Sleep'}</b> {status.label}</span>})}</div>}
 <p className="load-tool-note">{mode==='load'?'Taller bars = more recorded training load. Points reflect duration and intensity.':'Taller bars = more time training; intensity is not included.'} Today is partial and excluded from weekly totals. {large?`${model.source}. More is not automatically better.`:''}</p>
 {large&&<><details><summary>Daily load & coverage</summary><div className="table-wrap"><table><thead><tr><th>Day</th><th>Sessions</th><th>{model.unit}</th><th>7d avg</th><th>28d avg</th></tr></thead><tbody>{[...model.rows].reverse().map(r=><tr key={r.iso}><td>{r.iso}{r.iso===model.today.iso?' *':''}</td><td>{r.sessions}</td><td>{fmt(r.value)}</td><td>{fmt(r.short)}</td><td>{fmt(r.long)}</td></tr>)}</tbody></table></div></details><p>Seven-day totals compare the last seven finished calendar days with the preceding seven. The baseline is the mean of the last 28 finished days. The chart’s averages include the selected day. Missing values are never zero-filled; rest days count as zero only in complete synced history. Tredict effort and COROS load are kept separate. These rolling averages describe training, not measured fatigue, fitness or an overtraining diagnosis.</p></>}
 </>;
}
export default function FatigueRecovery({data,now}:{data:AthleteData;now:Date}){const expand=useExpand();return <section className="fatigue-recovery load-analysis" aria-label="Training load analysis"><header><h2>Training load</h2><button onClick={()=>expand.widget('Training load analysis',<div className="load-analysis"><LoadTool data={data} now={now} large/></div>)}>Analyse ↗</button></header><LoadTool data={data} now={now}/></section>}
