"use client";
import {useEffect,useRef,useState,lazy,Suspense} from 'react';
import {createPortal} from 'react-dom';
import {MoreHorizontal,Upload,X} from 'lucide-react';
import {loadWorkoutView} from './activity-loader';
import {WorkoutLoading} from './loading-state';
import ExpansionProvider from './expansion';
const WorkoutDetails=lazy(loadWorkoutView);
export default function HomeActivityImport(){
 const menu=useRef<HTMLDetailsElement>(null),picker=useRef<HTMLInputElement>(null),dialog=useRef<HTMLElement>(null),generation=useRef(0);
 const [open,setOpen]=useState(false),[detail,setDetail]=useState<Record<string,any>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function close(){generation.current++;setOpen(false);setDetail(null);setBusy(false);setError('')}
 useEffect(()=>{const outside=(event:PointerEvent)=>{if(menu.current&&!menu.current.contains(event.target as Node))menu.current.open=false};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&menu.current?.open){menu.current.open=false;menu.current.querySelector('summary')?.focus()}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{generation.current++;document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[]);
 useEffect(()=>{if(!open)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLElement>('button')?.focus();const handle=(event:KeyboardEvent)=>{if(document.querySelector('.share-canvas[open]'))return;if(event.key==='Escape'&&!document.querySelector('.metric-expansion'))close();if(event.key==='Tab'){const items=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled)')??[]);if(event.shiftKey&&document.activeElement===items[0]){event.preventDefault();items.at(-1)?.focus()}else if(!event.shiftKey&&document.activeElement===items.at(-1)){event.preventDefault();items[0]?.focus()}}};document.addEventListener('keydown',handle);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handle);requestAnimationFrame(()=>menu.current?.querySelector('summary')?.focus({preventScroll:true}))}},[open]);
 async function choose(file:File){const epoch=++generation.current;setBusy(true);setError('');try{const {importFitFile}=await import('./import-fit');const imported=await importFitFile(file);if(epoch===generation.current)setDetail(imported)}catch(e){if(epoch===generation.current)setError(e instanceof Error?e.message:'The activity could not be imported.')}finally{if(epoch===generation.current)setBusy(false)}}
 return <><details className="home-more-menu" ref={menu}><summary aria-label="More homepage actions" title="More"><MoreHorizontal size={17}/></summary><div className="home-more-popover"><button onClick={()=>{if(menu.current)menu.current.open=false;setOpen(true)}}><Upload size={14}/>Import activity</button></div></details>{open&&createPortal(<ExpansionProvider data={{activities:detail?[detail as import('./analytics').Workout]:[],sleep:{},hrv:{}}} isDemo={false}><div className="sieste-v3 activity-layer"><div className="overlay activity-card-stack" onClick={close}>{detail?<Suspense fallback={<WorkoutLoading onClose={close}/>}><WorkoutDetails activity={detail as import('./analytics').Workout} preloadedDetail={detail} manageScroll={false} history={[]} token="" isDemo={false} onClose={close}/></Suspense>:<section ref={dialog} className="modal activity-import-modal" role="dialog" aria-modal="true" aria-labelledby="activity-import-title" onClick={e=>e.stopPropagation()}><header><h2 id="activity-import-title">Import activity</h2><button className="icon-button" aria-label="Close activity import" onClick={close}><X size={19}/></button></header><p>Open a Garmin activity export or another watch’s FIT file to explore its recorded data.</p><input ref={picker} type="file" accept=".fit" hidden aria-label="Activity FIT file" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void choose(file)}}/><button className="primary-button" disabled={busy} onClick={()=>picker.current?.click()}><Upload size={16}/>{busy?'Reading activity…':'Choose FIT file'}</button><small>FIT · up to 16 MB. Unzip Garmin exports first.</small><p className="activity-import-footnote">Opens on this device for analysis. Your training history stays unchanged.</p>{error&&<p role="alert" className="error">{error}</p>}</section>}</div></div></ExpansionProvider>,document.body)}</>;
}
