import {sportFamily} from './sports';
export type ReviewSignal={title:string;detail:string;flag:boolean;available:boolean};
export function trainingReview(activities:{date:string;sportType:string;subSportType?:string;summary?:Record<string,any>}[],end:string,historyStart?:string,threshold=30):ReviewSignal[]{
 const endDate=new Date(end);endDate.setUTCHours(23,59,59,999);const recent=new Date(endDate);recent.setUTCHours(0,0,0,0);recent.setUTCDate(recent.getUTCDate()-6);const baseline=new Date(recent);baseline.setUTCDate(baseline.getUTCDate()-28);
 return ['running','cycling','strength_training'].map(family=>{const group=activities.filter(a=>sportFamily(a)===family&&new Date(a.date)>=baseline&&new Date(a.date)<=endDate),r=group.filter(a=>new Date(a.date)>=recent),b=group.filter(a=>new Date(a.date)<recent);const complete=historyStart?new Date(historyStart)<=baseline:activities.some(a=>new Date(a.date)<=baseline);const invalid=group.some(a=>typeof a.summary?.duration!=='number'||!Number.isFinite(a.summary.duration)||a.summary.duration<0);const base=b.reduce((s,a)=>s+(a.summary?.duration??0),0)/4,now=r.reduce((s,a)=>s+(a.summary?.duration??0),0);const available=complete&&!invalid&&base>0,change=available?(now/base-1)*100:null;return {title:family==='strength_training'?'Strength training volume':`${family==='running'?'Running':'Cycling'} volume`,available,flag:available&&change!>threshold,detail:available?`${(now/3600).toFixed(1)} h in the last 7 days versus ${(base/3600).toFixed(1)} h/week across the previous 28 days (${change!>=0?'+':''}${change!.toFixed(0)}%).`:invalid?'Some sessions have no duration; this comparison is unavailable.':'Not enough prior training history for a meaningful comparison.'}});
}
export function symptomGuidance({pain,emergency,urgent}:{pain:number;emergency:boolean;urgent:boolean}){
 if(emergency)return {level:'emergency',title:'Seek emergency medical care',message:'After an injury, a changed shape, numbness or tingling, a cold or blue/grey limb, or a crack at the time of injury needs urgent emergency assessment. Stop training and contact your local emergency service.'};
 if(urgent)return {level:'urgent',title:'Get prompt medical advice',message:'Severe or worsening pain, substantial swelling, or difficulty bearing weight or using the area needs assessment. Stop the activity and contact a clinician or local urgent-care service.'};
 if(pain>0)return {level:'review',title:'Pain deserves attention',message:'Do not push through an activity that causes pain. If symptoms persist, worsen, or keep returning, arrange an assessment with a clinician or physiotherapist. Training metrics cannot determine the cause.'};
 return {level:'unknown',title:'No pain reported in this check-in',message:'This does not rule out injury or confirm that training is safe. Notice new symptoms and seek advice if concerned.'};
}
