"use client";
import {useState,useMemo} from 'react';
import {intervalConsistency} from './training-coach-data';
import {sportFamily,runningPace} from './sports';
import {valueTrend} from './trend';
import {effortProfile} from './effort-profile-data';
import TrendBadge from './trend-badge';
const labels:Record<string,string>={pace:'Pace',power:'Power',heartrate:'HR',cadence:'Cadence',stepLength:'Step length'};
export default function IntervalConsistency({detail}:{detail:any}){
 const [selected,setSelected]=useState<number[]>([]),[source,setSource]=useState('laps'),family=sportFamily(detail);
 const detected=useMemo(()=>effortProfile(detail,family==='cycling'?'power':'speed').efforts.map((e:any)=>({duration:(e.end-e.start)*60,distance:family==='running'?e.mean*(e.end-e.start)*60:undefined,power:family==='cycling'?e.mean:undefined,pace:family==='running'?1000/e.mean:undefined,start:e.start})),[detail,family]);
 const laps=source==='laps'?(detail.laps??[]):detected;
 if(!['running','cycling'].includes(family))return null;
 const result=intervalConsistency(laps,selected,family);
 const outputs=result.valid?result.rows.map((r:any)=>family==='cycling'?r.power:1000/r.pace):[];
 const mean=outputs.length?outputs.reduce((a:number,b:number)=>a+b,0)/outputs.length:0;
 const variation=mean?Math.sqrt(outputs.reduce((n:number,v:number)=>n+(v-mean)**2,0)/outputs.length)/mean*100:null;
 const metric=result.changes[0],fade=result.valid&&metric.first&&metric.last?(family==='running'?metric.first/metric.last-1:metric.last/metric.first-1)*100:null;
 function suggest(){let best:number[]=[];laps.forEach((lap:any)=>{const d=(lap.summary??lap).duration;if(!(d>0))return;const group=laps.flatMap((l:any,i:number)=>{const s={...l,...l.summary};return s.duration>=d&&s.duration<=d*1.2&&((family==='cycling'?s.power:s.pace??(s.duration/s.distance*1000))>0)?[i]:[]});if(group.length>best.length)best=group});setSelected(best)}
 const format=(key:string,v:number|null)=>v===null?'—':key==='pace'?runningPace(v):`${Math.round(v)} ${key==='power'?'W':key==='heartrate'?'bpm':key==='stepLength'?'cm':family==='cycling'?'rpm':'spm'}`;
 return <details className="coach-intervals"><summary>Repeat consistency <span>Select work laps to compare ↗</span></summary><div className="tool-controls"><select aria-label="Repeat source" value={source} onChange={e=>{setSource(e.target.value);setSelected([])}}><option value="laps">Recorded laps · {detail.laps?.length??0}</option><option value="efforts">Detected efforts · {detected.length}</option></select><button onClick={suggest}>Suggest similar durations</button><button onClick={()=>setSelected([])}>Clear</button></div><p>Select only comparable work repeats. Leave warm-up, recovery and cool-down unchecked.</p><div className="coach-lap-picker">{laps.map((_:any,i:number)=><button key={i} aria-pressed={selected.includes(i)} onClick={()=>setSelected(v=>v.includes(i)?v.filter(j=>j!==i):[...v,i])}>{source==='laps'?'Lap':'Effort'} {i+1}</button>)}</div>{result.reason?<p>{result.reason}</p>:<><strong className={result.firstFade!==null?'trend-watch':'trend-steady'}>{result.firstFade!==null?`First output drop >3%: ${source==='laps'?'lap':'effort'} ${result.firstFade+1}`:'No output drop >3% in selected repeats'}</strong><div className="execution-kpis"><span>Output variation <b>{variation?.toFixed(1)}%</b></span><span>Finish vs start <b>{fade===null?'—':`${fade>=0?'↑':'↓'} ${Math.abs(fade).toFixed(1)}%`}</b></span></div><div className="repeat-bars" aria-label="Selected repeat output">{outputs.map((v:number,i:number)=><div key={i}><span style={{height:`${v/Math.max(...outputs)*65}px`}}/><small>{result.rows[i].index+1}</small><b>{family==='running'?runningPace(1000/v):`${Math.round(v)}W`}</b></div>)}</div><p>Variation is the coefficient of variation of output; lower means more even repeats. Suggestions group similar durations only—review the work/recovery selection.</p><div className="coach-grid">{result.changes.map(c=><div className="coach-tile" key={c.key}><span>{labels[c.key]}</span><strong>{format(c.key,c.first)} → {format(c.key,c.last)}</strong><TrendBadge trend={valueTrend(c.last,c.first,c.key==='pace'?'lower':c.key==='power'?'higher':'neutral',`last ${result.n} vs first ${result.n} selected laps`)}/></div>)}</div><p>Last {result.n} versus first {result.n} work laps. HR, cadence and step-length changes describe movement; their direction alone does not establish fatigue. Hills and intentional pacing can explain output changes.</p></>}</details>;
}
