"use client";
import {Component,type ReactNode} from 'react';
import {X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Skeleton} from '@/components/ui/skeleton';
export function LoadingState({label='Loading…',compact=false}:{label?:string;compact?:boolean}){return <div className={`loading-state${compact?' is-compact':''}`} role="status" aria-live="polite"><span className="loading-orbit" aria-hidden="true"/><span>{label}</span>{!compact&&<div className="loading-skeleton flex gap-2" aria-hidden="true"><Skeleton className="h-20 flex-1"/><Skeleton className="h-20 flex-1"/><Skeleton className="h-20 flex-1"/></div>}</div>}
export function DashboardLoading(){return <div className="dashboard-loading" role="status" aria-label="Loading your saved dashboard"><strong>sieste<span className="loading-orbit" aria-hidden="true"/></strong><p>Loading your saved dashboard…</p><div className="dashboard-skeleton" aria-hidden="true"><div className="skeleton-metrics"><Skeleton className="h-20"/><Skeleton className="h-20"/><Skeleton className="h-20"/></div><div className="skeleton-calendar"><Skeleton className="h-40"/><Skeleton className="h-40"/><Skeleton className="h-40"/></div><Skeleton className="h-28"/></div></div>}
export function WorkoutLoading({onClose}:{onClose:()=>void}){return <section className="modal workout-modal workout-loading" role="dialog" aria-modal="true" aria-label="Loading workout" onClick={e=>e.stopPropagation()}><Button variant="ghost" size="icon" className="close" autoFocus aria-label="Close workout" onClick={onClose}><X data-icon="inline-start"/></Button><LoadingState label="Opening workout…"/></section>}
export class FeatureBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div className="notice" role="alert">This view could not load. <button className="lab-button" onClick={()=>window.location.reload()}>Reload app</button></div>:this.props.children}}
