"use client";
import {useEffect,useState} from 'react';
type Measurements={weight:number|null;height:number|null;savedAt:string};
export default function ManualBody(){
 const [saved,setSaved]=useState<Measurements|null>(null),[weight,setWeight]=useState(''),[height,setHeight]=useState(''),[message,setMessage]=useState(''),[ready,setReady]=useState(false),[signedIn,setSignedIn]=useState(true),[busy,setBusy]=useState(false),[local,setLocal]=useState<Measurements|null>(null);
 useEffect(()=>{let active=true;fetch('/api/profile',{cache:'no-store'}).then(async response=>{const data:any=await response.json();if(!active)return;if(response.status===401){setSignedIn(false);return}if(!response.ok)throw new Error(data.error);if(data.profile){setSaved(data.profile);setWeight(data.profile.weight===null?'':String(data.profile.weight));setHeight(data.profile.height===null?'':String(data.profile.height))}}).catch(()=>{if(active)setMessage('Your saved measurements could not be loaded. Please reopen this view to retry.')}).finally(()=>{if(active)setReady(true)});try{const value=JSON.parse(localStorage.getItem('flemme.manual-body.v1')||'null');if(value&&(value.weight||value.height))setLocal(value)}catch{}return()=>{active=false}},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const w=weight.trim()===''?null:Number(weight),h=height.trim()===''?null:Number(height);if((w!==null&&(!Number.isFinite(w)||w<=0||w>1000))||(h!==null&&(!Number.isFinite(h)||h<=0||h>300))||(w===null&&h===null)){setMessage('Enter a valid weight in kg or height in cm.');return}setBusy(true);try{const response=await fetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({weight:w,height:h})});const data:any=await response.json();if(!response.ok)throw new Error(data.error);setSaved(data.profile);setMessage('Saved to your sieste account.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save. Your entries are still here; please retry.')}finally{setBusy(false)}}
 async function clear(){setBusy(true);try{const response=await fetch('/api/profile',{method:'DELETE'});const data:any=await response.json();if(!response.ok)throw new Error(data.error);setSaved(null);setWeight('');setHeight('');setMessage('Saved measurements cleared.')}catch(e){setMessage(e instanceof Error?e.message:'Could not clear measurements.')}finally{setBusy(false)}}
 return <section className="panel manual-body"><div className="panel-head"><div><h2>Your weight & height</h2><p>Optional measurements · saved to your athlete account</p></div></div>{!signedIn?<p className="lab-note"><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT to save your measurements.</a></p>:<><div className="manual-body-summary"><div><span>Weight</span><strong>{saved?.weight??'—'} <small>kg</small></strong></div><div><span>Height</span><strong>{saved?.height??'—'} <small>cm</small></strong></div></div><form onSubmit={save}><label>Weight (kg)<input type="number" inputMode="decimal" min="0.1" max="1000" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)} placeholder="e.g. 72.5" disabled={!ready||busy}/></label><label>Height (cm)<input type="number" inputMode="decimal" min="0.1" max="300" step="0.1" value={height} onChange={e=>setHeight(e.target.value)} placeholder="e.g. 178" disabled={!ready||busy}/></label><button className="lab-button" type="submit" disabled={!ready||busy}>{busy?'Saving…':'Save measurements'}</button><button className="lab-button subtle" type="button" disabled={!ready||!saved||busy} onClick={clear}>Clear saved values</button>{local&&<button type="button" className="lab-button subtle" disabled={!ready||busy} onClick={()=>{setWeight(local.weight==null?'':String(local.weight));setHeight(local.height==null?'':String(local.height));setMessage('Device measurements copied into the form. Save to add them to this account.')}}>Use measurements saved on this device</button>}</form><p className="manual-body-status" role="status">{message||(!ready?'Loading measurements…':saved?`Last saved ${new Date(saved.savedAt).toLocaleString()}`:'Enter either or both measurements.')}</p><p className="lab-note">Private to your signed-in sieste account and available across devices. Separate from Tredict records; these values are not sent to Tredict.</p></>}</section>
}
