type SparkProps={mode?:'line'|'bars';pointColors?:string[];dotted?:boolean;values:(number|null)[];label:string;positiveFrom?:number;negativeBelow?:number;amberBelow?:number;yellowBelow?:number;lightGreenFrom?:number;className?:string;color?:string;domain?:[number,number];reverse?:boolean;partial?:boolean[];pointLabels?:string[]};
// Shared compact geometry; daily totals use zero-based bars, physiology uses reading dots.
export default function MicroTrend({mode='line',pointColors=[],dotted=false,values,label,positiveFrom,negativeBelow,amberBelow,yellowBelow,lightGreenFrom,className='widget-spark',color,domain,reverse=false,partial=[],pointLabels=[]}:SparkProps){
 const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v),valid=values.filter(finite);
 if(!valid.length)return <span className={`${className} no-data`}>No readings</span>;
 const min=domain?.[0]??(mode==='bars'?0:valid.reduce((a,b)=>Math.min(a,b))),max=domain?.[1]??valid.reduce((a,b)=>Math.max(a,b)),x=(i:number)=>values.length===1?105:(mode==='bars'?12:5)+i*(mode==='bars'?186:200)/(values.length-1),y=(v:number)=>{const ratio=max===min?(mode==='bars'?0:.5):Math.max(0,Math.min(1,(v-min)/(max-min)));return 5+(reverse?ratio:1-ratio)*30};
 let connected=false;const path=values.map((v,i)=>{if(!finite(v)){connected=false;return ''}const command=connected?'L':'M';connected=true;return `${command}${x(i).toFixed(2)},${y(v).toFixed(2)}`}).join(' ');
 const stride=Math.max(1,Math.ceil(values.length/8));
 return <svg className={className} viewBox="0 0 210 40" preserveAspectRatio="none" style={color?{color}:undefined} role="img" aria-label={label}>
  {mode==='line'&&<path strokeDasharray={dotted?'2 3':undefined} d={path} fill="none" stroke="currentColor" strokeOpacity=".65" strokeWidth="1.25" strokeLinecap="round" strokeLinejoin="round"/>}
  {values.map((v,i)=>{if(!finite(v)||!(mode==='bars'||i%stride===0||partial[i]||i===values.length-1||!finite(values[i-1])||!finite(values[i+1])))return null;const tone=pointColors[i]??(negativeBelow!==undefined&&v<negativeBelow?'#dc4545':positiveFrom!==undefined&&v>=positiveFrom?'#16804a':amberBelow!==undefined&&v<amberBelow?'#c58a20':yellowBelow!==undefined&&v<yellowBelow?'#b29c38':lightGreenFrom!==undefined&&v>=lightGreenFrom?'#6ba985':amberBelow!==undefined?'#8893a3':negativeBelow!==undefined?'#c58a20':'currentColor');if(mode==='bars'){const height=Math.max(1,35-y(v)),width=Math.min(16,180/values.length);return <g key={i}><rect x={x(i)-width/2} y={35-height} width={width} height={height} rx="2" fill={tone} fillOpacity={partial[i]?.65:.9}>{pointLabels[i]&&<title>{pointLabels[i]}</title>}</rect>{i===values.length-1&&<path d={`M${x(i)-4},39h8`} stroke={tone} strokeWidth="1.5"/>}</g>}return <circle key={i} cx={x(i)} cy={y(v)} r="2.4" stroke={tone} strokeWidth="1" style={{fill:partial[i]?'white':tone}}>{pointLabels[i]&&<title>{pointLabels[i]}</title>}</circle>})}
 </svg>;
}
