"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {loadWorkout} from './workout-detail-cache';
import {localDate} from './week-overview';
import {sportFamily} from './sports';
import {routeGeometry} from './route-geometry';
import {shareFinishes,shareSolidColours,type ShareFinish} from './share-card-design';
import {MONTH_POSTER_ROUTES_PER_PAGE,monthRoutePoster,type PosterRoute} from './month-route-poster-data';
export default function MonthRoutePoster({activities,now,token,isDemo}:{activities:any[];now:Date;token:string;isDemo:boolean}){
 const [month,setMonth]=useState(localDate(now).slice(0,7)),[sport,setSport]=useState('running'),[page,setPage]=useState(0),[finish,setFinish]=useState<ShareFinish>('solid'),[ink,setInk]=useState('#ffffff'),[routes,setRoutes]=useState<PosterRoute[]>([]),[busy,setBusy]=useState(false),[done,setDone]=useState(0),[failed,setFailed]=useState(0),[missing,setMissing]=useState(0),[error,setError]=useState(''),[prepared,setPrepared]=useState<{source:string;file:File}|null>(null);const generation=useRef(0);
 const sessions=useMemo(()=>[...new Map(activities.filter(a=>sportFamily(a)===sport&&localDate(new Date(a.date)).slice(0,7)===month&&new Date(a.date)<=now).map(a=>[a.id,a])).values()].sort((a,b)=>a.date.localeCompare(b.date)),[activities,month,sport,now]);
 const pages=Math.max(1,Math.ceil(sessions.length/MONTH_POSTER_ROUTES_PER_PAGE)),batch=sessions.slice(page*MONTH_POSTER_ROUTES_PER_PAGE,(page+1)*MONTH_POSTER_ROUTES_PER_PAGE);
 useEffect(()=>{setPage(current=>Math.min(current,pages-1))},[pages]);
 useEffect(()=>{generation.current++;setRoutes([]);setDone(0);setFailed(0);setMissing(0);setBusy(false);setError('');return()=>{generation.current++}},[month,sport,page,token]);
 async function load(){const run=++generation.current;setBusy(true);setRoutes([]);setFailed(0);setMissing(0);setDone(0);setError('');let found:PosterRoute[]=[];for(let i=0;i<batch.length;i+=3){if(run!==generation.current)return;await Promise.all(batch.slice(i,i+3).map(async a=>{try{const d=isDemo?a:await loadWorkout(token,a.id);if(run!==generation.current)return;const s=d.seriesSampled?.data??{},g=routeGeometry(s.positionLat??[],s.positionLong??[]);if(g)found.push({id:a.id,date:new Date(a.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'}),distance:Number.isFinite(a.summary?.distance)?a.summary.distance:null,geometry:g});else setMissing(v=>v+1)}catch{if(run===generation.current)setFailed(v=>v+1)}finally{if(run===generation.current)setDone(v=>v+1)}}));if(run===generation.current)setRoutes([...found].sort((a,b)=>batch.findIndex(x=>x.id===a.id)-batch.findIndex(x=>x.id===b.id)))}if(run===generation.current)setBusy(false)}
 const title=`${new Date(month+'-01T12:00:00').toLocaleDateString('en-GB',{month:'long',year:'numeric'})} · ${sport}`;
 const svg=useMemo(()=>monthRoutePoster(routes,title,finish,ink,page+1,pages),[routes,title,finish,ink,page,pages]);
 const file=prepared?.source===svg?prepared.file:null;
 useEffect(()=>{let active=true;setPrepared(null);if(!routes.length||busy)return;const image=new Image();image.onload=()=>{if(!active)return;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');if(!ctx){setError('PNG export unavailable.');return}ctx.drawImage(image,0,0);canvas.toBlob(b=>{if(active&&b)setPrepared({source:svg,file:new File([b],`sieste-${month}-${sport}-${page+1}.png`,{type:'image/png'})})},'image/png')};image.onerror=()=>active&&setError('Could not render the poster.');image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);return()=>{active=false;image.onload=null}},[svg,busy,routes.length,month,sport,page]);
 function download(){if(!file)return;const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function share(){if(!file)return;try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file]});else download()}catch(e){if((e as Error).name!=='AbortError')setError('Use Download PNG to save the image.')}}
 return <section className="compact-tool"><header><h3>Monthly route poster</h3></header><div className="tool-controls"><label>Month<input aria-label="Poster month" type="month" max={localDate(now).slice(0,7)} value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setPage(0)}}}/></label><select aria-label="Poster sport" value={sport} onChange={e=>{setSport(e.target.value);setPage(0)}}><option value="running">Running</option><option value="cycling">Cycling</option><option value="hiking">Hiking</option><option value="walking">Walking</option></select></div><p>{sessions.length} synced sessions · {month===localDate(now).slice(0,7)?'month in progress':'loaded history only'}. Routes load on demand and reuse the activity cache.</p>{pages>1&&<div className="tool-controls"><button disabled={page===0} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page+1}/{pages} · up to {MONTH_POSTER_ROUTES_PER_PAGE} routes</span><button disabled={page+1>=pages} onClick={()=>setPage(v=>v+1)}>Next</button></div>}<button disabled={busy||!batch.length} onClick={load}>{busy?`Loading ${done}/${batch.length}…`:routes.length?'Reload routes':'Load routes for poster'}</button>{busy&&<button onClick={()=>{generation.current++;setBusy(false)}}>Stop</button>}<p role="status">{routes.length} routes shown · {missing} without GPS · {failed} failed{isDemo?' · illustrative demo; missing routes are not invented':''}</p>{routes.length>0&&<><div className="tool-controls"><select aria-label="Poster finish" value={finish} onChange={e=>setFinish(e.target.value as ShareFinish)}><option value="solid">Solid</option>{shareFinishes.map(f=><option key={f.key} value={f.key}>{f.name}</option>)}</select><select aria-label="Poster ink" value={ink} onChange={e=>setInk(e.target.value)}><option value="#ffffff">White</option><option value="#111111">Black</option>{shareSolidColours.map(colour=><option key={colour.color} value={colour.color}>{colour.name}</option>)}</select></div><img className="month-poster-preview" src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)} alt="Monthly route poster preview"/><div className="tool-controls"><button disabled={!file||busy} onClick={download}>Download transparent PNG</button><button disabled={!file||busy} onClick={share}>Share</button></div><p>1080 × 1350 · background stays transparent. Up to 12 larger route traces per page, with contrast edges for photos and videos. Each route is scaled independently. Totals include only the routes shown.</p></>}{error&&<p role="alert">{error}</p>}</section>;
}
