"use client";
import {useEffect,useMemo,useState} from 'react';
import RouteMap from './route-map';
import {editRoute,routeGpx,type Cut} from './route-tools-data';
export default function RouteTools({detail}:{detail:any}){
 const step=detail.seriesSampled?.sampleSize,lat=detail.seriesSampled?.data?.positionLat??[],total=(lat.length-1)*step;
 const [start,setStart]=useState(0),[end,setEnd]=useState(Number.isFinite(total)?total:0),[cuts,setCuts]=useState<Cut[]>([]),[cutStart,setCutStart]=useState(0),[cutEnd,setCutEnd]=useState(0);
 useEffect(()=>{setStart(0);setEnd(Number.isFinite(total)?total:0);setCuts([])},[detail.id,total]);
 const edited=useMemo(()=>editRoute(detail,start,end,cuts),[detail,start,end,cuts]);
 if(!(total>0)||!Number.isFinite(step))return <p>No timed GPS samples available to edit.</p>;
 const time=(n:number)=>`${Math.floor(n/60)}:${String(Math.round(n%60)).padStart(2,'0')}`;
 function download(){if(!edited?.geometry)return;const url=URL.createObjectURL(new Blob([routeGpx(edited.detail,edited.geometry)],{type:'application/gpx+xml'}));const a=document.createElement('a');a.href=url;a.download='sieste-edited-route.gpx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="compact-tool"><header><h3>Trim & clean route</h3><button onClick={()=>{setStart(0);setEnd(total);setCuts([])}}>Reset</button></header><p>Preview and export only. Original activity, laps and totals stay unchanged. Sample time may exclude watch pauses.</p><label>Start · {time(start)}<input aria-label="Trim route start" type="range" min={0} max={Math.max(0,end-step)} step={step} value={start} onChange={e=>setStart(+e.target.value)}/></label><label>End · {time(end)}<input aria-label="Trim route end" type="range" min={start+step} max={total} step={step} value={end} onChange={e=>setEnd(+e.target.value)}/></label><details><summary>Remove a middle section</summary><div className="tool-controls"><label>From minute<input type="number" min={0} max={total/60} step="0.1" value={cutStart} onChange={e=>setCutStart(+e.target.value)}/></label><label>To minute<input type="number" min={0} max={total/60} step="0.1" value={cutEnd} onChange={e=>setCutEnd(+e.target.value)}/></label><button disabled={cutEnd<=cutStart||cutStart<0||cutEnd*60>total} onClick={()=>setCuts(c=>[...c,{start:cutStart*60,end:cutEnd*60}])}>Exclude section</button></div>{cuts.map((c,i)=><button key={i} onClick={()=>setCuts(v=>v.filter((_,j)=>j!==i))}>{time(c.start)}–{time(c.end)} · undo ×</button>)}</details>{edited?.geometry?<><RouteMap detail={edited.detail}/><p>{edited.geometry.points.length} GPS points · {edited.geometry.segments.filter(s=>s.length>1).length} separate track segments. Recording breaks and excluded sections are never joined.</p><button onClick={download}>Download edited GPX</button></>:<p>No usable route remains. Reset or choose a wider range.</p>}<small>Export includes recorded elevation where supplied. No timestamps are invented from active sample time.</small></section>;
}
