"use client";
import {useState} from 'react';
import {classifySession,runningSignals,sessionLabels} from './session-intelligence-data';
import {ExpandButton} from './expansion';
import {paceLabel} from './activity-metrics';
import {sportFamily} from './sports';
const labels:Record<string,[string,string]>={cadence:['Cadence','steps/min'],stepLength:['Step length','cm'],groundContactTime:['Contact time','ms'],verticalOscillation:['Vertical bounce','cm']};
const number=(n:number|null)=>n===null?'—':n.toFixed(1);
export function RunningEvidence({signals}:{signals:ReturnType<typeof runningSignals>}){
 return <div className="coach-evidence"><p>{signals.reason??`${signals.pairs} matched minutes per half · ${paceLabel(signals.pace)} /km. First 10 minutes and final 2 minutes excluded.`}</p>{signals.drift!==null&&<p><strong>HR cost {signals.drift>=0?'+':''}{number(signals.drift)}%</strong> · {number(signals.earlyHR)} → {number(signals.lateHR)} bpm at similar pace.</p>}{signals.mechanics.length>0&&<div className="coach-table-scroll"><table><thead><tr><th>Mechanics</th><th>Earlier</th><th>Later</th><th>Change</th></tr></thead><tbody>{signals.mechanics.map(r=><tr key={r.key}><th>{labels[r.key][0]}</th><td>{number(r.early)}</td><td>{number(r.late)} {labels[r.key][1]}</td><td>{r.change>=0?'↑':'↓'} {Math.abs(r.change).toFixed(1)}%</td></tr>)}</tbody></table></div>}<p>Matched one-minute blocks: speed within 3%, gradient within 0.5 percentage points and between −2% and +2%. Pace variation within each block must be ≤5%; stops and sensor gaps are excluded. At least five pairs are required.</p><p>HR cost compares heart rate divided by speed, late versus early. Heat, hydration and sensor error can also change it. The amber &gt;5% and red &gt;10% highlights are review rules, not diagnoses. This is most useful for steady easy runs.</p><p>{signals.mechanics.some(r=>Math.abs(r.change)>3)?'A mechanics change is worth checking on another similar run. Compare the same shoes, terrain and device; review the later laps and how they felt before changing your technique.':'Use these readings as your personal reference. Repeat the same easy route to see whether the pattern persists.'} A higher cadence or shorter contact time is not automatically better. Watch measurements cannot establish posture, foot placement or injury risk.</p></div>
}
export default function SessionIntelligence({detail,onClassify}:{detail:any;onClassify?:(label:string|null)=>void}){
 const suggestion=detail.evidence?.classification??classifySession(detail),signals=detail.evidence?.insights??runningSignals(detail),[override,setOverride]=useState<string|null>(detail.sessionLabel??null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(value:string){setBusy(true);setError('');const label=value||null;try{if(!detail.demo){const r=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'classify',id:detail.id,label})});const result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Label could not be saved.')}setOverride(label);onClassify?.(label)}catch(e){setError(e instanceof Error?e.message:'Please retry.')}finally{setBusy(false)}}
 const drift=signals.drift,tone=drift===null?'missing':drift>10?'bad':drift>5?'watch':'neutral';
 return <section className="session-intelligence"><div className="session-type"><span><b>{override??suggestion.label}</b><small>{override?'Your label':`${suggestion.confidence} confidence · suggested`}</small></span><select aria-label="Correct session type" value={override??''} disabled={busy} onChange={e=>save(e.target.value)}><option value="">Auto label</option>{sessionLabels.map(label=><option key={label}>{label}</option>)}</select></div>{error&&<p role="alert" className="trend-bad">{error}</p>}<details className="session-method"><summary>Why this label?</summary><p>{suggestion.reason} {override?'Your correction takes priority.':'You can correct the suggestion.'} {detail.demo?'Demo changes stay in this view.':'Saved privately in sieste; the original COROS activity is unchanged.'}</p></details>{sportFamily(detail)==='running'&&<div className="coach-grid"><div className="coach-tile"><span>Steady-run durability</span><strong className={`trend-${tone}`}>{drift===null?'Not enough matched data':`${drift>0?'↑':drift<0?'↓':'→'} ${Math.abs(drift).toFixed(1)}% HR cost`}</strong><small>{signals.pairs?`${signals.pairs} matched minutes / half`:'Pace + HR + gradient needed'}</small><ExpandButton title="Durability · evidence"><RunningEvidence signals={signals}/></ExpandButton></div><div className="coach-tile"><span>Running mechanics</span><strong>{signals.mechanics.length?`${signals.mechanics.length} matched measures`:'Awaiting sensor coverage'}</strong><small>{signals.mechanics.find((r:any)=>r.key==='cadence')?`${number(signals.mechanics.find((r:any)=>r.key==='cadence').early)} → ${number(signals.mechanics.find((r:any)=>r.key==='cadence').late)} steps/min`:'Same pace · same gradient'}</small><ExpandButton title="Your running mechanics"><RunningEvidence signals={signals}/></ExpandButton></div></div>}</section>
}
