'use client';
import {useState} from 'react';
import {lateBedtime} from './sleep-insights-data';
import {sleepTiming,clockLabel} from './sleep-timing-data';
type Timing=ReturnType<typeof sleepTiming>;
export default function SleepWindowChart({data,onSelect}:{data:Timing;onSelect?:(date:string)=>void}){
 const [selected,setSelected]=useState('');
 const choose=(date:string)=>{setSelected(date);onSelect?.(date)};
 const rows=data.rows.map(r=>{let bed=r.bed===null?null:r.bed%1440,wake=r.wake===null?null:r.wake%1440;if(bed!==null&&bed<720)bed+=1440;if(wake!==null&&bed!==null&&wake<=bed)wake+=1440;return {...r,bed,wake}}),valid=rows.filter(r=>r.bed!==null&&r.wake!==null);
 if(!valid.length)return <p className="sleep-timing-empty">No recorded bedtime and wake-time pairs.</p>;
 const active=valid.find(r=>r.date===selected)??valid.at(-1)!;
 const lo=Math.floor(Math.min(1200,...valid.map(r=>r.bed!))/60)*60,hi=Math.ceil(Math.max(2160,...valid.map(r=>r.wake!))/60)*60,mid=1680,y=(v:number)=>16+(v-lo)/(hi-lo)*192,x=(i:number)=>42+(i+.5)*310/rows.length,bw=Math.min(24,210/rows.length);
 const path=(key:'bed'|'wake')=>{let connected=false;return rows.map((r,i)=>{if(r.bed===null||r.wake===null){connected=false;return ''}const command=connected?'L':'M';connected=true;return `${command}${x(i)},${y(r[key]!)}`}).join(' ')};
 return <div className="sleep-window-plot"><div className="sleep-window-readout" aria-live="polite"><b>{active.label}</b><span><i className="bed-key"/>Bed <strong>{clockLabel(active.bed!)}</strong></span><span><i className="wake-key"/>Wake <strong>{clockLabel(active.wake!)}</strong></span>{active.hours!==null&&<span>{Math.floor(active.hours)}h {Math.round(active.hours%1*60)}m asleep</span>}</div><svg viewBox="0 0 360 240" role="group" aria-label="Sleep windows: bedtime above the 04:00 divider and wake time below it. Dotted lines connect bedtime and wake time across nights."><rect x="42" y={y(1440)} width="310" height={Math.max(0,y(Math.min(hi,2160))-y(1440))} fill="#f6c45c" opacity=".06"/><line x1="42" x2="352" y1={y(1440)} y2={y(1440)} stroke="#c38a29" strokeDasharray="2 4"/>{Array.from({length:Math.floor((hi-lo)/120)+1},(_,i)=>lo+i*120).map(t=><g key={t}><line x1="42" x2="352" y1={y(t)} y2={y(t)} stroke="#edf0f4"/><text x="36" y={y(t)+4} textAnchor="end" fontSize="11" fill="#526078">{clockLabel(t)}</text></g>)}<line x1="42" x2="352" y1={y(mid)} y2={y(mid)} stroke="#a7b1c1" strokeDasharray="3 4"/>{rows.map((r,i)=>r.bed===null||r.wake===null?null:<g key={r.date} role="button" tabIndex={0} aria-pressed={active.date===r.date} aria-label={`${r.date}: ${clockLabel(r.bed)} to ${clockLabel(r.wake)}${lateBedtime(r.bed)?", after midnight":""}`} onClick={()=>choose(r.date)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();choose(r.date)}}}><rect x={x(i)-155/rows.length} y="9" width={310/rows.length} height="219" rx="5" fill={active.date===r.date?"#eef2ff":"transparent"}/><title>{r.date}: {clockLabel(r.bed)}–{clockLabel(r.wake)}{lateBedtime(r.bed)?' · after midnight cutoff':''} · {r.hours===null?'sleep duration unavailable':`${Math.floor(r.hours)}h ${Math.round(r.hours%1*60)}m asleep`}</title><rect x={x(i)-bw/2} y={y(r.bed)} width={bw} height={Math.max(0,y(Math.min(mid,r.wake))-y(r.bed))} fill="#a99bdf" rx="2"/><rect x={x(i)-bw/2} y={y(Math.max(mid,r.bed))} width={bw} height={Math.max(0,y(r.wake)-y(Math.max(mid,r.bed)))} fill="#e7b96f" rx="2"/></g>)}<path pointerEvents="none" d={path('bed')} stroke="#7560aa" strokeWidth="1.5" strokeDasharray="2 4" fill="none"/><path pointerEvents="none" d={path('wake')} stroke="#ae772d" strokeWidth="1.5" strokeDasharray="2 4" fill="none"/>{rows.map((r,i)=><g key={r.date} pointerEvents="none">{r.bed!==null&&r.wake!==null&&<><circle cx={x(i)} cy={y(r.bed)} r={lateBedtime(r.bed)?4:2.5} fill={lateBedtime(r.bed)?"#c58a20":"#7560aa"}/><circle cx={x(i)} cy={y(r.wake)} r="2.5" fill="#ae772d"/></>}{(rows.length<=7||i%4===0||i===rows.length-1)&&<text x={x(i)} y="230" textAnchor="middle" fill="#526078" fontSize="11">{r.label.slice(0,2)}</text>}</g>)}</svg><p className="sleep-timing-caption">Tap a night · window includes awake time</p></div>;
}
