'use client';
import {lateBedtime} from './sleep-insights-data';
import {sleepTiming,clockLabel} from './sleep-timing-data';
type Timing=ReturnType<typeof sleepTiming>;
export default function SleepWindowChart({data,onSelect}:{data:Timing;onSelect?:(date:string)=>void}){
 const rows=data.rows.map(r=>{let bed=r.bed===null?null:r.bed%1440,wake=r.wake===null?null:r.wake%1440;if(bed!==null&&bed<720)bed+=1440;if(wake!==null&&bed!==null&&wake<=bed)wake+=1440;return {...r,bed,wake}}),valid=rows.filter(r=>r.bed!==null&&r.wake!==null);
 if(!valid.length)return <p className="sleep-timing-empty">No recorded bedtime and wake-time pairs.</p>;
 const lo=Math.floor(Math.min(1200,...valid.map(r=>r.bed!))/60)*60,hi=Math.ceil(Math.max(2160,...valid.map(r=>r.wake!))/60)*60,mid=1680,y=(v:number)=>24+(v-lo)/(hi-lo)*230,x=(i:number)=>60+(i+.5)*560/rows.length,bw=Math.min(32,360/rows.length);
 const path=(key:'bed'|'wake')=>{let connected=false;return rows.map((r,i)=>{if(r.bed===null||r.wake===null){connected=false;return ''}const command=connected?'L':'M';connected=true;return `${command}${x(i)},${y(r[key]!)}`}).join(' ')};
 return <div className="sleep-window-plot"><svg viewBox="0 0 640 288" role="img" aria-label="Sleep windows: bedtime above the 04:00 divider and wake time below it. Dotted lines connect bedtime and wake time across nights."><rect x="50" y={y(1440)} width="580" height={Math.max(0,y(Math.min(hi,2160))-y(1440))} fill="#f6c45c" opacity=".06"/><line x1="50" x2="630" y1={y(1440)} y2={y(1440)} stroke="#c38a29" strokeDasharray="2 4"/>{Array.from({length:Math.floor((hi-lo)/120)+1},(_,i)=>lo+i*120).map(t=><g key={t}><line x1="50" x2="630" y1={y(t)} y2={y(t)} stroke="#edf0f4"/><text x="43" y={y(t)+4} textAnchor="end" fontSize="11" fill="#7b8795">{clockLabel(t)}</text></g>)}<line x1="50" x2="630" y1={y(mid)} y2={y(mid)} stroke="#a7b1c1" strokeDasharray="3 4"/>{rows.map((r,i)=>r.bed===null||r.wake===null?null:<g key={r.date} role={onSelect?"button":undefined} tabIndex={onSelect?0:undefined} aria-label={`${r.date}: ${clockLabel(r.bed)} to ${clockLabel(r.wake)}${lateBedtime(r.bed)?", after midnight":""}`} onClick={()=>onSelect?.(r.date)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect?.(r.date)}}}><title>{r.date}: {clockLabel(r.bed)}–{clockLabel(r.wake)}{lateBedtime(r.bed)?' · after midnight cutoff':''} · {r.hours===null?'sleep duration unavailable':`${Math.floor(r.hours)}h ${Math.round(r.hours%1*60)}m asleep`}</title><rect x={x(i)-bw/2} y={y(r.bed)} width={bw} height={Math.max(0,y(Math.min(mid,r.wake))-y(r.bed))} fill="#b6a8dc" rx="2"/><rect x={x(i)-bw/2} y={y(Math.max(mid,r.bed))} width={bw} height={Math.max(0,y(r.wake)-y(Math.max(mid,r.bed)))} fill="#edc98b" rx="2"/></g>)}<path d={path('bed')} stroke="#7560aa" strokeWidth="1.5" strokeDasharray="2 4" fill="none"/><path d={path('wake')} stroke="#ae772d" strokeWidth="1.5" strokeDasharray="2 4" fill="none"/>{rows.map((r,i)=><g key={r.date}>{r.bed!==null&&r.wake!==null&&<><circle cx={x(i)} cy={y(r.bed)} r={lateBedtime(r.bed)?4:2.5} fill={lateBedtime(r.bed)?"#c58a20":"#7560aa"}/><circle cx={x(i)} cy={y(r.wake)} r="2.5" fill="#ae772d"/></>}{(rows.length<=7||i%4===0||i===rows.length-1)&&<text x={x(i)} y="276" textAnchor="middle" fill="#7b8795" fontSize="11">{r.label}</text>}</g>)}</svg><p className="sleep-timing-caption">Bedtime → 04:00 → wake · includes awake time. Amber dots: after your midnight cutoff.</p></div>;
}
