'use client';
const SleepNightMatrix=lazy(()=>import('./sleep-night-matrix'));
import SleepTraining from './sleep-training';
import SleepVitals from './sleep-vitals';
import DeferredPanel from './deferred-panel';
const SleepTools=lazy(()=>import('./sleep-tools'));
const SleepInsights=lazy(()=>import('./sleep-insights'));
import RecordedIndicator from './recorded-indicator';
import SleepWindowChart from './sleep-window-chart';
import {useState,lazy,useMemo} from 'react';
import {Moon,Sunrise,ChevronLeft,ChevronRight} from 'lucide-react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,ReferenceArea,ReferenceLine,CartesianGrid} from 'recharts';
import type {AthleteData} from './analytics';
import {ExpandButton} from './expansion';
import {sleepTiming,clockLabel} from './sleep-timing-data';
import {shiftSleepDate} from './sleep-insights-data';
import {localDate} from './week-overview';
import {durationLabel} from './activity-metrics';
type Timing=ReturnType<typeof sleepTiming>;
function TimingChart({data,kind,expanded=false}:{data:Timing;kind:'bed'|'wake';expanded?:boolean}){const stats=data[kind],color=kind==='bed'?'#7160ab':'#c88b32';if(stats.mean===null)return <div className="sleep-timing-empty">No {kind==='bed'?'bedtimes':'wake times'} recorded in this period.</div>;return <div className={expanded?'sleep-clock-chart expanded':'sleep-clock-chart'}><ResponsiveContainer width="100%" height="100%"><LineChart data={data.rows} margin={{left:0,right:10,top:8,bottom:0}}><CartesianGrid vertical={false} stroke="#e9edf3" strokeDasharray="2 4"/><XAxis dataKey="label" tick={{fontSize:11,fill:'#7b8795'}} minTickGap={20} axisLine={false} tickLine={false}/><YAxis domain={[stats.mean-data.span/2,stats.mean+data.span/2]} tickFormatter={clockLabel} tick={{fontSize:11,fill:'#7b8795'}} tickCount={4} width={46} axisLine={false} tickLine={false}/><ReferenceArea y1={stats.mean-30} y2={stats.mean+30} fill={color} fillOpacity={.07} strokeOpacity={0}/><ReferenceLine y={stats.mean} stroke={color} strokeOpacity={.45} strokeDasharray="3 5"/><Tooltip contentStyle={{borderRadius:8,fontSize:12,border:'1px solid #e1e6ee'}} formatter={(v:any)=>[clockLabel(Number(v)),kind==='bed'?'Bedtime':'Wake time']} labelFormatter={(_,payload)=>payload?.[0]?.payload?.date??''}/><Line dataKey={kind} stroke={color} strokeWidth={1.35} strokeDasharray="2 4" dot={{r:2.5,fill:color,strokeWidth:0}} activeDot={{r:4}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}
export default function SleepPage({data,isDemo}:{data:AthleteData;isDemo:boolean}){const [selectedNight,setSelectedNight]=useState(''),[days,setDays]=useState(7),[offset,setOffset]=useState(0),today=isDemo?'2026-09-17':localDate(new Date()),end=shiftSleepDate(today,offset),timing=useMemo(()=>sleepTiming(data.extra?.coros?.sleepWindows??{},data.sleep,end,days),[data.extra?.coros?.sleepWindows,data.sleep,end,days]),latest=timing.rows.find(r=>r.date===selectedNight)??timing.latest,night=latest?data.extra?.coros?.sleepWindows?.[latest.date.replaceAll('-','')]??{}:{},stageRows=[['Deep',night.deepPercent,'#7862ac'],['Light',night.lightPercent,'#b7a5dc'],['REM',night.remPercent,'#719ec0']] as const;
 return <section className="sleep-page" aria-label="Sleep regularity"><header className="sleep-page-heading"><h1><Moon size={19}/> Sleep</h1><div role="group" aria-label="Sleep period">{[7,28].map(n=><button key={n} aria-pressed={days===n} onClick={()=>{setDays(n);setSelectedNight('')}}>{n} days</button>)}</div><label className="sleep-night-picker"><span className="sr-only">Explore a night</span> <select aria-label="Sleep night" value={latest?.date??''} onChange={e=>setSelectedNight(e.target.value)}>{[...timing.rows].reverse().filter(r=>r.hours!==null||r.bed!==null||r.score!==null).map(r=><option key={r.date} value={r.date}>{r.date}</option>)}</select></label></header><div className="sleep-period-nav"><button aria-label="Previous sleep week" onClick={()=>{setOffset(v=>v-days);setSelectedNight('')}}><ChevronLeft size={14}/></button><span aria-live="polite">{timing.rows[0]?.label} – {timing.rows.at(-1)?.label} · {end.slice(0,4)}</span><button aria-label="Next sleep week" disabled={offset===0} onClick={()=>{setOffset(v=>Math.min(0,v+days));setSelectedNight('')}}><ChevronRight size={14}/></button>{offset!==0&&<button className="sleep-back-current" onClick={()=>{setOffset(0);setSelectedNight('')}}>Latest</button>}</div><SleepVitals data={data} end={end} days={days} date={latest?.date??end}/><SleepTraining data={data} end={end} days={days}/><section className="sleep-regularity-widget"><header><h2>Your sleep windows</h2><span>{days} days · <span className="sleep-amber">● after 00:00</span></span><ExpandButton title="Sleep timing"><SleepWindowChart data={timing}/></ExpandButton></header>
 <SleepWindowChart data={timing} onSelect={setSelectedNight}/><DeferredPanel className="sleep-timing-lines" summary={<> Timing averages &amp; variation </>}>{()=> <>{(['bed','wake'] as const).map(kind=>{const stats=timing[kind],title=kind==='bed'?'Bedtime':'Wake time',Icon=kind==='bed'?Moon:Sunrise;return <article className={`sleep-clock-card sleep-clock-${kind}`} key={kind}><header><div><h3><Icon size={15}/>{title}</h3><strong>{stats.mean===null?'—':clockLabel(stats.mean)}<small>average</small></strong></div><div className="sleep-clock-variation"><b>{stats.sd===null?'—':`${Math.round(stats.sd)} min`}</b><span>timing variation</span></div><ExpandButton title={`${title} · regularity`}><TimingChart data={timing} kind={kind} expanded/><p>{stats.count}/{days} readings · {stats.near} within 30 minutes of this period’s average. Variation is the standard deviation of recorded clock times, adjusted across midnight.</p></ExpandButton></header><TimingChart data={timing} kind={kind}/><footer><span>{stats.count}/{days} nights recorded</span><span>{stats.mean!==null?`${stats.near}/${stats.count} within ±30 min`:'Awaiting COROS sleep times'}</span></footer></article>})}
 </>}</DeferredPanel></section>
 <DeferredPanel className="v2-explore" summary="Night-by-night signals · timing, awake time & changes">{()=> <><SleepNightMatrix data={data} end={end} days={days}/><SleepInsights data={data} end={end} days={days} selectedDate={latest?.date}/></>}</DeferredPanel>
 <DeferredPanel className="sleep-zones" summary={<> Sleep stages, score &amp; interruptions <small>· {latest?.label??'No night'}</small> </>}>{()=> <><p className="sleep-score-secondary">COROS sleep score <strong>{latest?.score??'—'}/100</strong></p><div className="sleep-stage-bars">{stageRows.map(([label,value,color])=><div key={label}><span>{label}</span><i><b style={{width:typeof value==='number'?Math.max(0,Math.min(100,value))+'%':'0%',background:color}}/></i><strong>{typeof value==='number'?value+'%':'—'}</strong><RecordedIndicator readings={Object.entries(data.extra?.coros?.sleepWindows??{}).filter(([date])=>!latest||date<=latest.date.replaceAll('-','')).map(([date,v]:any)=>({date,value:v[label==='Deep'?'deepPercent':label==='Light'?'lightPercent':'remPercent']}))}/></div>)}</div><div className="sleep-awake"><div><small>Time awake</small><strong>{typeof night.awakeMinutes==='number'?night.awakeMinutes+' min':'—'}</strong><RecordedIndicator readings={Object.entries(data.extra?.coros?.sleepWindows??{}).filter(([date])=>!latest||date<=latest.date.replaceAll('-','')).map(([date,v]:any)=>({date,value:v.awakeMinutes}))}/></div><div><small>Interruptions</small><span>Count not supplied</span></div><div><small>Naps</small><strong>{typeof night.napMinutes==='number'?night.napMinutes+' min':'—'}</strong></div></div><details className="sleep-timing-lines"><summary>About stages &amp; interruptions</summary><p>Stage changes show direction only: more is not automatically better. Awake time is a total; COROS does not supply interruption counts or timings here.</p></details></>}</DeferredPanel><DeferredPanel className="sleep-night-log" summary="Sleep tools · recovery, routine & planning"><SleepTools data={data} end={end} days={days}/></DeferredPanel><DeferredPanel className="sleep-night-log" summary={<> Night-by-night details </>}>{()=> <><div><table><thead><tr><th>Wake date</th><th>Bedtime</th><th>Wake</th><th>Sleep</th><th>Score</th></tr></thead><tbody>{[...timing.rows].reverse().map(r=><tr key={r.date}><th>{r.label}</th><td>{r.bed===null?'—':clockLabel(r.bed)}</td><td>{r.wake===null?'—':clockLabel(r.wake)}</td><td>{r.hours===null?'—':durationLabel(r.hours*3600)}</td><td>{r.score??'—'}</td></tr>)}</tbody></table></div></>}</DeferredPanel>
 <p className="sleep-page-note">COROS account local times · nights belong to their wake-up date. Sleep duration excludes awake time. Missing nights stay as gaps; timing is never inferred from duration.{isDemo?' Demo has no recorded sleep times.':''}</p></section>;
}
