"use client";
import type {AthleteData} from './analytics';
import {fatigueRecovery} from './fatigue-recovery-data';
import {useExpand} from './expansion';
import {sleepInsights} from './sleep-insights-data';
export function SleepSpark({values,color='#7862ac'}:{values:(number|null)[];color?:string}){const valid=values.filter((v):v is number=>v!==null&&Number.isFinite(v));if(!valid.length)return <span className="sleep-spark-empty">No readings</span>;const min=Math.min(...valid),max=Math.max(...valid),x=(i:number)=>3+i*114/Math.max(1,values.length-1),y=(v:number)=>25-(v-min)/Math.max(1,max-min)*20;let connected=false;const path=values.map((v,i)=>{if(v===null){connected=false;return ''}const c=connected?'L':'M';connected=true;return `${c}${x(i)},${y(v)}`}).join(' ');return <svg className="sleep-mini-spark" viewBox="0 0 120 30" aria-label="Recorded trend; missing nights are gaps"><path d={path} fill="none" stroke={color} strokeWidth="1.4" strokeDasharray="2 3"/>{values.map((v,i)=>v===null?null:<circle key={i} cx={x(i)} cy={y(v)} r="1.6" fill={color}/>)}</svg>}
const delta=(n:number|null)=>n===null?'—':Math.abs(n)<1?'→ 0m':`${n>0?'↑':'↓'} ${Math.round(Math.abs(n))}m`;
export default function SleepInsights({data,end,days,selectedDate}:{data:AthleteData;end:string;days:number;selectedDate?:string}){const d=sleepInsights(data,end,days,selectedDate),expand=useExpand(),loads=fatigueRecovery(data,new Date(end+'T23:59:59'),29),lastLoad=loads.at(-1)?.effort??null,priorLoads=loads.slice(0,-1).map(r=>r.effort).filter((v):v is number=>v!==null&&v>0).sort((a,b)=>a-b),heavy=d.recentStreak>=2&&lastLoad!==null&&priorLoads.length>=7&&lastLoad>priorLoads[Math.floor(priorLoads.length*.75)],detail=<div className="sleep-comparison-detail"><p>Night ending {d.latest?.date??end}. Arrows show duration, not a judgement of recovery.</p>{[...d.comparisons,d.year].map(c=><p key={c.label}><b>{delta(c.delta)}</b> {c.label} · {c.count}/{c.total} nights recorded{c.baseline!==null?` · average ${Math.round(c.baseline*60)} min`: ' · insufficient history'}</p>)}<p>7-day comparisons need 4 recorded nights; 30-day comparisons need 15. Missing nights are never counted as zero.</p></div>;
 return <><button className={`sleep-takeaway ${d.recentStreak>=2?'sleep-yellow':''}`} onClick={()=>expand.widget('Sleep pattern',<>{detail}<p>{d.longest} consecutive nights under 7h at most in this period. {d.late}/{d.timed} recorded bedtimes after your midnight cutoff. {heavy?' The waking-day training load is also above the upper quarter of your recorded active days over the prior 28 days.':''} These are sleep patterns, not an injury prediction.</p></>)}>{d.weeklyDelta===null?'Building your weekly comparison':`Sleeping ${Math.round(Math.abs(d.weeklyDelta))}m ${d.weeklyDelta>=0?'more':'less'} per night in this 7-day window`}<span> · {d.late} after midnight{d.recentStreak>=2?` · ${d.recentStreak} short nights in a row`:d.longest>=2?` · longest short-night streak: ${d.longest}`:''}{heavy?' · heavier training day':''} ↗</span></button><div className="sleep-consistency-strip">{(['bed','wake'] as const).map(k=>{const s=d.current[k],p=d.previous[k],diff=s.count>=4&&p.count>=4&&s.sd!==null&&p.sd!==null?s.sd-p.sd:null;return <button key={k} onClick={()=>expand.widget(`${k==='bed'?'Bedtime':'Wake-time'} consistency`,<><p>{s.sd===null?'Not enough readings':`${Math.round(s.sd)} minutes of timing variation`} · {s.count}/{days} nights.</p><p>{diff===null?'More history is needed for a comparison.':`${delta(diff)} variation versus the previous ${days} days. Lower means more consistent timing.`}</p><p>Variation measures the spread of clock times across midnight, independently of sleep duration.</p></>)}><small>{k==='bed'?'Bedtime':'Wake'} consistency</small><strong>{s.sd===null?'—':`${Math.round(s.sd)}m`} <em className={diff===null||Math.abs(diff)<5?'sleep-neutral':diff<0?'sleep-good':'sleep-yellow'}>{delta(diff)}</em></strong><SleepSpark values={d.current.rows.map(r=>r[k])} color={k==='bed'?'#7862ac':'#b47b2b'}/></button>})}</div></>;
}
