"use client";
import {useMemo} from 'react';
import {sleepToolsData} from './sleep-tools-data';
import {lateBedtime} from './sleep-insights-data';
import {clockLabel} from './sleep-timing-data';
import {useExpand} from './expansion';
export default function SleepNightMatrix({data,end,days}:{data:any;end:string;days:number}){
 const expand=useExpand(),rows=useMemo(()=>{const all=sleepToolsData(data,end,days+7,8).rows;return all.slice(7).map((r,i)=>{const prior=all.slice(i,i+7).map(v=>v.hours).filter((v):v is number=>v!==null),mean=prior.length>=4?prior.reduce((s,v)=>s+v,0)/prior.length:null;const delta=r.hours!==null&&mean!==null?Math.round((r.hours-mean)*60):null;const flags=[...(r.hours!==null&&r.hours<7?['Under 7h sleep']:[]),...(r.bed!==null&&lateBedtime(r.bed)?['Bedtime after midnight']:[]),...(r.awake!==null&&r.awake>30?['Over 30 min awake']:[])];return {...r,delta,flags,coverage:prior.length}})},[data,end,days]);
 return <section className="sleep-night-matrix" aria-label="Night-by-night sleep checks"><header><h2>What changed overnight?</h2><small>Tap a day</small></header><div className="sleep-training-scroll"><div className="sleep-training-matrix" style={{gridTemplateColumns:`44px repeat(${days},minmax(32px,1fr))`,minWidth:days>7?days*40+44:undefined}}><div className="sleep-training-labels">{['Day','Bed','Wake','Δ sleep','Awake','Checks'].map(t=><span key={t}>{t}</span>)}</div>{rows.map(r=><button key={r.date} aria-label={`Sleep checks for ${r.date}`} onClick={()=>expand.widget(`Sleep checks · ${r.label}`,<><p>Bed {r.bed===null?'—':clockLabel(r.bed)} · wake {r.wake===null?'—':clockLabel(r.wake)}</p><p>{r.delta===null?'Not enough sleep history':`${r.delta>0?'+':''}${r.delta} minutes of sleep versus the prior seven-day average (${r.coverage}/7 nights).`}</p><p>Awake: {r.awake===null?'not supplied':r.awake+' minutes'}. This is total awake time, not the number of interruptions.</p><p>{r.flags.length?r.flags.join(' · '):'No flags among available readings.'}</p><p>Checks use your midnight cutoff, under 7h sleep, and a sieste review threshold of over 30 minutes awake. Missing readings are unassessed; these flags do not diagnose poor recovery.</p></>)}><span>{r.label.slice(0,2)}</span><span className={r.bed!==null&&lateBedtime(r.bed)?'night-watch':''}>{r.bed===null?'—':clockLabel(r.bed)}</span><span>{r.wake===null?'—':clockLabel(r.wake)}</span><span>{r.delta===null?'—':`${r.delta>0?'↑':r.delta<0?'↓':'→'}${Math.abs(r.delta)}m`}</span><span className={r.awake!==null&&r.awake>30?'night-watch':''}>{r.awake===null?'—':r.awake+'m'}</span><span className={r.flags.length?'night-watch':r.hours!==null&&r.bed!==null&&r.awake!==null?'night-ok':'night-neutral'}>{r.flags.length?`${r.flags.length} !`:r.hours!==null&&r.bed!==null&&r.awake!==null?'✓':'—'}</span></button>)}</div></div><p>Δ sleep vs prior 7d · amber = review · — = incomplete checks</p></section>;
}
