"use client";
import {useState} from 'react';
import {LineChart,Line,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {comparisonPeriods,volume,difference,type Window} from './training-comparison';
import {sportFamily} from './sports';
import {useExpand} from './expansion';
import type {AthleteData} from './analytics';
const fmt=(v:number|null)=>v==null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:1});
const date=(d:Date)=>d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const range=(w:Window)=>{const end=new Date(w.end);end.setDate(end.getDate()-1);return `${date(w.start)} – ${date(end)}`};
export default function TrainingComparison({data,isDemo,syncing}:{data:AthleteData;isDemo:boolean;syncing:boolean}){
 const [sport,setSport]=useState('running'),[metric,setMetric]=useState('distance'),expand=useExpand(),now=isDemo?new Date('2026-09-17T23:59:59'):new Date(),periods=comparisonPeriods(now),unit=metric==='distance'?'km':metric==='duration'?'h':'sessions';
 const read=(w:Window)=>volume(data,w,now,sportFamily,sport,metric);
 const change=(a:ReturnType<typeof read>,b:ReturnType<typeof read>)=>{const d=difference(a,b);return !d?(!a.historyCovered||!b.historyCovered?'History not fully imported':`Missing ${metric} in ${a.missing+b.missing} sessions`):`${d.absolute===0?'→':d.absolute>0?'↑':'↓'} ${fmt(Math.abs(d.absolute))} ${unit}${d.percent==null?' · no % baseline':` (${d.percent>=0?'+':''}${fmt(d.percent)}%)`}`};
 function mini(p:typeof periods[number]){const points=Array.from({length:15},(_,i)=>{const pick=(w:Window)=>{const end=new Date(w.start.getTime()+(w.end.getTime()-w.start.getTime())*(i+1)/15);const r=read({start:w.start,end});return r.complete?r.value:null};return {a:pick(p.current),b:pick(p.year)}}),max=Math.max(1,...points.flatMap(p=>[p.a??0,p.b??0]));const path=(key:'a'|'b')=>points.map((p,i)=>p[key]==null?'':`${i===0||points[i-1][key]==null?'M':'L'}${4+i*20},${48-p[key]!/max*44}`).join(' ');return <div className="comparison-mini"><svg viewBox="0 0 290 52" preserveAspectRatio="none" role="img" aria-label="Cumulative volume: current period and same period last year"><path d={path('a')} fill="none" stroke="#2563eb" strokeWidth="1.25"/><path d={path('b')} fill="none" stroke="#a78bfa" strokeWidth="1.5" strokeDasharray="4 4"/>{points.map((p,i)=>i%2===0?<g key={i}>{p.a!==null&&<circle cx={4+i*20} cy={48-p.a/max*44} r="2" fill="#2563eb"/>}{p.b!==null&&<circle cx={4+i*20} cy={48-p.b/max*44} r="2" fill="#a78bfa"/>}</g>:null)}</svg><span>Cumulative · current ━ / last year ┄</span></div>}
 function open(p:typeof periods[number]){const count=Math.round((Date.UTC(p.current.end.getFullYear(),p.current.end.getMonth(),p.current.end.getDate())-Date.UTC(p.current.start.getFullYear(),p.current.start.getMonth(),p.current.start.getDate()))/86400000);const rows=Array.from({length:count},(_,i)=>{const end=new Date(p.current.start);end.setDate(end.getDate()+i+1);const beforeEnd=new Date(p.year.start);beforeEnd.setDate(beforeEnd.getDate()+i+1);if(beforeEnd>p.year.end)beforeEnd.setTime(p.year.end.getTime());const a=read({start:p.current.start,end}),b=read({start:p.year.start,end:beforeEnd});return {day:i+1,current:a.complete?a.value:null,lastYear:b.complete?b.value:null}});expand.widget(`${sport==='all'?'All training':sport==='cycling'?'Cycling':'Running'} · ${p.label}`,<div><p>{range(p.current)} compared with {range(p.year)}</p><h3>Cumulative {metric==='duration'?'training time':metric} ({unit})</h3><div style={{height:330,marginTop:20}}><ResponsiveContainer width="100%" height="100%"><LineChart data={rows}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" label={{value:'Day of period',position:'insideBottom',offset:-3}}/><YAxis/><Tooltip/><Line dataKey="current" name="Current period" stroke="#2563eb" dot={false} strokeWidth={2} isAnimationActive={false}/><Line dataKey="lastYear" name="Last year" stroke="#a78bfa" strokeDasharray="5 5" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p>Solid: current period · Dashed: last year. Today is partial. Lines require complete synced coverage. Year-to-date curves align by day number; leap years can differ by one day.</p></div>)}
 return <section className="training-comparison"><header><div><h2>Training over time</h2><span>Current volume, recent change & last year</span></div><div className="comparison-controls"><select aria-label="Comparison sport" value={sport} onChange={e=>setSport(e.target.value)}><option value="running">Running</option><option value="cycling">Cycling</option><option value="all">All training</option></select><select aria-label="Comparison metric" value={metric} onChange={e=>setMetric(e.target.value)}><option value="distance">Distance · km</option><option value="duration">Training time · h</option><option value="sessions">Sessions</option></select></div></header><div className="comparison-grid">{periods.map(p=>{const a=read(p.current),b=read(p.previous),y=read(p.year);return <button key={p.label} onClick={()=>open(p)} className="comparison-card"><span>{p.label} <small>↗</small></span><strong>{fmt(a.value)} <small>{unit}</small></strong><small>{range(p.current)}{!a.complete?' · partial':''}</small>{p.label!=='Year to date'&&<div><span>Previous {p.label==='Last 7 days'?'7':'30'} days <b>{fmt(b.value)} {unit}</b></span><em className={(difference(a,b)?.absolute??0)<0?'stat-decrease':undefined}>{change(a,b)}</em></div>}<div><span>{p.label==='Year to date'?'Last year to same date':'Same period last year'} <b>{fmt(y.value)} {unit}</b></span><em className={(difference(a,y)?.absolute??0)<0?'stat-decrease':undefined}>{change(a,y)}</em></div>{mini(p)}</button>})}</div>{periods.some(p=>!read(p.year).complete)&&<p className="comparison-notice">{syncing?'Importing training history… Your saved dashboard remains available.':periods.some(p=>!read(p.year).historyCovered)?'Older history is not fully imported. Use Sync now to retry.':'Some sessions have missing measurements; change calculations are unavailable.'}</p>}<details><summary>Dates & calculation</summary><p>Last 7 and 30 days include today; previous periods have the same number of days. Last-year rolling periods end on the same calendar date last year. Year to date runs from 1 January to today, compared with 1 January to the same date last year (29 February becomes 28 February). Today is partial; past periods include the full final day. Totals cover synced activities, not planned workouts. Missing metrics and incomplete imports suppress change calculations. A higher volume is not automatically better training.</p><p>{data.historyStart?`Imported range starts ${date(new Date(data.historyStart))}. `:''}{isDemo?'Illustrative demo history.':`Last synced: ${data.syncedAt?new Date(data.syncedAt).toLocaleString():'unknown'}.`} Selecting a card expands its cumulative comparison without leaving Home.</p></details></section>
}
