"use client";
import {useState} from 'react';
import TrendBadge from './trend-badge';
import {valueTrend} from './trend';
import {useExpand} from './expansion';
import {trainingSnapshot} from './training-snapshot-data';
import type {AthleteData} from './analytics';
const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:1});
const time=(s:number)=>s<60?`${Math.round(s)}s`:`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`;
const ink=['#7dd3fc','#3b82f6','#8b5cf6','#f59e0b','#ef4444'];
export default function TrainingSnapshot({data,now}:{data:AthleteData;now:Date}){
 const [sport,setSport]=useState('running'),expand=useExpand(),s=trainingSnapshot(data,now,sport);
 const delta=(n:number|null,unit:string)=>n===null?'Comparison unavailable':`${n>0?'+':''}${fmt(n)}${unit?' '+unit:''}`;
 function open(){expand.widget('Last 7 days · training',<div className="snapshot-detail"><p>All synced sessions from {s.period.current.start.toLocaleDateString('en-GB')} through today. Today is partial; the preceding seven days are complete calendar days.</p><table><thead><tr><th>Metric</th><th>Last 7 days</th><th>Previous 7 days</th><th>Change</th></tr></thead><tbody>{s.metrics.map(m=><tr key={m.key}><th>{m.label}</th><td>{fmt(m.value)} {m.unit}{m.partial?' · partial':''}</td><td>{fmt(m.previous)} {m.unit}</td><td>{delta(m.change,m.unit)}</td></tr>)}</tbody></table><p>Distance includes running and cycling. Time and session count include all sports. Load is recorded load, not TSS. Comparisons are withheld when history or measurements are incomplete. More load is not automatically better.</p><h3>{sport==='running'?'Running':'Cycling'} · recorded HR zones</h3>{s.total>0?<div className="snapshot-zone-detail">{s.zones.map((v,i)=><div key={i}><span>Zone {i+1}</span><meter min={0} max={s.total} value={v}/><strong>{time(v)} · {Math.round(v/s.total*100)}%</strong></div>)}</div>:<p>No recorded zone times available.</p>}<p>{s.covered}/{s.sessions} sessions have recorded HR-zone time. Percentages use recorded time only. These are recorded zone indices; BPM boundaries can differ across sessions when your settings change. Running and cycling are kept separate.</p></div>)}
 return <section className="training-snapshot home-surface" aria-label="Seven-day training snapshot"><header><h2>Last 7 days</h2><span>Δ vs previous 7d</span></header><button className="snapshot-totals" onClick={open} aria-label="Expand weekly totals and previous-week comparison">{s.metrics.map(m=><span key={m.key}><span>{m.label}</span><strong>{fmt(m.value)} <small>{m.unit}</small>{m.partial&&<sup title="Incomplete coverage">*</sup>}</strong><TrendBadge trend={valueTrend(m.change===null?null:m.value,m.previous,'neutral','previous 7 days')}/></span>)}</button><div className="snapshot-zone-heading"><h3>HR-zone time</h3><select aria-label="HR-zone sport" value={sport} onChange={e=>setSport(e.target.value)}><option value="running">Running</option><option value="cycling">Cycling</option></select></div><button className="snapshot-zones" onClick={open} aria-label="Expand recorded heart-rate zone distribution">{s.total>0?<><div className="snapshot-zone-bar">{s.zones.map((v,i)=><span key={i} style={{flexGrow:v,background:ink[Math.min(i,ink.length-1)]}} title={`Z${i+1}: ${time(v)} (${Math.round(v/s.total*100)}%)`}/>)}</div><div className="snapshot-zone-legend">{s.zones.map((v,i)=><span key={i}><b>Z{i+1}</b> {time(v)} <small>{Math.round(v/s.total*100)}%</small></span>)}</div></>:<span className="snapshot-empty">{s.sessions?'HR-zone times not supplied yet':'No sessions in this period'}</span>}<small>{s.covered}/{s.sessions} sessions · recorded HR only ↗</small></button><footer>{fmt(s.calories)} kcal · from synced sessions <span>({s.calorieCoverage}/{s.sessionCount}) · today partial</span></footer></section>
}
