"use client";
import {useMemo,useState} from 'react';
import RecoveryResponse from './recovery-response';
import {localDate} from './week-overview';
import CoachAdditions from './coach-additions';
import EffortProgress from './effort-progress';
import type {AthleteData,Workout} from './analytics';
import {useExpand} from './expansion';
import {efficiencyInsight} from './training-insights-data';
import {sleepTrainingPattern,planComparison,progressRecords,uniqueWorkouts} from './training-coach-data';
import {runningPace,sportName} from './sports';
import {valueTrend} from './trend';
import TrendBadge from './trend-badge';
const n=(v:number|null|undefined,d=0)=>v==null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:d});
const date=(v:string)=>new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short'});
export default function TrainingCoach({data,now,onSelect,isDemo,analyzing,historyAnalysis,onAnalyze,analysisError}:{analysisError:string;isDemo:boolean;analyzing:boolean;historyAnalysis:boolean;onAnalyze:()=>void;data:AthleteData;now:Date;onSelect:(a:Workout)=>void}){
 const [family,setFamily]=useState<'running'|'cycling'>('running'),expand=useExpand(),day=now.toDateString();
 const {efficiency,sleep,plan,records}=useMemo(()=>({efficiency:efficiencyInsight({...data,activities:uniqueWorkouts(data.activities)},now,family),sleep:sleepTrainingPattern(data,now),plan:planComparison(data,now),records:progressRecords(data,now,family)}),[data,day,family]);
 const formatEffort=(v:number)=>family==='running'?runningPace(1000/v):`${n(v)} W`;
 const openSession=(a:Workout)=>{expand.close();onSelect(a)};
 function openEfficiency(){expand.widget(`${sportName(family)} · comparable sessions`,<div className="coach-evidence"><h3>{efficiency.title}</h3><p>Last 28 days versus the preceding 56 days. At least 3 unique pairs; the headline uses the median change in speed or measured power.</p><p>Same sport subtype, 20–120 minutes, duration within 20% and HR within 5 bpm. Labelled intervals, tempo and races are excluded. Available ascent/km and temperature must be similar. Missing terrain, wind or workout purpose can still affect the result; these are steady-session candidates, not confirmed easy runs.</p><div className="coach-table-scroll"><table><thead><tr><th>Recent / earlier</th><th>HR</th><th>{family==='running'?'Pace':'Power'}</th><th>Change</th></tr></thead><tbody>{efficiency.pairs.map(p=><tr key={p.recent.id}><td>{[p.recent,p.prior].map(a=><button className="coach-session" key={a.id} onClick={()=>openSession(a)}>{date(a.date)} ↗</button>)}</td><td>{[p.recent,p.prior].map(a=><div key={a.id}>{n(a.summary?.heartrate)} bpm</div>)}</td><td>{[p.recent,p.prior].map(a=><div key={a.id}>{family==='running'?runningPace(a.summary!.duration/a.summary!.distance*1000):`${n(a.summary!.power)} W`}</div>)}</td><td><TrendBadge trend={valueTrend(100+p.change,100,'higher','matched earlier session')}/><small>{p.terrainMatched?'Terrain checked':'Terrain unknown'} · {p.temperatureMatched?'Temperature checked':'Temperature unknown'}</small></td></tr>)}</tbody></table></div>{!efficiency.pairs.length&&<p>No suitable pair yet. Cycling comparisons require recorded power.</p>}</div>)}
 function openSleep(){expand.widget('Sleep alongside training',<div className="coach-evidence"><h3 className={`trend-${sleep.tone}`}>{sleep.title}</h3><p>A review flag appears after two consecutive recorded nights below 6 hours when training is also recorded on the second day. The headline covers the latest 3 calendar days; the table shows 14 days.</p><p>This fixed short-sleep flag is a transparent sieste review rule, not a validated injury prediction or a personal sleep requirement. Review session intensity and how you feel before adding training. <a href="https://pubmed.ncbi.nlm.nih.gov/33144349/" target="_blank" rel="noreferrer">Athlete sleep consensus ↗</a></p><div className="coach-table-scroll"><table><thead><tr><th>Date</th><th>Sleep</th><th>Sessions</th><th>Training</th><th>Effort</th></tr></thead><tbody>{[...sleep.rows].reverse().map(r=><tr key={r.iso}><td>{date(r.iso+'T12:00:00')}</td><td className={r.repeated&&r.sessions?'trend-bad':r.short?'trend-watch':''}>{n(r.sleep,1)} h {r.repeated&&r.sessions?'!':''}</td><td>{r.sessions}</td><td>{n(r.minutes)} min</td><td>{n(r.effort)}</td></tr>)}</tbody></table></div><p>Sleep uses the provider’s date; training uses your local date. Load uses recorded provider scores, not TSS. Missing nights remain unknown.</p></div>)}
 function openRecords(){expand.widget(`${sportName(family)} · best recorded efforts`,<EffortProgress data={data} now={now} family={family} onSelect={openSession}/>)}
 function openPlan(){expand.widget('Plan versus completed training',<div className="coach-evidence"><p>Week of {date(plan.startKey+'T12:00:00')}. Compare Monday through yesterday; today and future plans are excluded from the difference.</p><p>These are sport-level duration totals, not automatic claims that a particular planned workout was completed. Intensity and workout structure still matter.</p><div className="coach-table-scroll"><table><thead><tr><th>Sport</th><th>Planned</th><th>Recorded</th><th>Difference</th><th>Full-week plan</th></tr></thead><tbody>{plan.rows.map(r=><tr key={r.family}><th>{sportName(r.family)}</th><td>{n(r.planned)} min</td><td>{n(r.actual)} min</td><td><TrendBadge trend={valueTrend(r.actual,r.planned,'neutral','plan through yesterday')}/></td><td>{n(r.weekPlan)} min</td></tr>)}</tbody></table></div>{!plan.available&&<p>Structured plan comparisons are unavailable from this connection.</p>}{!plan.covered&&<p>Recorded totals are withheld because this week’s activity history is incomplete.</p>}{!plan.duePlans&&<p>No running, cycling or strength plans due before today were supplied.</p>}<p>Only explicitly structured plans can be compared. Unsaved sieste planner drafts are not included.</p></div>)}
 const effort=records.rows.find(r=>r.seconds===1200),actual=plan.rows.every(r=>r.actual!==null)?plan.rows.reduce((s,r)=>s+r.actual!,0):null,planned=plan.rows.every(r=>r.planned!==null)?plan.rows.reduce((s,r)=>s+r.planned!,0):null;
 return <section className="coach-panel" aria-label="Training insights"><header><h2>Training insights</h2><select aria-label="Training insight sport" value={family} onChange={e=>setFamily(e.target.value as typeof family)}><option value="running">Running</option><option value="cycling">Cycling</option></select></header><div className="coach-grid">
 <button className="coach-tile" onClick={openEfficiency}><span>Same effort, better output? ↗</span><strong className={efficiency.change===null?'trend-missing':efficiency.change===0?'trend-steady':efficiency.change<0?(efficiency.change<=-10?'trend-bad':'trend-watch'):'trend-good'}>{efficiency.change===null?'Building comparison':`${efficiency.change===0?'→':efficiency.change>0?'↑':'↓'} ${Math.abs(efficiency.change).toFixed(1)}% ${family==='running'?'speed':'power'}`}</strong><small>{efficiency.pairs.length} matched pairs · 28 vs prior 56 days</small></button>
 <button className="coach-tile" onClick={openRecords}><span>Best efforts · 1 / 5 / 20 / 60 min ↗</span><strong>{effort?.recent?formatEffort(effort.recent.value):'No 20-min effort yet'}</strong><TrendBadge trend={valueTrend(effort?.recent?.value,effort?.prior?.value,'higher','previous 28 days')}/><small>20-min best · {records.analyzed}/{records.eligible} sessions processed</small></button>
 <button className="coach-tile" onClick={openSleep}><span>Sleep × training ↗</span><strong className={`trend-${sleep.tone}`}>{sleep.title}</strong><small>{sleep.short} short nights · {sleep.coverage}/3 nights recorded</small></button>
 {data.provider!=='coros'&&<button className="coach-tile" onClick={openPlan}><span>Plan versus done · this week ↗</span><strong>{!plan.available?'No plans supplied':!plan.duePlans?'No plans due yet':`${n(actual)} / ${n(planned)} min`}</strong><small>Through yesterday · run, ride & strength</small>{plan.duePlans>0&&<TrendBadge trend={valueTrend(actual,planned,'neutral','plan through yesterday')}/>}</button>}
 </div><RecoveryResponse data={data} end={localDate(now)}/><CoachAdditions data={data} now={now} family={family} onSelect={onSelect}/>{!isDemo&&<div className="coach-analysis"><span>{data.activities.filter(a=>a.evidence?.insightVersion===2).length}/{data.activities.length} sessions processed{analyzing?' · analysing…':''}</span><button onClick={onAnalyze}>{historyAnalysis?'Pause history analysis':'Analyse older sessions'}</button></div>}{analysisError&&<p className="coach-foot trend-watch" role="status">{analysisError} Toggle history analysis off and on to retry.</p>}<p className="coach-foot">Tap for evidence · comparisons describe recorded training, not guaranteed fitness changes.</p></section>;
}
