"use client";
import {useState} from 'react';
import {Activity,ChartNoAxesCombined,HeartPulse,ArrowUpRight} from 'lucide-react';
import {useExpand} from './expansion';
import {recoveryInsight,workloadInsight,efficiencyInsight} from './training-insights-data';
import type {AthleteData} from './analytics';
import {runningPace} from './sports';
const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:1});
export default function TrainingInsights({data,now}:{data:AthleteData;now:Date}){
 const [sport,setSport]=useState<'running'|'cycling'>('running'),expand=useExpand(),recovery=recoveryInsight(data,now),load=workloadInsight(data,now),progress=efficiencyInsight(data,now,sport);
 function openRecovery(){expand.widget('Recovery · what changed',<div className="insight-evidence"><p>Sleep is assessed against your 8-hour target. HRV and resting HR are assessed against your own earlier readings.</p>{recovery.readings.map(r=><div key={r.metric} className={`expanded-assessment status-${r.tone}`}><strong>{r.metric} · {r.label}</strong><p>{r.reason}</p></div>)}<p>Use this as a prompt to review how you feel alongside your training plan. These signals do not diagnose injury or determine whether it is safe to train.</p></div>)}
 function openLoad(){const max=Math.max(1,...load.weeks.map(w=>w.load??0));expand.widget('Load · recent pattern',<div className="insight-evidence"><p>Five non-overlapping seven-day periods, ending yesterday. Excluding today avoids comparing a partial day with a full one.</p><div className="insight-load-chart">{load.weeks.map((w,i)=><div key={w.from}><strong>{fmt(w.load)}</strong><div><span style={{height:w.load===null?'0':`${w.load/max*100}%`,background:i===4?'#2563eb':'#bdcaf5'}}/></div><small>{w.from}<br/>{w.to}</small></div>)}</div><table><thead><tr><th>Period</th><th>Effort</th><th>Hours</th><th>Sessions</th></tr></thead><tbody>{load.weeks.map(w=><tr key={w.from}><th>{w.label}</th><td>{fmt(w.load)}</td><td>{fmt(w.hours)}</td><td>{w.sessions}</td></tr>)}</tbody></table><p>Earlier weekly mean: {fmt(load.baseline)} effort. Load uses recorded daily load, not TSS. Missing effort on a workout day suppresses the comparison; imported rest days count as zero. A rise or fall describes your workload, not injury risk or training quality.</p></div>)}
 function openProgress(){expand.widget(`${sport==='running'?'Running':'Cycling'} · matched sessions`,<div className="insight-evidence"><h3>{progress.title}</h3><p>Recent sessions from the last 28 days are paired with unique sessions from the preceding 56 days. Matches require the same sport subtype, average HR within 5 bpm, and duration within 20%. Sessions last 20–120 minutes; workouts labelled track, interval, tempo or race are excluded.</p><p>Where both records include them, ascent per kilometre must be within 5 m/km and temperature within 5°C. Missing conditions do not prove similar terrain or weather. Wind, stops, sensor changes and effort within the session can still affect the result. This is an observed comparison, not a confirmed fitness gain.</p><p>{progress.pairs.length} matched pairs from {progress.recentCount} recent and {progress.priorCount} earlier eligible sessions. At least three pairs are required; the headline is their median change in {sport==='running'?'speed':'power'}.</p><div className="table-wrap"><table><thead><tr><th>Recent / earlier</th><th>HR</th><th>{sport==='running'?'Pace':'Power'}</th><th>Change</th></tr></thead><tbody>{progress.pairs.map(p=><tr key={p.recent.id}><td>{[p.recent,p.prior].map(a=><div key={a.id}>{new Date(a.date).toLocaleDateString('en-GB')} · {a.title||sport}</div>)}<small>{p.terrainMatched?'Ascent matched':'Terrain unavailable'} · {p.temperatureMatched?'Temperature matched':'Temperature unavailable'}</small></td><td>{[p.recent,p.prior].map(a=><div key={a.id}>{Math.round(a.summary!.heartrate)} bpm</div>)}</td><td>{[p.recent,p.prior].map(a=><div key={a.id}>{sport==='running'?runningPace(a.summary!.duration/a.summary!.distance*1000):`${fmt(a.summary!.power)} W`}</div>)}</td><td>{p.change>=0?'+':''}{fmt(p.change)}%</td></tr>)}</tbody></table></div>{!progress.pairs.length&&<p>No sufficiently similar pairs yet. Cycling requires measured power; speed alone is too dependent on terrain and wind.</p>}</div>)}
 return <section className="training-insights" aria-label="Training insights"><header><h2>What’s changing</h2><span>Your baseline. Your evidence.</span><select aria-label="Progress insight sport" value={sport} onChange={e=>setSport(e.target.value as 'running'|'cycling')}><option value="running">Running progress</option><option value="cycling">Cycling progress</option></select></header><div className="insight-grid"><button className={`insight-card insight-recovery status-${recovery.tone}`} onClick={openRecovery}><span><HeartPulse size={16}/> Recovery <ArrowUpRight size={14}/></span><strong>{recovery.title}</strong><p>{recovery.summary}</p></button><button className="insight-card insight-load" onClick={openLoad}><span><Activity size={16}/> Workload <ArrowUpRight size={14}/></span><strong>{load.title}</strong><p>{load.summary}</p></button><button className="insight-card insight-progress" onClick={openProgress}><span><ChartNoAxesCombined size={16}/> {sport==='running'?'Running':'Cycling'} progress <ArrowUpRight size={14}/></span><strong>{progress.title}</strong><p>{progress.summary}</p></button></div></section>
}
