"use client";
import {useMemo,useState} from 'react';
import type {AthleteData,Workout} from './analytics';
import {planLinks,equipmentHistory,factorComparison,pedalComparison,conditionsComparison,comparableSessions} from './tredict-opportunities-data';
import {sportFamily,runningPace} from './sports';
import {useExpand} from './expansion';
const n=(v:number|null|undefined,d=1)=>v==null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:d});
const date=(v:string)=>new Date(v).toLocaleDateString('en-GB',{day:'numeric',month:'short'});
const delta=(v:number|null,b:number|null,unit='')=>v===null||b===null?'Need 3 comparable sessions':`${v>b?'↑':v<b?'↓':'→'} ${n(Math.abs(v-b),2)}${unit} vs matched baseline`;
const method='Earlier 84 days; same sport subtype, ≥20 minutes, duration within 20%, climbing per km within 5 m/km. Running speed within 5%; cycling mean power within 10%. Up to five earlier sessions; three required for a baseline. Weather, equipment and recording devices may differ.';
function SensorReview({current,history,onSelect,mode}:{current:Workout;history:Workout[];onSelect:(a:Workout)=>void;mode:'pedals'|'factors'|'conditions'}){
 const bands=Object.keys(current.evidence?.sensors?.powerBands??{}).filter(b=>Object.keys(current.evidence!.sensors!.powerBands[b]).some(k=>/Balance|Torque|Smoothness/.test(k))).sort((a,b)=>+a-+b),[band,setBand]=useState(bands[0]??'');
 const peers=comparableSessions(current,history),factors=factorComparison(current,history),pedals=pedalComparison(current,history,band),conditions=conditionsComparison(current,history);
 return <div className="coach-evidence"><button className="coach-session" onClick={()=>onSelect(current)}>{date(current.date)} · {current.title??current.sportType} ↗</button>{mode==='pedals'?<><label className="coach-period">Compare at power <select value={band} onChange={e=>setBand(e.target.value)} disabled={!bands.length}>{bands.length?bands.map(b=><option key={b} value={b}>{b}–{+b+24} W</option>):<option>No pedal samples</option>}</select></label><p>At least 2 minutes of readings per 25 W band. Balance is the recorded left-side share; 50/50 is not a universal target. Smoothness and torque effectiveness are sensor measures, not a technique grade.</p><div className="coach-table-scroll"><table><thead><tr><th>Measure</th><th>This ride</th><th>Earlier baseline</th><th>Coverage</th></tr></thead><tbody>{pedals.map(r=><tr key={r.key}><th>{r.label}</th><td>{n(r.value)} %</td><td>{n(r.baseline)} %<small>{delta(r.value,r.baseline,' pp')}</small></td><td>{n(r.seconds/60)} min · {r.used.length} earlier rides</td></tr>)}</tbody></table></div></>:mode==='factors'?<><p>Tredict’s recorded efficiency factors. Arrows show numerical direction; a change alone does not establish better economy or fitness.</p><div className="coach-table-scroll"><table><thead><tr><th>Factor</th><th>This run</th><th>Earlier baseline</th><th>Change</th></tr></thead><tbody>{factors.map(r=><tr key={r.key}><th>{r.label}</th><td>{n(r.value,3)}</td><td>{n(r.baseline,3)}<small>{r.used.length} comparable runs</small></td><td>{r.change===null?'—':`${r.change>0?'↑':r.change<0?'↓':'→'} ${n(Math.abs(r.change))}%`}</td></tr>)}</tbody></table></div></>:<><p>Conditions may help explain a harder session, but do not establish the cause. Air power is a sensor estimate of aerodynamic demand, not wind speed or a measured headwind. Watch temperature may be affected by body heat.</p><div className="coach-table-scroll"><table><thead><tr><th>Measure</th><th>This session</th><th>Earlier baseline</th><th>Difference</th></tr></thead><tbody>{conditions.map(r=><tr key={r.key}><th>{r.key==='temperature'?'Temperature':r.key==='airPower'?'Air power':'Form power'}</th><td>{n(r.value)} {r.key==='temperature'?'°C':'W'}</td><td>{n(r.baseline)}<small>{r.used.length} comparable sessions</small></td><td>{delta(r.value,r.baseline,r.key==='temperature'?'°C':' W')}</td></tr>)}</tbody></table></div><p>Sensor averages require ≥80% duration coverage. Form power describes non-forward power estimated by the sensor; a lower value is not automatically better.</p></>}<p>{method}</p><details><summary>Comparison sessions ({peers.length})</summary>{peers.map(a=><button className="coach-session" key={a.id} onClick={()=>onSelect(a)}>{date(a.date)} · {a.title??a.sportType} ↗</button>)}</details></div>
}
function EquipmentReview({data,now,onSelect}:{data:AthleteData;now:Date;onSelect:(a:Workout)=>void}){
 const rows=equipmentHistory(data,now),[chosen,setChosen]=useState(rows[0]?.equipment.id??''),row=rows.find(r=>r.equipment.id===chosen),runs=row?.sessions.filter(a=>sportFamily(a)==='running').sort((a,b)=>Date.parse(b.date)-Date.parse(a.date))??[],current=runs[0],peers=current?comparableSessions(current,data.activities):[];
 return <div className="coach-evidence"><p>Usage below comes from linked, synced sessions. Removed sessions are excluded; missing distance stays unknown. It does not imply that equipment needs replacing.</p><div className="coach-table-scroll"><table><thead><tr><th>Equipment</th><th>Sessions</th><th>Recorded usage</th></tr></thead><tbody>{rows.map(r=><tr key={r.equipment.id}><td><button className="coach-session" onClick={()=>setChosen(r.equipment.id)}>{r.equipment.name??r.equipment.id}{chosen===r.equipment.id?' ✓':''}</button></td><td>{r.sessions.length}</td><td>{n(r.km)} km · {n(r.minutes===null?null:r.minutes/60)} h{r.missing>0&&<small>{r.missing} missing distances</small>}</td></tr>)}</tbody></table></div>{!rows.length&&<p>No equipment assignments supplied by Tredict.</p>}{row&&<><h3>{row.equipment.name??'Equipment'} · linked sessions</h3>{current&&<><p>Latest run compared with similar earlier runs. Shoe assignments are shown so you can compare context; this is not a causal shoe ranking.</p><div className="coach-table-scroll"><table><thead><tr><th>Run</th><th>Shoes</th><th>Pace / HR</th></tr></thead><tbody>{[current,...peers].map(a=><tr key={a.id}><td><button className="coach-session" onClick={()=>onSelect(a)}>{date(a.date)} ↗</button></td><td>{rows.filter(r=>r.equipment.type==='shoes'&&r.sessions.some(s=>s.id===a.id)).map(r=>r.equipment.name).join(', ')||'Not supplied'}</td><td>{runningPace(a.summary!.duration/a.summary!.distance*1000)} · {n(a.summary?.heartrate,0)} bpm</td></tr>)}</tbody></table></div><p>{method}</p></>}{row.sessions.slice(0,30).map(a=><button className="coach-session" key={a.id} onClick={()=>onSelect(a)}>{date(a.date)} · {a.title??a.sportType} · {n(a.summary?.distance==null?null:a.summary.distance/1000)} km ↗</button>)}{row.sessions.length>30&&<p>Showing the latest 30 linked sessions.</p>}{!row.sessions.length&&<p>Equipment exists, but no assigned sessions are in the synced history yet.</p>}</>}</div>
}
export default function TredictOpportunities({data,now,onSelect}:{data:AthleteData;now:Date;onSelect:(a:Workout)=>void}){
 const expand=useExpand(),day=now.toDateString(),model=useMemo(()=>{const acts=[...data.activities].filter(a=>new Date(a.date)<=now).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));return {plans:planLinks(data,now),equipment:equipmentHistory(data,now),run:acts.find(a=>sportFamily(a)==='running'),ride:acts.find(a=>sportFamily(a)==='cycling'),latest:acts.find(a=>['running','cycling'].includes(sportFamily(a))) }},[data,day]);
 const open=(a:Workout)=>{expand.close();onSelect(a)},linked=model.plans.rows.filter(r=>r.done).length;
 function showPlans(){expand.widget('Planned → completed · last 28 days',<div className="coach-evidence"><p>Only Tredict’s explicit completion link confirms a match. No link does not mean you skipped the session. Duration differences do not confirm whether intensity or intervals matched the plan.</p>{!model.plans.available?<p>Planned training was not supplied. Sync to retry.</p>:!model.plans.rows.length?<p>No plans in the last 28 days.</p>:<div className="coach-table-scroll"><table><thead><tr><th>Plan</th><th>Completion</th><th>Planned / done</th></tr></thead><tbody>{model.plans.rows.map(r=><tr key={r.plan.id}><td>{date(r.plan.date)}<small>{r.plan.title??r.plan.sportType}</small></td><td>{r.done?<button className="coach-session" onClick={()=>open(r.done!)}>{date(r.done.date)} · Linked ↗</button>:r.status}</td><td>{n(r.planned===null?null:r.planned/60)} / {n(r.actual===null?null:r.actual/60)} min<small>{r.actual!==null&&r.planned!==null?`${r.actual>r.planned?'↑':r.actual<r.planned?'↓':'→'} ${n(Math.abs(r.actual-r.planned)/60)} min`:''}</small></td></tr>)}</tbody></table></div>}</div>)}
 function showSensor(mode:'pedals'|'factors'|'conditions'){const a=mode==='pedals'?model.ride:mode==='factors'?model.run:model.latest;expand.widget(mode==='pedals'?'Cycling · pedal metrics':mode==='factors'?'Running · efficiency factors':'Conditions · session context',a?<SensorReview current={a} history={data.activities} onSelect={open} mode={mode}/>:<p>No {mode==='pedals'?'cycling':mode==='factors'?'running':'endurance'} session synced yet.</p>)}
 return <section className="coach-panel opportunity-panel"><header><h2>Equipment & sensors</h2></header><div className="coach-grid"><button className="coach-tile" onClick={showPlans}><span>Plan → completed ↗</span><strong>{linked}/{model.plans.rows.length} linked</strong><small>Last 28 days · explicit Tredict links</small></button><button className="coach-tile" onClick={()=>expand.widget('Equipment · usage & comparisons',<EquipmentReview data={data} now={now} onSelect={open}/>)}><span>Equipment ↗</span><strong>{model.equipment.length} items</strong><small>Shoes, bikes & linked sessions</small></button><button className="coach-tile" onClick={()=>showSensor('pedals')}><span>Pedalling ↗</span><strong>{model.ride?.evidence?.sensors&&Object.values(model.ride.evidence.sensors.powerBands).some(b=>Object.keys(b).some(k=>/Balance|Torque|Smoothness/.test(k)))?'Compare power bands':'Awaiting pedal sensors'}</strong><small>{model.ride?date(model.ride.date):'No ride'} · balance, torque & smoothness</small></button><button className="coach-tile" onClick={()=>showSensor('factors')}><span>Running efficiency ↗</span><strong>{model.run?`${factorComparison(model.run,data.activities).filter(r=>r.value!==null).length} recorded factors`:'No run yet'}</strong><small>Effectiveness, aerobic & form factors</small></button><button className="coach-tile" onClick={()=>showSensor('conditions')}><span>Conditions ↗</span><strong>{model.latest?`${conditionsComparison(model.latest,data.activities).filter(r=>r.value!==null).length} measures available`:'No session yet'}</strong><small>Temperature · air & form power</small></button></div></section>
}
