import {Shirt} from 'lucide-react';
import {rainSignal,weatherTime,type WeatherHour} from './weather-recon-data';
export function outfitAdvice(hours:WeatherHour[]){
 const temps=hours.map(h=>h.temperature).filter((v):v is number=>typeof v==='number'&&Number.isFinite(v));
 if(!temps.length)return null;
 const low=Math.min(...temps),high=Math.max(...temps),rain=hours.some(h=>rainSignal(h)),windy=hours.some(h=>(h.wind??0)>=20||(h.gust??0)>=35);
 const top=low>=20?'Short-sleeve jersey':low>=15?'Short-sleeve jersey + arm warmers':low>=10?'Long-sleeve jersey + light base layer':low>=5?'Thermal long-sleeve jersey + base layer':'Thermal jersey + winter jacket';
 const legs=low>=15?'Bib shorts':low>=10?'Bib shorts + knee or leg warmers':'Thermal bib tights';
 const extras:string[]=[];if(rain)extras.push('Pack a breathable waterproof jacket; rain is possible during this window.');else if(windy||low<15)extras.push('Take a packable windproof gilet for exposed roads and descents.');if(low<10)extras.push('Full-finger gloves and overshoes; add a thin cap below 5°C.');if(high-low>=5)extras.push('Temperatures change by 5°C or more: choose removable layers.');if(high>=25)extras.push('Choose a breathable jersey and sun protection.');
 return {low,high,top,legs,extras,incomplete:temps.length!==hours.length||hours.some(h=>h.wind===null||h.rainChance===null)};
}
export default function WeatherOutfit({hours,timezone,best}:{hours:WeatherHour[];timezone:string;best:boolean}){const advice=outfitAdvice(hours);return <section className="weather-outfit"><header><h2><Shirt size={16}/>What to wear</h2><small>{best?'Best riding window':'Selected day · daylight hours'}</small></header>{advice?<><p className="weather-outfit-basis">{weatherTime(hours[0].time,timezone)}–{weatherTime(hours.at(-1)!.time+3600,timezone)} · {Math.round(advice.low)}–{Math.round(advice.high)}°C</p><div><article><small>Top</small><strong>{advice.top}</strong></article><article><small>Legs</small><strong>{advice.legs}</strong></article></div>{advice.extras.length>0&&<ul>{advice.extras.map(t=><li key={t}>{t}</li>)}</ul>}<small>{advice.incomplete?'Some forecast values are missing. ':''}Start with the coolest hour; adjust for your cold tolerance and effort. Clothing does not change the riding-condition rating.</small><details><summary>How these tips work</summary><p>sieste’s temperature bands are practical starting points, not personal comfort predictions. Wind and rain add an outer layer; no wind-chill temperature is inferred from riding speed. Layering guidance: <a href="https://www.cyclinguk.org/cycle/wear-cycling-winter-cold" target="_blank" rel="noreferrer">Cycling UK</a>.</p></details></>:<p>Not enough daylight temperature data for an outfit suggestion. Choose another day.</p>}</section>}
