"use client";
import WeatherOutfit from './weather-outfit';
import WeatherCondition from './weather-condition';
import {LoadingState} from './loading-state';
import {useEffect,useMemo,useRef,useState,memo} from 'react';
import {Bike,CloudSun,CloudRain,Wind,Thermometer,MapPin,LocateFixed,Search,RefreshCw,Sunrise,Sunset,ArrowUp,ArrowRight,Pencil} from 'lucide-react';
import {ridingOutlook,rainSignal,bestRidingWindow,windBearing,defaultWeatherRules,parseWeather,ridingWindows,weatherAssessment,weatherDay,weatherLabels,weatherTime,type WeatherRules} from './weather-recon-data';
type Place={name:string;latitude:number;longitude:number};
type Forecast=ReturnType<typeof parseWeather>&{fetchedAt:number;key:string};
const forecastCache=new Map<string,Forecast>();
const storageKey='sieste-weather-location-v1';
const value=(n:number|null,suffix='')=>n===null?'—':`${Math.round(n)}${suffix}`;
function WeatherRecon({active=true}:{active?:boolean}){
 const [editing,setEditing]=useState(false),[allHours,setAllHours]=useState(false);
 const [place,setPlace]=useState<Place|null>(null),[query,setQuery]=useState(''),[results,setResults]=useState<Place[]>([]),[searching,setSearching]=useState(false),[locating,setLocating]=useState(false),[searchError,setSearchError]=useState('');
 const [forecast,setForecast]=useState<Forecast|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[now,setNow]=useState(Date.now()),[day,setDay]=useState(''),[duration,setDuration]=useState(3),[rules,setRules]=useState<WeatherRules>(defaultWeatherRules);
 const searchAbort=useRef<AbortController|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;try{const p=JSON.parse(localStorage.getItem(storageKey)||'null');if(p&&typeof p.name==='string'&&Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)&&Math.abs(p.latitude)<=90&&Math.abs(p.longitude)<=180)setPlace(p)}catch{}return()=>{mounted.current=false;searchAbort.current?.abort()}},[]);
 function choose(p:Place){setPlace(p);setEditing(false);setResults([]);setQuery('');setSearchError('');setDay('');try{localStorage.setItem(storageKey,JSON.stringify(p))}catch{}}
 async function search(e:React.FormEvent){e.preventDefault();if(query.trim().length<2)return;searchAbort.current?.abort();const controller=new AbortController();searchAbort.current=controller;setSearching(true);setSearchError('');setResults([]);try{const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query.trim())}&count=5&language=en&format=json`,{signal:controller.signal});if(!response.ok)throw new Error();const json=await response.json() as {results?:any[]};const choices=(json.results??[]).filter((p:any)=>Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)).map((p:any)=>({name:[p.name,p.admin1,p.country].filter(Boolean).join(', '),latitude:p.latitude,longitude:p.longitude}));setResults(choices);if(!choices.length)setSearchError('No locations found. Try a nearby town.')}catch(e){if(!controller.signal.aborted)setSearchError('Location search is unavailable. Please retry.')}finally{if(!controller.signal.aborted)setSearching(false)}}
 function locate(){if(!navigator.geolocation){setSearchError('Location is unavailable in this browser. Search for a town instead.');return}setLocating(true);setSearchError('');navigator.geolocation.getCurrentPosition(p=>{if(!mounted.current)return;choose({name:'My area',latitude:Math.round(p.coords.latitude*100)/100,longitude:Math.round(p.coords.longitude*100)/100});setLocating(false)},()=>{if(!mounted.current)return;setLocating(false);setSearchError('Could not access your location. Search for a town instead.')},{enableHighAccuracy:false,timeout:12000,maximumAge:300000})}
 useEffect(()=>{if(!place||!active)return;const controller=new AbortController(),key=`${place.latitude},${place.longitude}`;setError('');setForecast(forecastCache.get(key)??null);setLoading(true);const load=async()=>{const cached=forecastCache.get(key);if(cached&&Date.now()-cached.fetchedAt<900000){setForecast(cached);setLoading(false);return}try{const params=new URLSearchParams({latitude:String(place.latitude),longitude:String(place.longitude),hourly:'temperature_2m,precipitation_probability,precipitation,wind_speed_10m,wind_gusts_10m,wind_direction_10m,weather_code,is_day',daily:'sunrise,sunset',forecast_days:'10',timeformat:'unixtime',timezone:'auto',wind_speed_unit:'kmh',temperature_unit:'celsius',precipitation_unit:'mm'});const response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`,{signal:controller.signal});if(!response.ok)throw new Error('The weather service is unavailable. Please retry shortly.');const data={...parseWeather(await response.json()),fetchedAt:Date.now(),key};if(!controller.signal.aborted){forecastCache.set(key,data);setForecast(data);setNow(Date.now())}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not load the forecast.')}finally{if(!controller.signal.aborted)setLoading(false)}};void load();return()=>controller.abort()},[place,refresh,active]);
 useEffect(()=>{if(!active)return;const tick=()=>{if(document.visibilityState==='visible'){setNow(Date.now());if(forecast&&Date.now()-forecast.fetchedAt>=900000)setRefresh(r=>r+1)}};tick();const timer=setInterval(tick,60000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick)}},[forecast,active]);
 const tz=forecast?.timezone??'UTC';const hours=useMemo(()=>forecast?.hours.filter(h=>h.time>=Math.floor(now/3600000)*3600)??[],[forecast,now]);const days=Array.from(new Set(hours.map(h=>weatherDay(h.time,tz))));const selectedDay=days.includes(day)?day:days[0];const dayHours=hours.filter(h=>weatherDay(h.time,tz)===selectedDay);const allWindows=useMemo(()=>ridingWindows(hours,duration,rules,now/1000),[hours,duration,rules,now]);const windows=allWindows.filter(w=>weatherDay(w.start,tz)===selectedDay);const best=bestRidingWindow(windows);const sun=forecast?.sun.find(s=>s.date===selectedDay);const focus=best?Math.max(0,dayHours.findIndex(h=>h.time===best.start)-1):0;const visibleHours=allHours?dayHours:dayHours.slice(Math.min(focus,Math.max(0,dayHours.length-6)),Math.min(focus,Math.max(0,dayHours.length-6))+6);const outlook=ridingOutlook(dayHours,best,rules);const current=outlook?.hour;const assessment=outlook?.assessment;const currentBearing=current?windBearing(current.direction):null;const currentRain=outlook?.rain;const temperature=outlook&&outlook.minTemp!==null&&current?.temperature!==null?Math.round(outlook.minTemp)===Math.round(current!.temperature!)?value(current!.temperature,'°'):`${Math.round(outlook.minTemp)}–${Math.round(current!.temperature!)}°`:'—';
 function reload(){if(place)forecastCache.delete(`${place.latitude},${place.longitude}`);setRefresh(r=>r+1)}
 return <section className="weather-recon" aria-label="Cycling weather recon">
  <header className="weather-title"><div><CloudSun size={22}/><h1>Weather recon</h1></div><span>10-day cycling outlook</span></header>
  <form className="weather-search" hidden={!!place&&!editing} onSubmit={search}><label className="weather-search-field"><Search size={16}/><input aria-label="Find a town or city" placeholder="Town or city" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/></label><button type="submit" disabled={searching||query.trim().length<2}>{searching?'Finding…':'Find'}</button><button type="button" onClick={locate} disabled={locating} aria-label="Use my location" title="Use my location"><LocateFixed size={17}/></button></form>
  {results.length>0&&<div className="weather-results">{results.map(p=><button key={`${p.latitude},${p.longitude}`} onClick={()=>choose(p)}><MapPin size={15}/>{p.name}</button>)}</div>}
  {searchError&&<p className="weather-error" role="alert">{searchError}</p>}
  {!place&&<div className="weather-empty"><Bike size={28}/><h2>Find your next riding window</h2><p>Choose a town to compare temperature, rain and wind for the next 10 days.</p><small>“Use my location” shares approximate coordinates with Open-Meteo. Your selection is remembered on this device.</small></div>}
  {place&&<div className="weather-location"><span><MapPin size={14}/>{place.name}</span><button onClick={()=>setEditing(v=>!v)} aria-label="Change weather location" title="Change location"><Pencil size={14}/></button><button onClick={reload} disabled={loading} aria-label="Refresh forecast" title="Refresh forecast"><RefreshCw size={15} className={loading?'spinning':''}/></button></div>}
  {loading&&!forecast&&<LoadingState label="Checking the forecast…"/>}
  {error&&<div className="weather-error" role="alert">{error} <button onClick={reload}>Retry</button></div>}
  {forecast&&current&&assessment&&<>
   <div className="weather-day-controls"><div className="weather-days" role="group" aria-label="Forecast day, scroll for all 10 days">{days.map((d,i)=><button key={d} aria-pressed={selectedDay===d} onClick={e=>{setDay(d);setAllHours(false);e.currentTarget.scrollIntoView({block:'nearest',inline:'nearest',behavior:'smooth'})}}>{i===0?'Today':i===1?'Tomorrow':new Date(hours.find(h=>weatherDay(h.time,tz)===d)!.time*1000).toLocaleDateString('en-GB',{timeZone:tz,weekday:'short',day:'numeric'})}</button>)}</div><label>Ride <select aria-label="Ride duration" value={duration} onChange={e=>setDuration(Number(e.target.value))}>{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n} value={n}>{n}h</option>)}</select></label></div>
   <div className={`weather-window ${best?'has-window':''}`}><Bike size={21}/><div><small>{best?'Best riding window':'No matching window'}</small><strong>{best?<>{weatherTime(best.start,tz)} <ArrowRight size={15}/> {weatherTime(best.end,tz)}</>:`No full ${duration}h window fits your limits`}</strong><span>{best?'Lowest rain risk, then lighter wind & gusts.':'Review the hourly outlook below or choose another day.'}</span></div></div>
   <div className={`weather-now weather-${assessment.grade}`}><div className="weather-now-title"><b title={assessment.reasons.join(' · ')}><i className="weather-dot"/>{weatherLabels[assessment.grade]}</b><small>{outlook?.scope} · {weatherTime(outlook!.start,tz)}–{weatherTime(outlook!.end,tz)}</small></div>{assessment.grade!=='good'&&<p>{assessment.reasons.join(' · ')}</p>}<div className="weather-metrics"><div><Thermometer size={14}/><strong>{temperature}</strong></div><div className={currentRain?`weather-rain-${currentRain}`:''} title={currentRain==='forecast'?'Rain forecast':currentRain==='possible'?'Rain possible':'Maximum hourly rain probability'}><CloudRain size={14}/><strong>{value(current.rainChance,'%')}</strong><small>max</small>{currentRain&&<span>{currentRain==='forecast'?'Rain forecast':'Rain possible'}</span>}</div><div title={currentBearing?`Peak wind from ${currentBearing.from}; arrow points where it blows`:'Wind direction unavailable'}>{currentBearing&&current.wind!==null&&current.wind>0?<ArrowUp size={16} style={{transform:`rotate(${currentBearing.towards}deg)`}} aria-label={`Wind from ${currentBearing.from}`}/>:<Wind size={14}/>}<strong>{value(current.wind)}<small> km/h max</small></strong><span>{current.wind===0?'Calm':currentBearing?`From ${currentBearing.from}`:'Wind'} · gust {value(current.gust)}</span></div></div></div>
   <div className="weather-sun-times"><span title="Sunrise"><Sunrise size={15}/><span>Sunrise</span><b>{sun?.sunrise?weatherTime(sun.sunrise,tz):'—'}</b></span><span title="Sunset"><Sunset size={15}/><span>Sunset</span><b>{sun?.sunset?weatherTime(sun.sunset,tz):'—'}</b></span>{best&&<span className="weather-best-key"><Bike size={13}/>Best ride</span>}</div>
   <div className="weather-hour-table" role="table" aria-label="Hourly cycling conditions"><div className="weather-hour-head" role="row"><span role="columnheader">Time</span><span role="columnheader">°C</span><span role="columnheader">Rain</span><span role="columnheader">Wind <small>km/h</small></span><span role="columnheader">Gust <small>km/h</small></span></div>{visibleHours.map(h=>{const a=weatherAssessment(h,rules),rain=rainSignal(h),bearing=windBearing(h.direction),riding=!!best&&h.time>=best.start&&h.time<best.end;const event=sun?.sunrise&&sun.sunrise>=h.time&&sun.sunrise<h.time+3600?'sunrise':sun?.sunset&&sun.sunset>=h.time&&sun.sunset<h.time+3600?'sunset':null;return <div role="row" className={`weather-hour weather-${a.grade}${riding?' is-best-ride':''}${rain?' has-rain-'+rain:''}`} key={h.time} aria-label={`${weatherTime(h.time,tz)}${riding?' · best riding window':''}`} title={`${weatherLabels[a.grade]}: ${a.reasons.join(', ')}`}><span role="cell"><i className="weather-dot" aria-label={weatherLabels[a.grade]}/>{weatherTime(h.time,tz)}{event==='sunrise'?<Sunrise size={12} aria-label="Sunrise this hour"/>:event==='sunset'?<Sunset size={12} aria-label="Sunset this hour"/>:best?.start===h.time?<Bike size={12} aria-label="Best ride starts"/>:null}</span><span role="cell" className="weather-temperature-cell"><WeatherCondition code={h.code} daylight={h.daylight}/>{value(h.temperature,'°')}</span><span role="cell" className={rain?`weather-rain-cell weather-rain-${rain}`:''} title={rain==='forecast'?'Rain forecast':rain==='possible'?'Rain possible':'Rain probability'}><span>{rain&&<CloudRain size={12} aria-label={rain==='forecast'?'Rain forecast':'Rain possible'}/>}{value(h.rainChance,'%')}</span><small>{h.rain===null?'—':h.rain.toFixed(1)} mm</small></span><span role="cell" className="weather-wind-cell" title={bearing?`Wind from ${bearing.from}; arrow points where it blows`:'Wind direction unavailable'}><span>{bearing&&h.wind!==null&&h.wind>0?<ArrowUp size={13} style={{transform:`rotate(${bearing.towards}deg)`}} aria-label={`Wind from ${bearing.from}`}/>:null}{value(h.wind)}</span><small>{h.wind===0?'Calm':bearing?`from ${bearing.from}`:'—'}</small></span><span role="cell">{value(h.gust)}</span></div>})}</div>
   <div className="weather-hours-footer"><span>Arrows show where wind blows</span>{dayHours.length>6&&<button aria-expanded={allHours} onClick={()=>setAllHours(v=>!v)}>{allHours?'Compact view':`All ${dayHours.length} hours`}</button>}</div>
   <div className="weather-legend"><span className="weather-good"><i className="weather-dot"/>Favourable</span><span className="weather-mixed"><i className="weather-dot"/>Mixed</span><span className="weather-poor"><i className="weather-dot"/>Poor</span><span className="weather-unknown"><i className="weather-dot"/>Unknown</span></div>
  </>}
  {place&&<details className="weather-rules"><summary>Riding preferences</summary><div>{([{key:'minTemp',label:'Min. temp °C',min:0,max:25},{key:'maxTemp',label:'Max. temp °C',min:10,max:34},{key:'rainChance',label:'Max. rain %',min:0,max:100},{key:'wind',label:'Max. wind km/h',min:0,max:40},{key:'gust',label:'Max. gust km/h',min:0,max:60}] as const).map(f=><label key={f.key}>{f.label}<input type="number" min={f.min} max={f.max} value={rules[f.key]} onChange={e=>{if(e.target.value==='')return;const n=Math.max(f.min,Math.min(f.max,Number(e.target.value)));setRules(r=>({...r,[f.key]:n,...(f.key==='minTemp'&&n>r.maxTemp?{maxTemp:n}:{}),...(f.key==='maxTemp'&&n<r.minTemp?{minTemp:n}:{})}))}}/></label>)}</div><p>Favourable also requires daylight, ≤0.1 mm rain and no rain, snow or storm weather code. These are planning preferences, not a safety assessment.</p><button onClick={()=>setRules(defaultWeatherRules)}>Reset limits</button></details>}
  <footer className="weather-source"><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather data by Open-Meteo</a>{forecast&&<span> · Retrieved {new Date(forecast.fetchedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})} · Forecast times: {tz}</span>}<p>Longer-range forecasts are less certain; recheck closer to your ride. Check local alerts and road conditions. Rain values cover the preceding hour. Weather refreshes every 15 minutes while this view is open.</p></footer>
 {!loading&&forecast&&<WeatherOutfit hours={best?dayHours.filter(h=>h.time>=best.start&&h.time<best.end):dayHours.filter(h=>h.daylight===1)} timezone={tz} best={!!best}/>}
 </section>
}

export default memo(WeatherRecon);
