"use client";
import WidgetSpark from './widget-spark';
import {useState,lazy,Suspense} from 'react';
const WeeklyVolumeDetail=lazy(()=>import('./weekly-volume-detail'));
import {Footprints,Bike,Dumbbell} from 'lucide-react';
import {useExpand} from './expansion';
import {weeklyVolume,type VolumeMetric} from './weekly-volume-data';
import type {AthleteData} from './analytics';
const sports=[{key:'running',label:'Running',color:'#2563eb',Icon:Footprints},{key:'cycling',label:'Cycling',color:'#7c3aed',Icon:Bike},{key:'strength_training',label:'Strength',color:'#b76a08',Icon:Dumbbell}];
const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:1});
function changeLabel(c:ReturnType<typeof weeklyVolume>){const d=c.comparison;if(d.direction==='unavailable')return '—';if(d.direction==='flat')return '→ 0%';const arrow=d.direction==='up'?'↑':'↓';return `${arrow} ${d.percent===null?fmt(Math.abs(d.absolute!))+' '+c.unit:Math.abs(d.percent).toLocaleString('en-GB',{maximumFractionDigits:0})+'%'}`}
export default function WeeklyVolume({data,now}:{data:AthleteData;now:Date}){
 const [weeks,setWeeks]=useState(8),[metric,setMetric]=useState<VolumeMetric>('sport'),expand=useExpand();
 function open(s:typeof sports[number]){const chart=weeklyVolume(data,now,s.key,weeks,metric);expand.widget(`${s.label} · weekly volume`,<Suspense fallback={<p role="status">Loading weekly volume…</p>}><WeeklyVolumeDetail chart={chart} color={s.color} change={changeLabel(chart)}/></Suspense>)}
 return <section className="weekly-volume" aria-label="Weekly training volume"><header><h2>Weekly volume</h2><div><select aria-label="Weekly volume metric" value={metric} onChange={e=>setMetric(e.target.value as VolumeMetric)}><option value="sport">km / strength hours</option><option value="hours">Hours · all sports</option><option value="sessions">Sessions</option></select><select aria-label="Weeks displayed" value={weeks} onChange={e=>setWeeks(+e.target.value)}>{[8,12,26].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></div></header><div className="weekly-volume-grid">{sports.map(s=>{const chart=weeklyVolume(data,now,s.key,weeks,metric);return <button className={`weekly-volume-card volume-${s.key}`} key={s.key} onClick={()=>open(s)}><span className="weekly-volume-title"><s.Icon size={16}/>{s.label}<span className={`weekly-change change-${chart.comparison.direction}`} title="Compared with the same elapsed portion of last week" aria-label={`${changeLabel(chart)} compared with the same point last week`}>{changeLabel(chart)}</span></span><strong>{fmt(chart.current.value)} <small>{chart.unit}{chart.current.incomplete?'*':''}</small></strong><span className="weekly-volume-caption">{chart.current.sessions} sessions</span><WidgetSpark className="weekly-volume-spark" values={chart.rows.map(r=>r.value)} color={s.color} label={`${s.label} weekly ${chart.unit}, ${weeks} weeks. Hollow dots mark partial weeks.`} partial={chart.rows.map(r=>!!(r.current||r.incomplete))} pointLabels={chart.rows.map(r=>`${r.label}: ${fmt(r.value)} ${chart.unit}${r.incomplete?' · incomplete':r.current?' · week in progress':''}`)}/><span className="weekly-volume-axis"><span>{chart.rows[0].label}</span><span>Now</span></span><span className="weekly-volume-average">Avg 4w <b>{fmt(chart.average)} {chart.unit}</b></span>{chart.current.incomplete&&<small className="weekly-volume-warning">* Incomplete data</small>}</button>})}</div><p className="weekly-volume-note">This week · ↑↓ vs same point last week · Monday starts · hollow dot = partial · tap for details</p></section>
}
