"use client";
import WidgetSpark from './widget-spark';
import {useState} from 'react';
import {BarChart,Bar,Cell,ResponsiveContainer,CartesianGrid,XAxis,YAxis,Tooltip} from 'recharts';
import {Footprints,Bike,Dumbbell} from 'lucide-react';
import {useExpand} from './expansion';
import {weeklyVolume,type VolumeMetric} from './weekly-volume-data';
import type {AthleteData} from './analytics';
const sports=[{key:'running',label:'Running',color:'#2563eb',Icon:Footprints},{key:'cycling',label:'Cycling',color:'#7c3aed',Icon:Bike},{key:'strength_training',label:'Strength',color:'#b76a08',Icon:Dumbbell}];
const fmt=(v:number|null)=>v===null?'—':v.toLocaleString('en-GB',{maximumFractionDigits:1});
function changeLabel(c:ReturnType<typeof weeklyVolume>){const d=c.comparison;if(d.direction==='unavailable')return '—';if(d.direction==='flat')return '→ 0%';const arrow=d.direction==='up'?'↑':'↓';return `${arrow} ${d.percent===null?fmt(Math.abs(d.absolute!))+' '+c.unit:Math.abs(d.percent).toLocaleString('en-GB',{maximumFractionDigits:0})+'%'}`}
export default function WeeklyVolume({data,now}:{data:AthleteData;now:Date}){
 const [weeks,setWeeks]=useState(8),[metric,setMetric]=useState<VolumeMetric>('sport'),expand=useExpand();
 function open(s:typeof sports[number]){const chart=weeklyVolume(data,now,s.key,weeks,metric);expand.widget(`${s.label} · weekly volume`,<div className="weekly-volume-detail"><p>Monday–Sunday totals in {chart.unit}. The current week includes synced sessions through today. Dashed outlines mark the current week or incomplete data.</p><div className="weekly-volume-expanded"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart.rows} margin={{top:12,right:12,left:0,bottom:6}}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" minTickGap={30}/><YAxis unit={chart.unit==='sessions'?'':chart.unit} allowDecimals={chart.unit!=='sessions'}/><Tooltip formatter={(v:any)=>[fmt(typeof v==='number'?v:null)+' '+chart.unit,'Volume']}/><Bar dataKey="value" maxBarSize={42} radius={[4,4,0,0]}>{chart.rows.map(r=><Cell key={r.start} fill={s.color} fillOpacity={r.current||r.incomplete?.45:1} stroke={s.color} strokeDasharray={r.current||r.incomplete?'4 3':undefined}/>)}</Bar></BarChart></ResponsiveContainer></div><p><b>{changeLabel(chart)}</b> versus the same point last week: {fmt(chart.current.value)} vs {fmt(chart.comparison.previous)} {chart.unit}. The prior period ends {new Date(chart.comparison.through).toLocaleString('en-GB')}. A dash means incomplete data; when the baseline is zero, the arrow shows the absolute change instead of a percentage.</p><p>Previous four complete weeks: {fmt(chart.average)} {chart.unit}/week on average. A higher volume is not automatically better.</p><div className="table-wrap"><table><thead><tr><th>Week</th><th>Volume</th><th>Sessions</th><th>Coverage</th></tr></thead><tbody>{chart.rows.map(r=><tr key={r.start}><td>{r.start} – {r.end}</td><td>{fmt(r.value)} {chart.unit}</td><td>{r.sessions}</td><td>{r.incomplete?'Incomplete history or measurements':r.current?'Week in progress':'Complete'}</td></tr>)}</tbody></table></div><p>Missing measurements are excluded and marked incomplete; unknown weeks are gaps, not zero. Removed workouts are excluded. Strength volume is time or session count, not lifted weight.</p></div>)}
 return <section className="weekly-volume" aria-label="Weekly training volume"><header><h2>Weekly volume</h2><div><select aria-label="Weekly volume metric" value={metric} onChange={e=>setMetric(e.target.value as VolumeMetric)}><option value="sport">km / strength hours</option><option value="hours">Hours · all sports</option><option value="sessions">Sessions</option></select><select aria-label="Weeks displayed" value={weeks} onChange={e=>setWeeks(+e.target.value)}>{[8,12,26].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></div></header><div className="weekly-volume-grid">{sports.map(s=>{const chart=weeklyVolume(data,now,s.key,weeks,metric),max=Math.max(1,...chart.rows.map(r=>r.value??0)),step=200/weeks;return <button className={`weekly-volume-card volume-${s.key}`} key={s.key} onClick={()=>open(s)}><span className="weekly-volume-title"><s.Icon size={16}/>{s.label}<span className={`weekly-change change-${chart.comparison.direction}`} title="Compared with the same elapsed portion of last week" aria-label={`${changeLabel(chart)} compared with the same point last week`}>{changeLabel(chart)}</span></span><strong>{fmt(chart.current.value)} <small>{chart.unit}{chart.current.incomplete?'*':''}</small></strong><span className="weekly-volume-caption">{chart.current.sessions} sessions</span><WidgetSpark className="weekly-volume-spark" values={chart.rows.map(r=>r.value)} color={s.color} label={`${s.label} weekly ${chart.unit}, ${weeks} weeks. Hollow dots mark partial weeks.`} partial={chart.rows.map(r=>!!(r.current||r.incomplete))} pointLabels={chart.rows.map(r=>`${r.label}: ${fmt(r.value)} ${chart.unit}${r.incomplete?' · incomplete':r.current?' · week in progress':''}`)}/><span className="weekly-volume-axis"><span>{chart.rows[0].label}</span><span>Now</span></span><span className="weekly-volume-average">Avg 4w <b>{fmt(chart.average)} {chart.unit}</b></span>{chart.current.incomplete&&<small className="weekly-volume-warning">* Incomplete data</small>}</button>})}</div><p className="weekly-volume-note">This week · ↑↓ vs same point last week · Monday starts · hollow dot = partial · tap for details</p></section>
}
