"use client";
import {useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
import type {AthleteData} from './analytics';
import {zoneLabel} from './zone-label';
import {weeklyZones} from './weekly-zones-data';
const colors=['#94a3b8','#60a5fa','#6366f1','#f59e0b','#ef4444','#be123c','#881337'];
const duration=(s:number)=>s>=3600?`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`:s>=60?`${Math.floor(s/60)}m ${Math.round(s%60)}s`:`${Math.round(s)}s`;
export default function WeeklyZones({data,now}:{data:AthleteData;now:Date}){
 const [offset,setOffset]=useState(0),[sport,setSport]=useState('running'),[scheme,setScheme]=useState('');
 const stamp=now.toDateString(),model=useMemo(()=>weeklyZones(data,now,offset,sport),[data,stamp,offset,sport]);
 const group=model.groups.find(g=>g.id===scheme)??model.groups[0],total=group?.seconds.reduce((a,b)=>a+b,0)??0;
 const last=new Date(model.end);last.setDate(last.getDate()-1);const date=(d:Date)=>d.toLocaleDateString('en-GB',{day:'numeric',month:'short'});
 const earliest=data.activities.reduce((min,a)=>Math.min(min,+new Date(a.date)),+model.start);
 return <section className="weekly-zones" aria-label="Weekly zone distribution"><header><h2>Weekly zones</h2><select aria-label="Weekly zone sport" value={sport} onChange={e=>{setSport(e.target.value);setScheme('')}}><option value="running">Running</option><option value="cycling">Cycling</option></select></header><nav aria-label="Zone week"><button aria-label="Previous zone week" disabled={+model.start<=earliest} onClick={()=>setOffset(v=>v-1)}><ChevronLeft size={15}/></button><span>{date(model.start)} – {date(last)}{model.partial?' · so far':''}</span><button aria-label="Next zone week" disabled={offset===0} onClick={()=>setOffset(v=>v+1)}><ChevronRight size={15}/></button></nav>{model.groups.length>1&&<select aria-label="Zone definitions" value={group.id} onChange={e=>setScheme(e.target.value)}>{model.groups.map((g,i)=><option key={g.id} value={g.id}>{g.label} · {g.covered} sessions · set {i+1}</option>)}</select>}{total>0&&group?<><div className="weekly-zone-total"><b>{duration(total)}</b><span>classified HR time · {group.covered}/{model.sessions} sessions</span></div><div className="weekly-zone-stack" aria-hidden="true">{group.seconds.map((s,i)=><i key={i} style={{width:`${s/total*100}%`,background:colors[Math.min(i,6)]}}/>)}</div><div className="weekly-zone-rows">{group.seconds.map((s,i)=>{const band=group.bands?.[i],range=band?(band.from<0?`≤${band.to}`:band.to<0?`≥${band.from}`:`${band.from}–${band.to}`)+' bpm':null;return <div key={i}><span><b style={{color:colors[Math.min(i,6)]}}>Z{i+1}</b><span className="zone-intensity">{zoneLabel(band,i,group.seconds.length)}</span><small>{range??'BPM not supplied'}</small></span><span className="weekly-zone-track"><i style={{width:`${s/total*100}%`,background:colors[Math.min(i,6)]}}/></span><strong>{duration(s)}</strong><span>{Math.round(s/total*100)}%</span></div>})}</div><footer>{group.bands?'HR zones · provider names when supplied; otherwise relative intensity.':'Relative intensity labels only; BPM boundaries unavailable. Not threshold or VO₂-max estimates.'}{group.unclassified>0&&` ${duration(group.unclassified)} outside these bands.`}{group.covered<model.sessions&&' Other sessions excluded from this view.'}{data.historyComplete===false&&' Synced history is incomplete.'}</footer></>:<p className="weekly-zone-empty">{model.sessions?'No usable HR-zone times yet for these sessions.':'No sessions this week.'}</p>}</section>;
}
