import {effortExcluded} from './workout-exclusions';
export const localDate=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
const mean=(values:(number|null)[])=>{const v=values.filter(finite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null};
export function weekOverview(data:any,now:Date,family:(a:any)=>string){
 const daily=Array.from({length:14},(_,i)=>{const date=new Date(now);date.setDate(date.getDate()-13+i);const iso=localDate(date),key=iso.replaceAll('-',''),sessions=data.activities.filter((a:any)=>localDate(new Date(a.date))===iso&&new Date(a.date)<=now),sleep=data.sleep[key],hrv=data.hrv[key];
 const body=(data.extra?.bodyvalues?.bodyvalues??[]).filter((r:any)=>localDate(new Date(r.timestamp))===iso&&finite(r.hrRestDynamic)&&new Date(r.timestamp)<=now).sort((a:any,b:any)=>b.timestamp.localeCompare(a.timestamp));
 const effortSource=data.extra?.efforts?.trainingEfforts,raw=effortSource?.[key],effortValues=Array.isArray(raw)?raw.map((e:any)=>Array.isArray(e)?e[0]:e):[];
 const effort=effortExcluded(data,iso)?null:effortSource?(effortValues.length&&effortValues.every(finite)?effortValues.reduce((a:number,b:number)=>a+b,0):sessions.length===0?0:null):null;
 const sum=(field:string)=>{const values=sessions.map((a:any)=>a.summary?.[field]).filter((v:any)=>finite(v)&&v>=0);return values.length?values.reduce((a:number,b:number)=>a+b,0):sessions.length?null:0};
 return {iso,label:date.toLocaleDateString('en-GB',{weekday:'short'}),sessions,minutes:sum('duration')===null?null:sum('duration')/60,calories:sum('calories'),effort,sleep:finite(sleep?.[0])?sleep[0]/3600:null,hrv:finite(hrv?.[0])?hrv[0]:null,rhr:body[0]?.hrRestDynamic??null,vo2:mean(sessions.filter((a:any)=>family(a)==='running').map((a:any)=>a.summary?.vo2max)),runKm:sessions.filter((a:any)=>family(a)==='running'&&finite(a.summary?.distance)).reduce((s:number,a:any)=>s+a.summary.distance/1000,0),rideKm:sessions.filter((a:any)=>family(a)==='cycling'&&finite(a.summary?.distance)).reduce((s:number,a:any)=>s+a.summary.distance/1000,0)};
 });
 const summarize=(rows:typeof daily)=>{const acts=rows.flatMap(r=>r.sessions),total=(key:'minutes'|'calories'|'effort'|'runKm'|'rideKm')=>{const active=rows.filter(r=>r.sessions.length>0);if(active.length&&active.every(r=>r[key]===null))return null;const v=rows.map(r=>r[key]).filter(finite);return v.length?v.reduce((s,v)=>s+v,0):null};return {sessions:acts.length,minutes:total('minutes'),calories:total('calories'),effort:total('effort'),effortDays:rows.filter(r=>finite(r.effort)).length,sleep:mean(rows.map(r=>r.sleep)),sleepDays:rows.filter(r=>finite(r.sleep)).length,hrv:mean(rows.map(r=>r.hrv)),hrvDays:rows.filter(r=>finite(r.hrv)).length,rhr:mean(rows.map(r=>r.rhr)),rhrDays:rows.filter(r=>finite(r.rhr)).length,vo2:mean(rows.map(r=>r.vo2)),vo2Days:rows.filter(r=>finite(r.vo2)).length,runKm:total('runKm'),rideKm:total('rideKm'),strength:acts.filter((a:any)=>family(a)==='strength_training').length,restDays:rows.filter(r=>r.sessions.length===0).length,durationCoverage:acts.filter((a:any)=>finite(a.summary?.duration)).length,calorieCoverage:acts.filter((a:any)=>finite(a.summary?.calories)).length}};
 return {rows:daily.slice(7),current:summarize(daily.slice(7)),previous:summarize(daily.slice(0,7)),start:daily[7].iso,end:daily[13].iso,historyComplete:!!data.historyStart&&new Date(data.historyStart)<=new Date(daily[0].iso+'T00:00:00')};
}
