"use client";
import {useEffect,useMemo,useState} from 'react';
import {Heart,Timer,Activity,Zap,RotateCcw} from 'lucide-react';
import {runningPace,cadenceUnit} from './sports';
import type {RouteSelection} from './route-geometry';
import {lapMosaic,mosaicLevel,mosaicStorageKey,validLapLabels,lapLabelOptions,type LapLabel} from './workout-lap-mosaic-data';
import './workout-lap-mosaic.css';
const clock=(seconds:number|null)=>{if(seconds===null)return '—';const rounded=Math.round(seconds);return `${Math.floor(rounded/60)}:${String(rounded%60).padStart(2,'0')}`};
type Props={detail:Record<string,any>;history:any[];token:string;isDemo?:boolean;storageScope:string;onSelection:(selection:RouteSelection|null)=>void};
export default function WorkoutLapMosaic({detail,storageScope,onSelection}:Props){
 const result=useMemo(()=>lapMosaic(detail),[detail]),{laps,family,totalDuration}=result;
 const [chosen,setChosen]=useState<number|null>(null),[metric,setMetric]=useState<'speed'|'power'>('speed'),[labels,setLabels]=useState<Record<string,LapLabel>>({}),[storageError,setStorageError]=useState(false);
 const storageKey=useMemo(()=>mosaicStorageKey(storageScope,detail),[storageScope,detail]);
 useEffect(()=>{setChosen(null);setStorageError(false);try{setLabels(storageKey?validLapLabels(JSON.parse(localStorage.getItem(storageKey)??'{}'),laps.length):{})}catch{setLabels({});setStorageError(true)}},[storageKey,laps.length]);
 const available=(['speed','power'] as const).filter(key=>laps.some(lap=>lap[key]!==null)),mode=available.includes(metric)?metric:available[0]??'speed',selected=chosen===null?null:laps[chosen];
 useEffect(()=>{onSelection(selected?.start!==null&&selected?.start!==undefined&&selected.end!==null?{start:selected.start,end:selected.end,label:`Lap ${selected.index}${labels[selected.index]?` · ${labels[selected.index]}`:''}`,kind:'lap',revision:chosen??0}:null)},[selected?.start,selected?.end,selected?.index,labels,chosen,onSelection]);
 function save(next:Record<string,LapLabel>){setLabels(next);if(storageKey)try{if(Object.keys(next).length)localStorage.setItem(storageKey,JSON.stringify(next));else localStorage.removeItem(storageKey)}catch{setStorageError(true)}}
 const speedLabel=(value:number)=>family==='swimming'?runningPace(100/value).replace('/km','/100m'):['running','walking','hiking'].includes(family)?runningPace(1000/value):`${(value*3.6).toFixed(1)} km/h`;
 const output=(value:number|null)=>value===null?'—':mode==='power'?`${Math.round(value)} W`:speedLabel(value);
 if(!laps.length)return <p className="lap-mosaic-empty">No recorded laps for this session.</p>;
 return <section className="lap-mosaic"><header><div><strong>Lap mosaic</strong><small>{laps.length} laps · {clock(totalDuration)} recorded</small></div><div><select aria-label="Select a lap" value={chosen===null?'':String(chosen)} onChange={e=>setChosen(e.target.value===''?null:Number(e.target.value))}><option value="">Choose lap</option>{laps.map((lap,index)=><option key={lap.index} value={index}>Lap {lap.index}{labels[lap.index]?` · ${labels[lap.index]}`:''}</option>)}</select>{available.length>1&&<select aria-label="Lap mosaic height" value={mode} onChange={e=>setMetric(e.target.value==='power'?'power':'speed')}><option value="speed">Speed</option><option value="power">Power</option></select>}<button type="button" aria-label="Reset lap labels" title="Reset labels" disabled={!Object.keys(labels).length} onClick={()=>save({})}><RotateCcw size={13}/></button></div></header>
 <div className="lap-mosaic-bars" aria-label="Recorded laps. Width is duration, height and colour are relative output.">{laps.map((lap,index)=>{const level=mosaicLevel(lap,laps,mode),width=totalDuration&&lap.duration!==null?lap.duration/totalDuration:0;return <button key={lap.index} type="button" aria-pressed={chosen===index} aria-label={`Lap ${lap.index}, ${labels[lap.index]??'unlabelled'}, ${clock(lap.duration)}, ${output(lap[mode])}`} title={`Lap ${lap.index} · ${output(lap[mode])}`} onClick={()=>setChosen(index)} style={{flexGrow:width||.002,flexBasis:0,height:level===null?16:24+level*55,background:level===null?'#e5e7eb':`hsl(239 75% ${77-level*27}%)`}}><span>{lap.index}</span>{labels[lap.index]&&<i title={labels[lap.index]}>{labels[lap.index].slice(0,1)}</i>}</button>})}</div>
 <div className="lap-mosaic-legend"><span>Width = time</span><span><i/> Low → high {mode==='power'?'power':'speed'} in this session</span></div>
 {selected?<div className="lap-mosaic-detail" aria-live="polite"><header><strong>Lap {selected.index}</strong><label className="lap-mosaic-label"><select aria-label={`Label lap ${selected.index}`} value={labels[selected.index]??''} onChange={e=>{const next={...labels};if(e.target.value)next[selected.index]=e.target.value as LapLabel;else delete next[selected.index];save(next)}}><option value="">Add label</option>{lapLabelOptions.map(label=><option key={label} value={label}>{label}</option>)}</select></label><button type="button" onClick={()=>setChosen(null)}>Clear</button></header><div><span><Timer size={12}/><b>{clock(selected.duration)}</b></span>{selected.distance!==null&&<span><Activity size={12}/><b>{(selected.distance/1000).toFixed(2)} km</b></span>}{selected.speed!==null&&<span><b>{speedLabel(selected.speed)}</b></span>}{selected.power!==null&&<span><Zap size={12}/><b>{Math.round(selected.power)} W</b></span>}{selected.hr!==null&&<span><Heart size={12}/><b>{Math.round(selected.hr)} bpm</b></span>}{selected.cadence!==null&&<span><b>{Math.round(selected.cadence)}</b> {cadenceUnit(family)}</span>}</div>{selected.start===null&&<small>Recorded metrics available; lap timing cannot be placed reliably on the route.</small>}</div>:<p className="lap-mosaic-note">Tap a lap to highlight it and add a training label.</p>}
 {result.reason&&<p className="lap-mosaic-note">{result.reason}</p>}{storageError&&<p className="lap-mosaic-note">Labels stay in this view; browser storage is unavailable.</p>}<details><summary>How to read it</summary><p>Colour shows relative recorded output within this session, not personal training zones. Unknown output stays grey. Lap widths use recorded duration; unknown durations use a small placeholder. Labels are saved only in this browser for your account and this recording.</p></details>
 </section>;
}
