"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Play,Pause,RotateCcw,Route,TrendingUp,Wind,Heart,Timer,Zap,Footprints} from 'lucide-react';
import type {RouteSelection} from './route-geometry';
import {workoutReplayData,type ReplayRange,type FingerprintPoint} from './workout-replay-data';
import {paceFromSpeed} from './activity-terrain-data';
import {cadenceUnit} from './sports';
import './workout-replay.css';
const clock=(seconds:number)=>{const s=Math.max(0,Math.round(seconds));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
const duration=(seconds:number)=>seconds>=3600?`${Math.floor(seconds/3600)}h ${Math.round(seconds%3600/60)}m`:seconds>=60?`${Math.floor(seconds/60)}m ${Math.round(seconds%60)}s`:`${Math.round(seconds)}s`;
const output=(value:number|null,cycling:boolean)=>value===null?'—':cycling?`${Math.round(value)} W`:`${paceFromSpeed(value)} /km`;
export type WorkoutReplayMode='replay'|'fingerprint'|'terrain'|'coasting';
const modeOptions=[{id:'replay',label:'Replay',Icon:Play},{id:'fingerprint',label:'Fingerprint',Icon:TrendingUp},{id:'terrain',label:'Terrain',Icon:Route},{id:'coasting',label:'Coasting',Icon:Wind}] as const;
export default function WorkoutReplay({detail,onSelection,onCursor,mode:externalMode}:{detail:any;onSelection?:(selection:RouteSelection|null)=>void;onCursor?:(sampleIndex:number|null)=>void;mode?:WorkoutReplayMode}){
 const data=useMemo(()=>workoutReplayData(detail),[detail]),[ownedMode,setMode]=useState<WorkoutReplayMode>('replay'),mode=externalMode??ownedMode,[index,setIndex]=useState(0),[playing,setPlaying]=useState(false),[chosen,setChosen]=useState<string|null>(null),[point,setPoint]=useState<FingerprintPoint|null>(null),[reducedMotion,setReducedMotion]=useState(false),panelRef=useRef<HTMLElement>(null);
 const row=data.rows[Math.min(index,data.rows.length-1)],lap=row?data.laps.find(l=>row.seconds/60>=l.start&&row.seconds/60<l.end):null;
 useEffect(()=>{setIndex(0);setPlaying(false);setChosen(null);setPoint(null)},[detail]);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)'),update=()=>{setReducedMotion(media.matches);if(media.matches)setPlaying(false)};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(mode==='replay')onCursor?.(row?.index??null);else onCursor?.(point?.index??null)},[mode,row?.index,point?.index,onCursor]);
 useEffect(()=>{if(mode==='replay')onSelection?.(lap?{start:lap.start,end:lap.end,label:`Lap ${lap.index}`,kind:'lap'}:null)},[mode,lap?.index,lap?.start,lap?.end,onSelection]);
 useEffect(()=>()=>{onCursor?.(null);onSelection?.(null)},[onCursor,onSelection]);
 useEffect(()=>{setPlaying(false);setChosen(null);setPoint(null)},[mode]);
 useEffect(()=>{if(!playing||mode!=='replay')return;const stop=()=>{if(document.hidden||panelRef.current?.closest('[hidden]'))setPlaying(false)};document.addEventListener('visibilitychange',stop);const timer=window.setInterval(()=>{if(document.hidden||panelRef.current?.closest('[hidden]')){setPlaying(false);return}setIndex(current=>{const next=current+Math.max(1,Math.round(15/data.step));if(next>=data.rows.length-1){setPlaying(false);return data.rows.length-1}return next})},200);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',stop)}},[playing,mode,data.step,data.rows.length]);
 const selectRanges=(ranges:ReplayRange[],label:string,kind:RouteSelection['kind'])=>{onSelection?.(ranges.length?{start:ranges[0].start,end:ranges.at(-1)!.end,label,kind,ranges}:null)};
 const change=(next:WorkoutReplayMode)=>{setMode(next);setPlaying(false);setChosen(null);setPoint(null);onSelection?.(null)};
 const selectPoint=(p:FingerprintPoint)=>{setPoint(p);selectRanges([{start:p.start,end:p.end}],`Stable minute at ${clock(p.start*60)}`,'replay')};
 const fingerprintValue=(value:number)=>data.cycling?(data.fingerprintSource==='power'?value:value*3.6):1000/value;
 const fingerprintLabel=(value:number)=>data.cycling?(data.fingerprintSource==='power'?`${Math.round(value)} W`:`${(value*3.6).toFixed(1)} km/h`):output(value,false);
 const bounds=useMemo(()=>{
  const values=data.fingerprint.map(p=>data.cycling?(data.fingerprintSource==='power'?p.output:p.output*3.6):1000/p.output),hrs=data.fingerprint.map(p=>p.hr);if(!values.length)return {xmin:0,xmax:1,ymin:0,ymax:1};const xmin=Math.min(...values),xmax=Math.max(...values),ymin=Math.min(...hrs),ymax=Math.max(...hrs);return {xmin:xmin-Math.max(5,(xmax-xmin)*.12),xmax:xmax+Math.max(5,(xmax-xmin)*.12),ymin:Math.max(0,ymin-Math.max(3,(ymax-ymin)*.12)),ymax:ymax+Math.max(3,(ymax-ymin)*.12)};
 },[data.fingerprint,data.cycling,data.fingerprintSource]);
 if(!data.rows.length)return <p className="activity-data-note">{data.reason}</p>;
 const instantOutput=data.cycling&&data.hasPower?(row?.power??null):(row?.speed??null),cadenceLabel=cadenceUnit(data.family),instantValue=data.cycling&&!data.hasPower?(instantOutput===null?'—':`${(instantOutput*3.6).toFixed(1)} km/h`):output(instantOutput,data.cycling);
 return <section ref={panelRef} className="workout-replay" aria-label="Interactive workout analysis">{!externalMode&&<nav className="workout-replay-modes" aria-label="Workout explorer views">{modeOptions.filter(option=>data.cycling||option.id!=='coasting').map(({id,label,Icon})=><button type="button" key={id} aria-pressed={mode===id} onClick={()=>change(id)}><Icon size={13}/><span>{label}</span></button>)}</nav>}
 {mode==='replay'&&<><div className="workout-replay-readout"><span><Timer size={12}/><strong>{clock(row?.seconds??0)}</strong><small>{duration(data.seconds)} recorded</small></span><span>{data.cycling?<Zap size={12}/>:<Footprints size={12}/>}<strong>{instantValue}</strong><small>{data.cycling?(data.fingerprintSource==='power'?'Power':'Speed'):'Pace'}</small></span><span><Heart size={12}/><strong>{row?.hr===null?'—':Math.round(row?.hr??0)}<em> bpm</em></strong><small>Heart rate</small></span><span><RotateCcw size={12}/><strong>{row?.cadence===null?'—':Math.round(row?.cadence??0)}</strong><small>{cadenceLabel}</small></span></div><div className="workout-replay-scrubber"><button type="button" aria-label={playing?'Pause replay':'Play replay'} disabled={!data.step||reducedMotion} title={reducedMotion?'Use the scrubber with reduced motion enabled':undefined} onClick={()=>{if(!playing&&index===data.rows.length-1)setIndex(0);setPlaying(v=>!v)}}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><input type="range" min="0" max={data.rows.length-1} step="1" value={index} aria-label="Workout replay time" aria-valuetext={`${clock(row?.seconds??0)}${lap?`, lap ${lap.index}`:''}`} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value))}}/><span>{lap?`Lap ${lap.index}`:'No aligned lap'}</span></div>{!!data.laps.length&&<div className="workout-replay-laps" aria-label="Replay laps">{data.laps.map(l=><button type="button" key={l.index} aria-pressed={lap?.index===l.index} style={{flexGrow:l.end-l.start}} onClick={()=>{setIndex(Math.min(data.rows.length-1,Math.round(l.start*60/data.step)));selectRanges([{start:l.start,end:l.end}],`Lap ${l.index}`,'lap')}} title={`Lap ${l.index} · ${clock((l.end-l.start)*60)}`}>{l.index}</button>)}</div>}<p className="workout-replay-note">Scrub to move the map marker. Values are individual recorded samples every {data.step}s; blanks are gaps. {data.lapReason}</p></>}
 {mode==='fingerprint'&&<>{data.fingerprint.length>=4?<><div className="workout-fingerprint-chart"><svg viewBox="0 0 340 180" role="img" aria-label={`${data.cycling?(data.hasPower?'Power':'Speed'):'Pace'} against heart rate, stable matched minutes`}><line x1="38" y1="144" x2="322" y2="144" stroke="#dce1ea"/><line x1="38" y1="14" x2="38" y2="144" stroke="#dce1ea"/>{[0,.5,1].map(f=><g key={f}><line x1="38" x2="322" y1={144-f*130} y2={144-f*130} stroke="#edf0f5"/><text x="31" y={148-f*130} textAnchor="end">{Math.round(bounds.ymin+f*(bounds.ymax-bounds.ymin))}</text><text x={38+f*284} y="160" textAnchor="middle">{data.cycling?Math.round(bounds.xmin+f*(bounds.xmax-bounds.xmin)):clock(bounds.xmin+f*(bounds.xmax-bounds.xmin))}</text></g>)}{data.fingerprint.map(p=>{const value=fingerprintValue(p.output),x=38+(value-bounds.xmin)/(bounds.xmax-bounds.xmin)*284,y=144-(p.hr-bounds.ymin)/(bounds.ymax-bounds.ymin)*130;return <circle key={p.index} cx={x} cy={y} r={point===p?5:3.4} fill={`hsl(${210+p.phase*65} 70% ${65-p.phase*20}%)`} stroke={point===p?'#312e81':'#fff'} strokeWidth="1" tabIndex={0} role="button" aria-label={`${clock(p.start*60)} · ${fingerprintLabel(p.output)} · ${Math.round(p.hr)} bpm`} onClick={()=>selectPoint(p)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectPoint(p)}}}><title>{clock(p.start*60)} · {fingerprintLabel(p.output)} · {Math.round(p.hr)} bpm</title></circle>})}<text x="8" y="9">bpm</text><text x="180" y="176" textAnchor="middle">{data.cycling?(data.fingerprintSource==='power'?'Power · W':'Speed · km/h'):'Pace · /km'}</text></svg></div><div className="workout-fingerprint-caption"><span><i/>Early → late</span><span>{data.fingerprintCount} matched minutes</span></div>{point&&<div className="workout-replay-selected"><b>{clock(point.start*60)} → {clock(point.end*60)}</b><span>{fingerprintLabel(point.output)} · {Math.round(point.hr)} bpm{point.cadence!==null?` · ${Math.round(point.cadence)} ${cadenceLabel}`:''}</span></div>}</>:<p className="workout-replay-empty">Not enough stable, flat minutes at comparable output in both halves. A short, hilly or interval workout may have no fingerprint.</p>}<details className="workout-replay-method"><summary>How the fingerprint is matched</summary><p>One-minute averages after the first 2 minutes and before the final minute. Moving samples, stable output, grade within ±2%; matched output and similar grade across both halves. Colour shows recorded order, not a form score. Cycling uses speed when power is absent; wind and drafting can change speed.</p></details></>}
 {mode==='terrain'&&<>{data.terrainSeconds>0?<><div className="workout-terrain-bar">{data.terrain.map(bucket=><button type="button" key={bucket.key} className={bucket.key} style={{width:`${bucket.percent}%`}} aria-label={`${bucket.key} · ${Math.round(bucket.percent)}%`} onClick={()=>{setChosen(bucket.key);selectRanges(bucket.ranges,bucket.key,'terrain')}}/>)}</div><div className="workout-terrain-table"><table><thead><tr><th>Terrain</th><th>Time</th><th>{data.cycling?(data.hasPower?'Power':'Speed'):'Pace'}</th><th>HR / cadence</th></tr></thead><tbody>{data.terrain.map(bucket=><tr key={bucket.key} className={chosen===bucket.key?'is-selected':''}><th><button type="button" disabled={!bucket.seconds} aria-pressed={chosen===bucket.key} onClick={()=>{setChosen(bucket.key);selectRanges(bucket.ranges,bucket.key,'terrain')}}>{bucket.key}<small>{Math.round(bucket.percent)}%</small></button></th><td>{duration(bucket.seconds)}</td><td>{data.cycling&&!data.hasPower?(bucket.speed===null?'—':`${(bucket.speed*3.6).toFixed(1)} km/h`):output(data.cycling?bucket.power:bucket.speed,data.cycling)}</td><td>{bucket.hr===null?'—':`${Math.round(bucket.hr)} bpm`}<small>{bucket.cadence===null?'—':`${Math.round(bucket.cadence)} ${cadenceLabel}`}</small></td></tr>)}</tbody></table></div></>:<p className="workout-replay-empty">Terrain breakdown needs moving speed and either grade or paired elevation and distance samples.</p>}<div className="workout-terrain-coverage"><b>{Math.round(data.movingSeconds?data.terrainSeconds/data.movingSeconds*100:0)}% moving time classified</b><span>Uphill &gt;2% · flat ±2% · downhill &lt;−2%</span></div><details className="workout-replay-method"><summary>Terrain method & coverage</summary><p>{Math.round(data.movingSeconds?data.terrainSeconds/data.movingSeconds*100:0)}% of recorded moving time classified. Uphill &gt;2%, downhill &lt;−2%, flat between. Recorded grade or approximately 50 m elevation/distance windows; gaps and stops split the calculation. Cadence averages exclude zero readings. Tap a row to highlight every matching route section.</p></details></>}
 {mode==='coasting'&&<><div className="workout-coasting-summary"><div><Wind size={15}/><strong>{data.coasting.percent===null?'—':`${data.coasting.percent.toFixed(1)}%`}</strong><span>{data.coasting.method==='cadence'?'cadence coasting estimate':data.coasting.method==='unavailable'?'coasting unavailable':'coasting estimate'}</span></div><div><strong>{data.coasting.percent===null?'—':duration(data.coasting.seconds)}</strong><span>{duration(data.coasting.classifiedSeconds)} with {data.coasting.method==='cadence'?'cadence':'power'}</span></div><button type="button" disabled={!data.coasting.ranges.length} aria-pressed={chosen==='coasting'} onClick={()=>{setChosen('coasting');selectRanges(data.coasting.ranges,'Coasting estimate','coasting')}}>Show on route</button></div><div className="workout-coasting-details"><span><b>{duration(data.coasting.zeroPowerSeconds)}</b> raw zero-power moving</span><span><b>{duration(data.coasting.confirmedSeconds)}</b> 0 W + confirmed 0 rpm</span><span><b>{duration(data.coasting.unloadedSeconds)}</b> pedalling at 0 W</span><span><b>{duration(data.coasting.unknownCadenceSeconds)}</b> 0 W, cadence unconfirmed</span><span><b>{duration(data.coasting.powerGapSeconds)}</b> moving power gaps</span><span><b>{duration(data.coasting.stoppedSeconds)}</b> stopped / ≤3.6 km/h</span><span><b>{Math.round(data.coasting.coverage*100)}%</b> moving power coverage</span><span><b>{Math.round(data.coasting.movingSeconds?data.coasting.cadenceSeconds/data.coasting.movingSeconds*100:0)}%</b> moving cadence coverage</span></div><details className="workout-replay-method"><summary>How coasting is measured</summary><p>{data.coasting.method==='power'?'Recorded 0 W while faster than 3.6 km/h; positive cadence is excluded from coasting. Without usable cadence, 0 W is an estimate and may include a sensor dropout. Percentage uses moving time with valid power.':data.coasting.method==='cadence'?'Cadence-based estimate: 0 rpm while faster than 3.6 km/h, divided by moving time with valid cadence. Both pedalling and zero-rpm readings are present. Power cannot provide a useful estimate for this recording.':'Coasting needs a power recording with non-zero readings, or a cadence recording containing both pedalling and zero rpm. Raw zero-power time is shown separately.'} Missing speed, power or cadence never becomes a recorded zero. {data.coasting.allPowerZero?'Every moving power reading is zero; check that the power sensor was recording.':null} {data.coasting.allCadenceZero?'Cadence reads zero throughout and cannot confirm coasting.':null} {data.coasting.motionGapSeconds>0?`${duration(data.coasting.motionGapSeconds)} without speed cannot be classified.`:''}</p></details></>}
 </section>;
}
