"use client";
import {useMemo,useRef,useState,useEffect} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine} from 'recharts';
import {GitCompareArrows,ArrowDown,ArrowUp} from 'lucide-react';
import {cachedWorkout,loadWorkout} from './workout-detail-cache';
import {demoWorkoutDetail} from './demo-workout-detail';
import type {Workout} from './analytics';
import {sportFamily,runningPace} from './sports';
import type {RouteSelection} from './route-geometry';
import {routeCandidates,fetchableComparisonId,compareRoutes} from './workout-route-compare-data';
import './workout-route-compare.css';
type Props={detail:Record<string,any>;history:any[];token:string;isDemo?:boolean;onSelection:(selection:RouteSelection|null)=>void};
const date=(value:string)=>new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'short'});
const deltaText=(value:number)=>`${Math.floor(Math.abs(Math.round(value))/60)}:${String(Math.abs(Math.round(value))%60).padStart(2,'0')}`;
export default function WorkoutRouteCompare({detail,history,token,isDemo,onSelection}:Props){
 const candidates=useMemo(()=>routeCandidates(detail,history),[detail,history]);
 const [choice,setChoice]=useState(''),[prior,setPrior]=useState<Record<string,any>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[metric,setMetric]=useState<'Speed'|'Power'|'HR'>('Speed'),request=useRef(0);
 useEffect(()=>{request.current++;setChoice('');setPrior(null);setError('');setBusy(false);onSelection(null);return()=>{request.current++}},[detail.id,token,isDemo,onSelection]);
 const comparison=useMemo(()=>prior?compareRoutes(detail,prior):null,[detail,prior]);
 async function choose(id:string){
  const sequence=++request.current;setChoice(id);setPrior(null);setError('');onSelection(null);
  const activity=candidates.find(candidate=>String(candidate.activity.id)===id)?.activity;
  if(!activity){setBusy(false);return}
  const resident=isDemo?demoWorkoutDetail(activity as Workout):activity.seriesSampled?activity:cachedWorkout(token,id);
  if(resident){setPrior({...activity,...resident});setBusy(false);return}
  if(!fetchableComparisonId(activity)){setError('This recording has no cached route available for comparison.');setBusy(false);return}
  setBusy(true);
  try{const loaded=await loadWorkout(token,id);if(request.current===sequence)setPrior({...activity,...loaded})}catch(cause){if(request.current===sequence)setError(cause instanceof Error?cause.message:'Could not load the earlier route.')}finally{if(request.current===sequence)setBusy(false)}
 }
 const available=(['Speed','Power','HR'] as const).filter(key=>comparison?.points.some(point=>point[`current${key}`]!==null&&point[`prior${key}`]!==null)),mode=available.includes(metric)?metric:available[0]??'Speed',pace=mode==='Speed'&&sportFamily(detail)!=='cycling',unit=mode==='Speed'?(pace?'/km':'km/h'):mode==='Power'?'W':'bpm';
 const metricLabel=(key:string)=>key==='Speed'&&sportFamily(detail)!=='cycling'?'Pace':key;
 const valueLabel=(value:number)=>pace?runningPace(value>0?3600/value:null):`${value.toFixed(mode==='Speed'?1:0)} ${unit}`;
 return <section className="workout-route-compare"><header><span><GitCompareArrows size={14}/><strong>Previous visit</strong></span>{comparison?.matched&&<small>{Math.round(comparison.overlap*100)}% GPS overlap</small>}</header>
 {candidates.length?<label className="workout-compare-picker"><select aria-label="Choose an earlier possible route match" value={choice} onChange={e=>void choose(e.target.value)}><option value="">Choose a possible match…</option>{candidates.map(({activity,distance})=><option key={activity.id} value={activity.id}>{date(activity.date)} · {(distance/1000).toFixed(2)} km · {activity.title||'Workout'}</option>)}</select></label>:<p className="workout-compare-note">No earlier same-sport recording with a similar distance is available.</p>}
 {!choice&&candidates.length>0&&<p className="workout-compare-note">Choose one recording to load. Distance similarities are checked against GPS before comparison.</p>}{busy&&<p role="status" className="workout-compare-note">Checking this recording’s route…</p>}{error&&<p role="alert" className="workout-compare-note">{error}</p>}{comparison&&!comparison.matched&&<p className="workout-compare-note">{comparison.reason}</p>}
 {comparison?.matched&&<><div className="workout-compare-summary">{comparison.delta!==null?<span>{comparison.delta<=0?<ArrowDown size={14}/>:<ArrowUp size={14}/>}<b>{deltaText(comparison.delta)} {Math.abs(comparison.delta)<1?'level':comparison.delta<0?'quicker':'slower'}</b><small>observed moving time · common distance</small></span>:<span><b>Moving time unavailable</b><small>Missing speed samples prevent a complete comparison</small></span>}<span><b>{(comparison.commonDistance/1000).toFixed(2)} km</b><small>shared recorded distance</small></span></div>
 {available.length>0&&<><div className="workout-compare-chart-heading"><span><i/> This session <i className="prior"/> {prior?date(prior.date):'Earlier'}</span>{available.length>1&&<select aria-label="Comparison metric" value={mode} onChange={e=>setMetric(e.target.value as typeof metric)}>{available.map(key=><option key={key} value={key}>{metricLabel(key)}</option>)}</select>}<small>{unit}</small></div><div className="workout-compare-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={comparison.points} margin={{left:0,right:8,top:4,bottom:0}}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="km" type="number" domain={['dataMin','dataMax']} tick={{fontSize:10}} tickFormatter={value=>`${Number(value).toFixed(1)}k`} height={23}/><YAxis tick={{fontSize:10}} width={pace?39:32} tickFormatter={value=>pace?runningPace(Number(value)>0?3600/Number(value):null).replace(' /km',''):String(Math.round(Number(value)))} domain={['auto','auto']}/><Tooltip contentStyle={{fontSize:11,padding:7,borderRadius:8}} labelFormatter={value=>`${Number(value).toFixed(2)} km`} formatter={(value:any,name:any)=>[valueLabel(Number(value)),name]}/><Line dataKey={`current${mode}`} name="This session" stroke="#4f46e5" strokeWidth={1.7} dot={false} connectNulls={false} isAnimationActive={false}/><Line dataKey={`prior${mode}`} name="Earlier session" stroke="#94a3b8" strokeWidth={1.5} strokeDasharray="4 3" dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></>}
 {comparison.movingTimeAvailable&&<><div className="workout-compare-chart-heading"><strong>Where time changed</strong><small>Below zero = quicker</small></div><div className="workout-compare-chart delta"><ResponsiveContainer width="100%" height="100%"><LineChart data={comparison.points} margin={{left:0,right:8,top:4,bottom:0}} onClick={event=>{const value=event.activeLabel;if(typeof value!=='number')return;const point=comparison.points.reduce((closest,candidate)=>Math.abs(candidate.km-value)<Math.abs(closest.km-value)?candidate:closest,comparison.points[0]);if(point.currentTime>0)onSelection({start:Math.max(0,point.currentTime-.5),end:point.currentTime+.5,label:`Comparison at ${point.km.toFixed(2)} km`,kind:'effort',revision:Date.now()})}}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="km" type="number" domain={['dataMin','dataMax']} tick={{fontSize:10}} tickFormatter={value=>`${Number(value).toFixed(1)}k`} height={23}/><YAxis tick={{fontSize:10}} width={32} tickFormatter={value=>`${Math.round(value)}s`} domain={['auto','auto']}/><ReferenceLine y={0} stroke="#cbd5e1"/><Tooltip contentStyle={{fontSize:11,padding:7,borderRadius:8}} labelFormatter={value=>`${Number(value).toFixed(2)} km`} formatter={(value:any)=>[`${Number(value)>=0?'+':'−'}${deltaText(Number(value))}`,Number(value)<0?'Quicker':'Slower']}/><Line dataKey="delta" stroke="#6366f1" strokeWidth={1.6} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></>}
 <details><summary>Match & timing details</summary><p>{comparison.reason} Median GPS difference: {Math.round(comparison.medianGap??0)} m. Moving time counts recorded speed above 0.5 m/s; observed stops are excluded. Watch pauses may already be omitted by the provider. This is a session comparison, not an exact race result. Weather, traffic and recovery can change performance.</p></details></>}
 </section>;
}
