"use client";
import {useMemo} from 'react';
import {Activity,ArrowRight,Clock,Dumbbell,Heart,Moon,Wind} from 'lucide-react';
import type {AthleteData,Workout} from './analytics';
import {SportIcon,clockDuration} from './dashboard-calendar';
import {sportName,sportFamily} from './sports';
import {recoveryAfterWorkout,strengthSummary,workoutContext,type UsualRange} from './workout-context-data';
import './workout-context.css';

type Props={detail:Workout|Record<string,any>;history:Workout[];healthData?:AthleteData;now?:Date;onSelect?:(activity:Workout)=>void};
const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'});
const time=(date:string)=>new Date(date).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
const sleepDuration=(hours:number)=>{const minutes=Math.round(hours*60);return `${Math.floor(minutes/60)}h${String(minutes%60).padStart(2,'0')}`};
const signed=(value:number,unit:string)=>`${value>0?'+':value<0?'−':''}${Math.abs(value).toFixed(0)}${unit}`;
function gapLabel(gap:{hours:number|null;overlap:boolean}|null){return !gap?'':gap.overlap?'Overlapping recordings':gap.hours===null?'Gap unknown':gap.hours<1?`${Math.round(gap.hours*60)}m gap`:`${gap.hours.toFixed(gap.hours<10?1:0)}h gap`}

export default function WorkoutContext({detail,history,now,onSelect}:Props){
 const context=useMemo(()=>workoutContext(detail as Workout,history,now),[detail,history,now]);
 return <section className="workout-context" aria-label="Training session sequence"><div className="workout-context-sequence">{([context.previous,context.current,context.next] as const).map((activity,index)=>{const label=['Previous','This session','Next recorded'][index],content=<><span className="workout-context-label">{label}</span>{activity?<><span className="workout-context-session"><SportIcon activity={activity}/><b>{sportName(sportFamily(activity))}</b></span><span className="workout-context-date">{new Date(activity.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})} · {time(activity.date)}</span></>:<span className="workout-context-missing">No {index===0?'earlier':'later'} session</span>}</>;return <div className={'workout-context-node '+(index===1?'current':'')} key={label}>{activity&&index!==1&&onSelect?<button type="button" onClick={()=>onSelect(activity)} aria-label={`Open ${label.toLowerCase()} workout`}>{content}</button>:<div aria-current={index===1?'true':undefined}>{content}</div>}{index<2&&<span className="workout-context-gap"><ArrowRight size={11}/>{gapLabel(index===0?context.before:context.after)}</span>}</div>})}</div></section>;
}

export function StrengthSummary({detail,history,now}:Props){
 const result=useMemo(()=>strengthSummary(detail as Workout,history,now),[detail,history,now]);if(!result)return null;
 const {current,previous,durationChange,setsChange}=result,rows=[current,...previous],effects=current.aerobic!==null||current.anaerobic!==null;
 return <section className="workout-strength"><header><h3><Dumbbell size={14}/>Strength session</h3><span>{current.sets===null?'Sets not supplied':`${current.sets} recorded sets`}</span></header><div className="workout-strength-totals"><span><Clock size={13}/><b>{clockDuration(current.duration)}</b>{durationChange!==null&&<small>{signed(durationChange/60,'m')} vs last</small>}</span>{current.sets!==null&&<span><Dumbbell size={13}/><b>{current.sets} sets</b>{setsChange!==null&&<small>{signed(setsChange,'')} vs last</small>}</span>}{effects&&<span title="Recorded COROS aerobic / anaerobic training effect"><Wind size={13}/><b>{current.aerobic?.toFixed(1)??'—'} / {current.anaerobic?.toFixed(1)??'—'}</b><small>Aerobic / anaerobic effect</small></span>}</div>{previous.length>0&&<div className="workout-context-table-wrap"><table className="workout-context-table"><caption className="sr-only">This session and up to three previous strength sessions</caption><thead><tr><th>Session</th><th>Time</th><th>Sets</th><th>Effect A / AN</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.activity.id} className={i===0?'current':''}><th scope="row">{i===0?'This session':new Date(row.activity.date).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</th><td>{clockDuration(row.duration)}</td><td>{row.sets??'—'}</td><td>{row.aerobic?.toFixed(1)??'—'} / {row.anaerobic?.toFixed(1)??'—'}</td></tr>)}</tbody></table></div>}<details className="workout-context-method"><summary>What these numbers cover</summary><p>Sets are the recorded session count. Training effect is COROS’s recorded aerobic / anaerobic estimate, not a measure of lifting quality. Exercise names, repetitions, weights and tonnage are not supplied in this recording.</p></details></section>;
}

function rangeText(range:UsualRange|null,kind:'sleep'|'hrv'|'rhr'){if(!range)return 'Building baseline';return kind==='sleep'?`${sleepDuration(range.low)}–${sleepDuration(range.high)}`:`${Math.round(range.low)}–${Math.round(range.high)} ${kind==='hrv'?'ms':'bpm'}`}
function RecoveryCell({value,range,kind}:{value:number|null;range:UsualRange|null;kind:'sleep'|'hrv'|'rhr'}){
 if(value===null)return <td className="workout-context-unknown">—</td>;
 const tone=!range?'neutral':value<range.low||value>range.high?'review':'usual',difference=range?value-range.mean:null;
 return <td className={'workout-recovery-value '+tone} title={range?`Usual ${rangeText(range,kind)} · ${range.count} prior readings`:'Not enough prior readings for a usual range'}><b>{kind==='sleep'?sleepDuration(value):Math.round(value)}{kind!=='sleep'&&<small>{kind==='hrv'?' ms':' bpm'}</small>}</b>{difference!==null&&<span>{kind==='sleep'?signed(difference*60,'m'):kind==='hrv'?signed(difference/range!.mean*100,'%'):signed(difference,' bpm')}</span>}</td>;
}
export function RecoveryAfterWorkout({detail,history,healthData,now}:Props){
 const result=useMemo(()=>recoveryAfterWorkout(detail as Workout,history,healthData,now),[detail,history,healthData,now]);
 return <section className="workout-recovery"><header><h3><Moon size={14}/>The following mornings</h3><span>{dateLabel(result.date)} · {result.sessions.length} session{result.sessions.length===1?'':'s'}</span></header>{!result.available?<p className="workout-context-empty">Your daily health history is needed for this view.</p>:!result.rows.length?<p className="workout-context-empty">The next morning’s recorded sleep, HRV and resting HR will appear here.</p>:<><div className="workout-context-table-wrap"><table className="workout-context-table"><caption className="sr-only">Recorded health on the three calendar mornings after this training day</caption><thead><tr><th>Morning</th><th><Moon size={12}/>Sleep</th><th><Activity size={12}/>HRV</th><th><Heart size={12}/>Resting HR</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.date}><th scope="row">{dateLabel(row.date)}<span className="workout-recovery-other">{row.sessions.length>0?<>{row.sessions.slice(0,3).map(a=><SportIcon key={a.id} activity={a}/>)}{row.sessions.length>3&&<small>+{row.sessions.length-3}</small>}</>:null}</span></th><RecoveryCell value={row.sleep} range={result.ranges.sleep} kind="sleep"/><RecoveryCell value={row.hrv} range={result.ranges.hrv} kind="hrv"/><RecoveryCell value={row.rhr} range={result.ranges.rhr} kind="rhr"/></tr>)}</tbody></table></div><div className="workout-recovery-ranges"><span><Moon size={11}/>{rangeText(result.ranges.sleep,'sleep')}</span><span><Activity size={11}/>{rangeText(result.ranges.hrv,'hrv')}</span><span><Heart size={11}/>{rangeText(result.ranges.rhr,'rhr')}</span></div></>}<p className="workout-context-foot">After the whole training day{result.sessions.length>1?' · includes your other sessions':''}. Changes are observations; they do not identify which workout caused them.</p><details className="workout-context-method"><summary>Baseline & coverage</summary><p>Values remain on their recorded morning date. Missing and future readings stay blank. Differences compare with the mean of the 28 calendar days before the training day; usual bands use mean ±2 SD (log scale for HRV), with at least 7 sleep or 14 HRV / resting-HR readings. Minimum spread: 15 minutes for sleep, 0.10 log units for HRV, 2 bpm for resting HR. Sport icons show other recorded sessions on the following days.</p></details></section>;
}
