import {corosNativeActivity,corosNativeSummary,COROS_NATIVE_VERSION} from '../../coros-native';
import {Decoder,Stream} from '@garmin/fitsdk';
import {workoutEvidence} from '../../training-coach-data';
import {sportFamily} from '../../sports';
const finite=(v:any):v is number=>typeof v==='number'&&Number.isFinite(v);
export function applySavedZones(detail:any,zoneVersions:any){const versions=zoneVersions?.[sportFamily(detail)]?.heartrate??{},version=Object.keys(versions).filter(d=>d<=detail.date).sort().at(-1),zones=version?versions[version]:null;if(!Array.isArray(zones)||!zones.length||!detail.hrHistogram)return detail;const totals=zones.map(()=>0);for(const [raw,seconds] of Object.entries(detail.hrHistogram.secondsByBpm)){const bpm=+raw,index=zones.findIndex((z:any)=>finite(z.from)&&finite(z.to)&&(z.from<0||bpm>=z.from)&&(z.to<0||bpm<=z.to));if(index>=0&&finite(seconds))totals[index]+=seconds}return {...detail,summary:{...detail.summary,zonesDistribution:{...detail.summary.zonesDistribution,heartrate:totals},zonesSource:'COROS heart rate · saved Tredict zone boundaries'}}}
export function fitDetail(blob:string,activity:any){const bytes=Uint8Array.from(atob(blob),c=>c.charCodeAt(0));const decoder=new Decoder(Stream.fromByteArray(bytes));if(!decoder.isFIT()||!decoder.checkIntegrity())throw new Error('COROS returned an invalid FIT file.');const {messages,errors}=decoder.read();if(errors.length)throw new Error('COROS FIT file could not be decoded completely.');return decodedFit(messages,activity)}
export function decodedFit(m:any,activity:any){const s=m.sessionMesgs?.[0];if(!s)throw new Error('COROS FIT file has no session.');const family=sportFamily(activity),running=family==='running',start=Date.parse(s.startTime),end=Date.parse(s.timestamp),count=Math.ceil((end-start)/1000);if(!Number.isFinite(count)||count<1||count>604800)throw new Error('Unsupported FIT recording duration.');
 const summary=(s:any)=>{const result:any={};const fields:any={duration:s.totalTimerTime,durationTotal:s.totalElapsedTime,distance:s.totalDistance,calories:s.totalCalories,heartrate:s.avgHeartRate,heartrateMax:s.maxHeartRate,power:s.avgPower,powerMax:s.maxPower,speed:s.enhancedAvgSpeed??s.avgSpeed,speedMax:s.enhancedMaxSpeed??s.maxSpeed,temperature:s.avgTemperature,groundContactTime:s.avgStanceTime,verticalRatio:s.avgVerticalRatio};for(const [k,v] of Object.entries(fields))if(finite(v))result[k]=v;if(finite(s.avgCadence))result.cadence=s.avgCadence*(running?2:1);if(finite(s.avgStepLength))result.stepLength=s.avgStepLength/10;if(finite(s.avgVerticalOscillation))result.verticalOscillation=s.avgVerticalOscillation/10;if(finite(s.totalAscent)||finite(s.totalDescent))result.altitude={ascent:s.totalAscent,descent:s.totalDescent};if(result.speed>0)result.pace=1000/result.speed;return result};
 const data:Record<string,(number|null)[]>={};const assign=(key:string,i:number,v:any)=>{if(!finite(v))return;if(!data[key])data[key]=Array(count).fill(null);data[key][i]=v};const events=(m.eventMesgs??[]).filter((e:any)=>e.event==='timer').sort((a:any,b:any)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));let event=0,active=true;const secondsByBpm:Record<string,number>={};let validSeconds=0,activeSamples=0;const effortField=(m.fieldDescriptionMesgs??[]).find((d:any)=>d.fieldName==='Effort Pace'&&d.units==='m/s')?.key;
 for(const r of m.recordMesgs??[]){const at=Date.parse(r.timestamp),i=Math.round((at-start)/1000);if(i<0||i>=count)continue;while(event<events.length&&Date.parse(events[event].timestamp)<=at){active=events[event].eventType==='start';event++}if(!active)continue;activeSamples++;const fields:any={heartrate:r.heartRate,speed:r.enhancedSpeed??r.speed,power:r.power,distance:r.distance,altitude:r.enhancedAltitude??r.altitude,groundContactTime:r.stanceTime,verticalRatio:r.verticalRatio,temperature:r.temperature,leftRightBalance:r.leftRightBalance,leftTorqueEffectiveness:r.leftTorqueEffectiveness,rightTorqueEffectiveness:r.rightTorqueEffectiveness,leftPedalSmoothness:r.leftPedalSmoothness,rightPedalSmoothness:r.rightPedalSmoothness};for(const [k,v] of Object.entries(fields))assign(k,i,v);assign('cadence',i,finite(r.cadence)?r.cadence*(running?2:1):null);assign('stepLength',i,finite(r.stepLength)?r.stepLength/10:null);assign('verticalOscillation',i,finite(r.verticalOscillation)?r.verticalOscillation/10:null);assign('positionLat',i,finite(r.positionLat)?r.positionLat*180/2147483648:null);assign('positionLong',i,finite(r.positionLong)?r.positionLong*180/2147483648:null);if(effortField!==undefined)assign('speedGradeAdjusted',i,r.developerFields?.[effortField]);if(r.heartRate>0&&r.heartRate<300){const bpm=Math.round(r.heartRate);secondsByBpm[bpm]=(secondsByBpm[bpm]??0)+1;validSeconds++}}
 const merged={...corosNativeSummary(activity.summary,activity.nativeVersion===COROS_NATIVE_VERSION),...summary(s)};const hrBands=[0,0,0,0,0];for(const [hr,t] of Object.entries(secondsByBpm)){const bpm=+hr;hrBands[bpm<120?0:bpm<140?1:bpm<160?2:bpm<180?3:4]+=t}if(validSeconds)merged.hrBands=hrBands; if(Array.isArray(s.timeInHrZone)&&s.timeInHrZone.some(finite))merged.zonesDistribution={heartrate:s.timeInHrZone};const detail={...corosNativeActivity(activity),nativeVersion:COROS_NATIVE_VERSION,summary:merged,laps:(m.lapMesgs??[]).map((l:any,i:number)=>({lap:i+1,...summary(l)})),seriesSampled:{sampleSize:1,data},hrHistogram:{secondsByBpm,validSeconds,missingSeconds:Math.max(0,(merged.duration??activeSamples)-validSeconds),sampleSeconds:1},recordedSource:'COROS FIT'};return {...detail,evidence:workoutEvidence(detail)}
}
