import {corosRecords,corosSleep,corosHrv,corosResting} from '../../coros-data';
import {day,captureCoros} from './library';
const args=(from:string,to:string)=>({startDate:from.replaceAll('-',''),endDate:to.replaceAll('-',''),sportTypeCodes:[65535],minDistanceKm:0,maxDistanceKm:100000,minDurationMinutes:0,maxDurationMinutes:100000,maxAveragePace:'',locationKeyword:'',limit:1500});
export async function importCorosHistory(client:any,previous:any,now:Date){const recent=new Date(now.getTime()-30*86400000).toISOString().slice(0,10),today=now.toISOString().slice(0,10),migration=previous?.extra?.coros?.importVersion!==2;const state=previous?.extra?.coros?.history;
 let pending:[string,string][]=migration?[['2000-01-01',today]]:[...(state?.pending??[])],fresh=corosRecords(await client.call('querySportRecords',args(recent,today)));const map=new Map<string,any>((previous?.activities??[]).filter((a:any)=>a.provider==='coros'&&a.date.slice(0,10)<recent).map((a:any)=>[a.id,a]));for(const a of fresh)map.set(a.id,a);
 let issue:string|undefined;if(fresh.length>=1500)pending.unshift([recent,today]);
 for(let i=0;i<2&&pending.length;i++){const [from,to]=pending[0];try{const rows=corosRecords(await client.call('querySportRecords',args(from,to)));pending.shift();for(const a of rows)map.set(a.id,a);if(rows.length>=1500){const start=Date.parse(from+'T00:00:00Z'),end=Date.parse(to+'T00:00:00Z');if(end<=start){pending.unshift([from,to]);issue='COROS returned 1,500 sessions for one day; that day needs a separate export.';break}const mid=new Date(start+Math.floor((end-start)/86400000/2)*86400000),next=new Date(mid.getTime()+86400000);pending.unshift([from,mid.toISOString().slice(0,10)],[next.toISOString().slice(0,10),to])}}catch{issue='Older workout history will retry on the next sync.';break}}
 return {activities:[...map.values()],history:{pending,complete:pending.length===0,from:'2000-01-01',through:today,issue}};
}
export async function importRecoveryHistory(owner:string,client:any,previous:any,oldest:string,now:Date){const prior=previous?.extra?.coros,fromDay=prior?.recoveryHistory?.nextEnd??day(new Date(now.getTime()-28*86400000));const sleep:any={},hrv:any={};let nextEnd=fromDay,completed=!!prior?.recoveryHistory?.complete,issue:string|undefined;const end=new Date(nextEnd.slice(0,4)+'-'+nextEnd.slice(4,6)+'-'+nextEnd.slice(6,8)+'T00:00:00Z');if(!completed){const start=new Date(end.getTime()-6*86400000),args={startDate:day(start),endDate:day(end),days:7};try{const [s,h]=await Promise.all([client.call('querySleepData',args),client.call('querySleepHrv',args)]);const parsed=corosSleep(s);Object.assign(sleep,parsed.sleep);Object.assign(hrv,corosHrv(h));await Promise.all([captureCoros(owner,'querySleepData',s,args),captureCoros(owner,'querySleepHrv',h,args)]);nextEnd=day(new Date(start.getTime()-86400000));completed=nextEnd<oldest.replaceAll('-','');return {sleep,hrv,windows:parsed.windows,state:{nextEnd,complete:completed,through:args.endDate,from:args.startDate}}}catch{issue='Older sleep and HRV will retry on the next sync.'}}return {sleep,hrv,windows:{},state:{nextEnd,complete:completed,issue}}}
