import {accessCredentials,issuer,CorosConnection,CorosError} from '../../../db/coros';
export function unwrapTool(result:any){if(result?.isError)throw new CorosError('COROS could not return this data. Try syncing again.');if(result?.structuredContent)return result.structuredContent;const texts=(result?.content??[]).filter((x:any)=>x.type==='text').map((x:any)=>x.text);for(const value of texts){try{return JSON.parse(value)}catch{/* Some tools return a JSON fenced block. */}const fenced=value.match(/```(?:json)?\s*([\s\S]*?)```/);if(fenced)try{return JSON.parse(fenced[1])}catch{}}return {text:texts.join('\n')}}
export async function createCorosClient(row:CorosConnection){const credentials=await accessCredentials(row);const endpoint=issuer(row.region)+'/mcp';let session='';let nextId=0;
 async function rpc(method:string,params?:any,notify=false){const id=notify?undefined:++nextId;const response=await fetch(endpoint,{method:'POST',redirect:'manual',headers:{Authorization:'Bearer '+credentials.accessToken,'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-03-26',...(session?{'Mcp-Session-Id':session}:{})},body:JSON.stringify({jsonrpc:'2.0',...(id===undefined?{}:{id}),method,params}),signal:AbortSignal.timeout(45000)});if(response.status===401||response.status===403)throw new CorosError('Reconnect COROS to continue syncing.',401);if(response.status===429)throw new CorosError('COROS is limiting requests. Your saved data is unchanged; try again later.',429);if(!response.ok)throw new CorosError('COROS is temporarily unavailable. Your saved data is unchanged.');session=response.headers.get('mcp-session-id')||session;if(notify)return null;let message:any;
 if(response.headers.get('content-type')?.includes('text/event-stream')){const reader=response.body?.getReader();if(!reader)throw new CorosError('Empty COROS response.');const decoder=new TextDecoder();let buffer='',size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>12000000)throw new CorosError('COROS returned too much data for one request.');buffer+=decoder.decode(value,{stream:true}).replace(/\r\n/g,'\n');let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const event=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const raw=event.split('\n').filter(v=>v.startsWith('data:')).map(v=>v.slice(5).trimStart()).join('\n');if(!raw)continue;const parsed=JSON.parse(raw);if(parsed.id===id){message=parsed;break}}if(message)break}}finally{await reader.cancel()}}
 else message=await response.json();if(message?.error)throw new CorosError('COROS rejected this data request. Please try again.');if(message?.id!==id||!('result' in message))throw new CorosError('COROS returned an unexpected response.');return message.result;
 }
 await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'sieste',version:'1.0.0'}});await rpc('notifications/initialized',undefined,true);const catalogue=await rpc('tools/list');const tools:any[]=catalogue?.tools??[];
 return {tools,async callRaw(name:string,args:any={}){const tool=tools.find(t=>t.name.toLowerCase()===name.toLowerCase());if(!tool)throw new CorosError("COROS tool unavailable.",422);return rpc("tools/call",{name:tool.name,arguments:args})},async call(name:string,args:any={}){const tool=tools.find(t=>t.name.toLowerCase()===name.toLowerCase());if(!tool)throw new CorosError(`COROS has not enabled ${name} for this connection.`,422);return unwrapTool(await rpc('tools/call',{name:tool.name,arguments:args}))}};
}
