import {refreshHealth,healthDay,hasSleepWindowReading,hasDailyReading,overnightSources} from './refresh-policy';
import {corosNativeActivity,corosNativeSnapshot,COROS_NATIVE_VERSION} from '../../coros-native';
import {extendCoros,captureCoros} from './library';
import {importCorosHistory,importRecoveryHistory} from './history';
import {corosPredictions,repairRacePredictions} from '../../coros-extended-data';
import {storage,ownerPrefix} from '../../../db/storage';
import {corosConnection,corosPrefix,CorosConnection,CorosError} from '../../../db/coros';
import {restoreAnalyses,saveAnalysis} from '../../../db/activity-analysis';
import {filteredSnapshot,workoutExclusions} from '../../../db/workout-exclusions';
import {sessionLabels} from '../../session-intelligence-data';
import {createCorosClient} from './mcp';
import {fitDetail} from './fit';
import {corosRecords,corosSleep,corosHrv,corosResting,corosDaily,corosFitness,corosRecovery,corosLoad,corosSummary,corosLaps} from '../../coros-data';
const date=(d:Date)=>d.toISOString().slice(0,10).replaceAll('-','');
const identity=(row:CorosConnection)=>'coros:'+row.revision;
export async function corosSnapshot(row:CorosConnection){const object=row.snapshot_key?await storage().bucket.get(row.snapshot_key):null;if(!object)return null;const data=corosNativeSnapshot(await object.json());const cached=data.extra?.coros?.fitness?.predictionVersion!==2?await storage().bucket.get((await ownerPrefix(row.owner))+'coros-library/queryFitnessAssessmentOverview.json'):null;return filteredSnapshot(row.owner,await restoreAnalyses(row.owner,identity(row),repairRacePredictions(data,cached?await cached.json():null)))}
const inFlight=new Map<string,Promise<any>>();
export async function syncCoros(row:CorosConnection,wellnessOnly=false,options:{manual?:boolean;timeZone?:string;primary?:any}={}){const existing=inFlight.get(row.owner);if(existing)return existing;const task=performSync(row,wellnessOnly,options);inFlight.set(row.owner,task);try{return await task}finally{inFlight.delete(row.owner)}}
async function performSync(row:CorosConnection,wellnessOnly:boolean,options:{manual?:boolean;timeZone?:string;primary?:any}){const previous=await corosSnapshot(row);if(!options.manual&&previous?.syncedAt&&Date.now()-Date.parse(previous.syncedAt)<60000)return previous;const client=await createCorosClient(row),now=new Date(),oldest=new Date(Date.UTC(now.getUTCFullYear()-1,0,1)-31*86400000),recent=new Date(now.getTime()-30*86400000),from=previous?recent:oldest;const warnings:string[]=[],prefix=(await corosPrefix(row.owner))+row.revision+'/';
 const imported=wellnessOnly?{activities:previous?.activities??[],history:previous?.extra?.coros?.history??{from:date(now),complete:false}}:await importCorosHistory(client,previous,now);const fresh=imported.activities;
 const activities=fresh.map(corosNativeActivity);const sources:any={...previous?.sources},extra:any={...previous?.extra};
 // Load scores from COROS only. Tredict effort and COROS load use different scales.
 extra.efforts={trainingEfforts:{}};extra.bodyvalues=previous?.extra?.coros?.importVersion===2?previous.extra.bodyvalues:{bodyvalues:[]};const nativePrevious=previous?.extra?.coros?.importVersion===2?previous:null;let sleep:any={...nativePrevious?.sleep},hrv:any={...nativePrevious?.hrv};let sleepWindows:any={...previous?.extra?.coros?.sleepWindows};let daily:any={...previous?.extra?.coros?.daily};let fitness=previous?.extra?.coros?.fitness,recovery=previous?.extra?.coros?.recovery,load=previous?.extra?.coros?.load;
 const today=healthDay(now,options.timeZone);const healthStart=new Date(now.getTime()-(previous?2:89)*86400000);const requests:[string,any,(v:any)=>void][]=[['querySleepData',{startDate:date(healthStart),endDate:today,days:previous?3:90},v=>{const parsed=corosSleep(v);sleep={...sleep,...parsed.sleep};sleepWindows={...sleepWindows,...parsed.windows}}],['queryRestingHeartRate',{days:previous?3:90},v=>{const rows=corosResting(v);const days=new Set(rows.map(r=>r.timestamp.slice(0,10)));extra.bodyvalues={bodyvalues:[...(nativePrevious?.extra?.bodyvalues?.bodyvalues??[]).map((r:any)=>days.has(r.timestamp.slice(0,10))?Object.fromEntries(Object.entries(r).filter(([k])=>k!=='hrRestDynamic')):r),...rows]}}],['queryDailyHealthData',{days:28},v=>{daily={...daily,...corosDaily(v)}}],['queryFitnessAssessmentOverview',{},v=>{fitness={...corosFitness(v),predictions:corosPredictions(v),predictionVersion:2,observedAt:now.toISOString()}}],['queryRecoveryStatus',{},v=>{recovery={...corosRecovery(v),observedAt:now.toISOString()}}],['queryTrainingLoadAssessment',{days:90},v=>{load=corosLoad(v)}]];
 for(let i=0;i<(previous?1:4);i++){const end=new Date(now.getTime()-i*7*86400000),start=new Date(end.getTime()-6*86400000);requests.push(['querySleepHrv',{startDate:date(start),endDate:i===0?today:date(end),days:7},v=>{hrv={...hrv,...corosHrv(v)}}])}
 for(let i=0;i<requests.length;i+=4)await Promise.all(requests.slice(i,i+4).map(async([name,args,apply])=>{const old=sources[name];const hasToday=(name==='querySleepData'?hasSleepWindowReading(today,sleep,sleepWindows):hasDailyReading(name,today,sleep,hrv,extra.bodyvalues?.bodyvalues??[]))||(['querySleepHrv','queryRestingHeartRate'].includes(name)&&!!options.primary&&hasDailyReading(name,today,options.primary.sleep,options.primary.hrv,options.primary.extra?.bodyvalues?.bodyvalues??[]));if(!refreshHealth(name,old,now,hasToday,!!options.manual))return;try{const value=await client.call(name,args);await captureCoros(row.owner,name,value,args);apply(value);const ready=!overnightSources.includes(name)||(name==='querySleepData'?hasSleepWindowReading(today,sleep,sleepWindows):hasDailyReading(name,today,sleep,hrv,extra.bodyvalues?.bodyvalues??[]));sources[name]={status:ready?'synced':'pending',provider:'coros',retrievedAt:now.toISOString()};if(!ready)warnings.push(`${name==='querySleepData'?'Sleep':name==='querySleepHrv'?'Overnight HRV':'Resting HR'} for today is not available from COROS yet. Refresh again after your watch has synced.`)}catch(e){sources[name]={...old,status:'unavailable',provider:'coros',attemptedAt:now.toISOString()};warnings.push(`${name.replace(/^query/,'')} could not be refreshed from COROS; saved values remain.`)}}));
 const recentPrimary=(wellnessOnly?[]:activities).filter((a:any)=>a.provider==='coros'&&Date.parse(a.date)>now.getTime()-14*86400000).slice(0,40);for(let i=0;i<recentPrimary.length;i+=4)await Promise.all(recentPrimary.slice(i,i+4).map(async(a:any)=>{try{const key=prefix+'summary/'+a.id+'.json',cached=await storage().bucket.get(key);let summary;if(cached)summary=await cached.json();else{summary=corosSummary(await client.call('getActivityDetail',a.coros));await storage().bucket.put(key,JSON.stringify(summary))}a.summary={...a.summary,...summary}}catch{warnings.push('Some recent COROS workout loads are not available yet.')}}));
 const grouped=new Map<string,any[]>();for(const a of activities){const day=(a.localDay??a.date.slice(0,10)).replaceAll('-','');const group=grouped.get(day)??[];group.push(a);grouped.set(day,group)}for(const [day,rows] of grouped)if(rows.every(a=>a.provider==='coros'&&Number.isFinite(a.summary?.trainingLoad)))extra.efforts.trainingEfforts[day]=rows.map(a=>[a.summary.trainingLoad]);
 const extended=await extendCoros(row.owner,client,previous?.extra?.coros,now);const earliest=activities.filter((a:any)=>a.provider==='coros').map((a:any)=>a.date.slice(0,10)).sort()[0]??now.toISOString().slice(0,10);const backfill=previous?.extra?.coros?.recoveryHistory?.checkedOn===date(now)?{sleep:{},hrv:{},windows:{},state:previous.extra.coros.recoveryHistory}:await importRecoveryHistory(row.owner,client,previous,earliest,now);backfill.state={...backfill.state,checkedOn:date(now)};sleep={...sleep,...backfill.sleep};hrv={...hrv,...backfill.hrv};sleepWindows={...sleepWindows,...backfill.windows};
 extra.coros={...extended,sleepWindows,daily,fitness,recovery,load,importVersion:2,history:imported.history,recoveryHistory:backfill.state};
 if(extended.profile){const p=extended.profile;extra.bodyvalues??={bodyvalues:[]};extra.bodyvalues.bodyvalues.push({timestamp:now.toISOString(),weightInKilograms:p.weight,heightInCentimeters:p.height,source:'COROS'})}
 // Preserve the old archive without allowing it to masquerade as current COROS data.
 extra.coros.archivedZones=extra.zones;delete extra.zones;delete extra.equipmentList;delete extra.plannedTrainingList;sources.efforts={status:'partial',provider:'coros'};
 extra.coros.fitnessHistory={...previous?.extra?.coros?.fitnessHistory,...(sources.queryFitnessAssessmentOverview?.retrievedAt===now.toISOString()?{[date(now)]:fitness}:{})};
const exclusions=await workoutExclusions(row.owner);const aliases=new Map(activities.filter((a:any)=>a.fallbackId).map((a:any)=>[a.fallbackId,a.id]));for(const e of exclusions){const alias=aliases.get(e.id);if(alias&&!exclusions.some(x=>x.id===alias))await storage().bucket.put((await ownerPrefix(row.owner))+'excluded/'+alias+'.json',JSON.stringify({id:alias,date:e.date}),{customMetadata:{date:e.date}})}
 const data={provider:'coros',activities,sleep,hrv,extra,sources,historyStart:imported.history.from+'T00:00:00Z',historyComplete:imported.history.complete,historyVersion:3,warnings:[...new Set(warnings)],syncedAt:now.toISOString(),sourceNote:'COROS · native workout and health data'};const snapshotKey=prefix+'snapshots/'+crypto.randomUUID()+'.json';await storage().bucket.put(snapshotKey,JSON.stringify(data),{httpMetadata:{contentType:'application/json'}});const update=await storage().db.prepare('UPDATE coros_connections SET snapshot_key = ?, updated_at = ? WHERE owner = ? AND revision = ? AND updated_at = ?').bind(snapshotKey,now.toISOString(),row.owner,row.revision,row.updated_at).run();if(!update.meta.changes){await storage().bucket.delete(snapshotKey);throw new CorosError('Your connection changed during sync. Please retry.',409)}if(row.snapshot_key)await storage().bucket.delete(row.snapshot_key);return filteredSnapshot(row.owner,await restoreAnalyses(row.owner,identity(row),data));
}
export async function corosAction(row:CorosConnection,payload:any){const {bucket,db}=storage(),object=row.snapshot_key?await bucket.get(row.snapshot_key):null;const snapshot:any=object?corosNativeSnapshot(await object.json()):null;if(!snapshot)throw new CorosError('Sync COROS before opening workouts.',409);const ids=payload.action==='enrich'?payload.ids:[payload.id];if(!Array.isArray(ids)||ids.length<1||ids.length>4||ids.some((id:any)=>typeof id!=='string'||!/^coros_\d+_[\w-]{1,100}$/.test(id)))throw new CorosError('Invalid COROS activity selection.',400);const activities=ids.map(id=>snapshot.activities.find((a:any)=>a.id===id));if(activities.some(a=>!a))throw new CorosError('Workout not found in your account.',404);const prefix=(await corosPrefix(row.owner))+row.revision+'/';
 if(payload.action==='remove'||payload.action==='restore'){const a=activities[0],keys=[a.id,...(a.fallbackId?[a.fallbackId]:[])];for(const id of keys){const key=(await ownerPrefix(row.owner))+'excluded/'+id+'.json';if(payload.action==='remove')await bucket.put(key,JSON.stringify({id,date:a.date}),{customMetadata:{date:a.date}});else await bucket.delete(key)}return {excludedWorkouts:await workoutExclusions(row.owner)}}
 if((await workoutExclusions(row.owner)).some(e=>ids.includes(e.id)))throw new CorosError('This workout was removed from sieste.',404);
 if(payload.action==='classify'){if(payload.label!==null&&!sessionLabels.includes(payload.label))throw new CorosError('Invalid session label.',400);if(payload.label===null)await db.prepare('DELETE FROM athlete_session_labels WHERE owner = ? AND identity = ? AND activity_id = ?').bind(row.owner,identity(row),ids[0]).run();else await db.prepare('INSERT INTO athlete_session_labels (owner,identity,activity_id,label) SELECT ?,?,?,? WHERE EXISTS (SELECT 1 FROM coros_connections WHERE owner = ? AND revision = ?) ON CONFLICT(owner,identity,activity_id) DO UPDATE SET label=excluded.label').bind(row.owner,identity(row),ids[0],payload.label,row.owner,row.revision).run();return {label:payload.label}}
 let client:Awaited<ReturnType<typeof createCorosClient>>|null=null;const getClient=async()=>client??(client=await createCorosClient(row));const details=[];
 for(const a of activities){const fullKey=prefix+'native-detail-v3/'+a.id+'.json',cached=await bucket.get(fullKey);let detail:any;if(cached)detail=await cached.json();else{const previewKey=prefix+'native-preview-v3/'+a.id+'.json',preview=await bucket.get(previewKey);if(preview)detail=await preview.json();else{const c=await getClient();const [summary,laps]=await Promise.all([c.call('getActivityDetail',a.coros),c.call('queryActivityLapData',a.coros)]);detail={...a,summary:{...a.summary,...corosSummary(summary)},laps:corosLaps(laps),recordedSource:'COROS',nativeVersion:COROS_NATIVE_VERSION};await bucket.put(previewKey,JSON.stringify(detail))}
 if(payload.action!=='preview'){const saved=await bucket.get(prefix+'fit/'+a.id+'.fit');let blob:string;if(saved){const bytes=new Uint8Array(await saved.arrayBuffer());blob=btoa(Array.from(bytes,b=>String.fromCharCode(b)).join(''))}else{const day=new Date().toISOString().slice(0,10);const usage=await db.prepare('INSERT INTO coros_fit_usage (owner,day,count) VALUES (?,?,1) ON CONFLICT(owner,day) DO UPDATE SET count=count+1 WHERE count<? RETURNING count').bind(row.owner,day,payload.background?45:50).first();if(!usage)throw new CorosError(payload.background?'Automatic COROS imports have paused for today. The remaining download allowance is reserved for activities you open.':'COROS’s daily detailed-file limit is reached. Saved workouts remain available; more details can load tomorrow.',429);const raw=await (await getClient()).callRaw('downloadActivityFitFiles',{...a.coros,limit:1});if(raw?.isError)throw new CorosError('COROS could not supply this workout file. Its daily file limit may have been reached.',429);const resource=raw?.content?.find((c:any)=>c.type==='resource'&&c.resource?._meta?.labelId===a.coros.labelId&&typeof c.resource?.blob==='string');if(!resource)throw new CorosError('COROS did not return this workout’s FIT data.');await bucket.put(prefix+'fit/'+a.id+'.fit',Uint8Array.from(atob(resource.resource.blob),c=>c.charCodeAt(0)));blob=resource.resource.blob;}
detail={...fitDetail(blob,detail),analysisSource:'COROS FIT'};const current=await corosConnection(row.owner);if(current?.revision!==row.revision)throw new CorosError('Your connection changed. Please reload.',409);await bucket.put(fullKey,JSON.stringify(detail),{httpMetadata:{contentType:'application/json'}})}}
 if(payload.action!=='preview')await saveAnalysis(row.owner,identity(row),a,detail,row.revision,'coros');const label=await db.prepare('SELECT label FROM athlete_session_labels WHERE owner = ? AND identity = ? AND activity_id = ?').bind(row.owner,identity(row),a.id).first<{label:string}>();details.push({...detail,analysisSource:payload.action!=='preview'?'COROS FIT':undefined,sessionLabel:label?.label??a.sessionLabel??null});}
 return {details};
}
