import {getChatGPTUser} from '../../../chatgpt-auth';
import {storage,privateJson,sameOrigin} from '../../../../db/storage';
import {corosConnection,corosPrefix,CorosError} from '../../../../db/coros';
import {createCorosClient} from '../mcp';
export const dynamic='force-dynamic';
// Private, bounded connection check. Preserve original tool responses until their
// units and fields have been verified; never guess a mapping into athlete charts.
export async function GET(){const user=await getChatGPTUser();if(!user)return privateJson({error:'Sign in first.'},401);try{const row=await corosConnection(user.userId);if(!row)return privateJson({error:'Connect COROS first.'},409);const object=await storage().bucket.get((await corosPrefix(user.userId))+row.revision+'/connection-check.json');return privateJson({connected:true,check:object?await object.json():null})}catch{return privateJson({error:'Could not load the connection check.'},503)}}
export async function POST(request:Request){if(!sameOrigin(request))return privateJson({error:'Cross-site request rejected.'},403);const user=await getChatGPTUser();if(!user)return privateJson({error:'Sign in first.'},401);try{const row=await corosConnection(user.userId);if(!row)return privateJson({error:'Connect COROS first.'},409);const key=(await corosPrefix(user.userId))+row.revision+'/connection-check.json';const prior=await storage().bucket.get(key);if(prior){const p:any=await prior.json();if(Date.now()-Date.parse(p.checkedAt)<300000)return privateJson({checked:true,available:p.available,errors:p.errors})}const client=await createCorosClient(row);const end=new Date(),start=new Date(end);start.setUTCDate(start.getUTCDate()-7);const date=(d:Date)=>d.toISOString().slice(0,10).replaceAll('-','');const queries=[['querySportRecords',{startDate:date(start),endDate:date(end),limit:3,sportTypeCodes:[65535],minDistanceKm:0,maxDistanceKm:100000,minDurationMinutes:0,maxDurationMinutes:100000,maxAveragePace:'',locationKeyword:''}],['queryDailyHealthData',{days:7}],['querySleepData',{startDate:date(start),endDate:date(end),days:7}],['querySleepHrv',{startDate:date(start),endDate:date(end),days:7}],['queryRestingHeartRate',{days:7}]] as const;const data:Record<string,unknown>={},errors:Record<string,string>={};for(const [name,args] of queries){try{data[name]=await client.call(name,args)}catch(e){errors[name]=e instanceof CorosError?e.message:'Data could not be retrieved.'}}const check={checkedAt:new Date().toISOString(),available:Object.keys(data),errors,tools:client.tools,data};const current=await corosConnection(user.userId);if(current?.revision!==row.revision)return privateJson({error:'Connection changed. Please retry.'},409);await storage().bucket.put(key,JSON.stringify(check),{httpMetadata:{contentType:'application/json'}});return privateJson({checked:true,available:check.available,errors})}catch(e){return privateJson({error:e instanceof CorosError?e.message:'Could not check COROS. Please try again.'},e instanceof CorosError?e.status:503)}}
